dotnet/docs-aspire

docs/index.yml
Deep link to .NET Aspire API for now, until prod is approved
=> Deep link to .NET Aspire API for now, until prod is approved

docs/includes/aspire-prereqs.md
=> update vs preview

.github/fabricbot.json, .github/workflows/markdownlint.yml, .github/workflows/quest-bulk.yml, .github/workflows/quest.yml, .markdownlint-cli2.jsonc, docs/deployment/azure/aca-deployment-azd-in-depth.md
In this PR:
- Fix markdownlint workflow
- Add missing Quest workflows
- Address MD issues
- Add fabricbot
---
|:--|:--|
| [docs/deployment/azure/aca-deployment-azd-in-depth.md](https://github.com/dotnet/docs-aspire/blob/1ab0b03417c2272e86e88d7749f994b2817bc09a/docs/deployment/azure/aca-deployment-azd-in-depth.md) | [Deploy a .NET Aspire app to Azure Container Apps using the Azure Developer CLI (in-depth guide)](https://review.learn.microsoft.com/en-us/dotnet/deployment/azure/aca-deployment-azd-in-depth?branch=pr-en-us-41) |
=> Add config to workflow

.github/workflows/check-for-build-warnings.yml, .github/workflows/quest-bulk.yml, .github/workflows/quest.yml, docfx.json, quest-config.json
Misc fixes for various configs
=> Misc fixes for various configs

docs/deployment/azure/includes/aca-deployment-azd.md
=> Fixed typo

docs/deployment/azure/includes/aca-deployment-cli.md
The include file for Azure CLI in the Azure Container Apps deployment tutorial is completed.
=> Completed Azure CLI deployment include file

docs/deployment/azure/aca-deployment.md
The title of aca-development.md detailed "Bicep", making it a bit misleading when saving a link to the page in favorites, since the content isn't specific to bicep (and by default doesn't have any bicep details).
---
|:--|:--|
| [docs/deployment/azure/aca-deployment.md](https://github.com/dotnet/docs-aspire/blob/a105459a41d84fe52d961e2332e5f4106f9eeec6/docs/deployment/azure/aca-deployment.md) | [Deploy a .NET Aspire app to Azure Container Apps](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment?branch=pr-en-us-76) |
=> Refined title in aca-deployment.md

docs/reference/aspire-faq.yml
Added a question to the FAQ on the relationship between .NET Aspire and Kubernetes.
Fixes #69
=> FAQ Additional question about K8s

docs/get-started/aspire-overview.md
Added a definition of "distributed application" and how they relate to cloud-native apps.
Fixes #80
---
|:--|:--|
| [docs/get-started/aspire-overview.md](https://github.com/dotnet/docs-aspire/blob/5d4f9cee59071aae1b797dc21654d5e2645bed39/docs/get-started/aspire-overview.md) | [.NET Aspire overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/aspire-overview?branch=pr-en-us-93) |
=> Added a definition of distributed application.

docs/database/postgresql-entity-framework-component.md
Fixes #96
---
|:--|:--|
| [docs/database/postgresql-entity-framework-component.md](https://github.com/dotnet/docs-aspire/blob/17179246d3cdaadf5d5a141ec6148bc088e7526f/docs/database/postgresql-entity-framework-component.md) | [.NET Aspire PostgreSQL Entity Framework Core component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/postgresql-entity-framework-component?branch=pr-en-us-100) |
=> Fix code in example

docs/deployment/azure/aca-deployment-azd-in-depth.md
Fixes #71
---
|:--|:--|
| [docs/deployment/azure/aca-deployment-azd-in-depth.md](https://github.com/dotnet/docs-aspire/blob/9990e22e1243a4c2ebc8613e115c5a78316e081d/docs/deployment/azure/aca-deployment-azd-in-depth.md) | [Deploy a .NET Aspire app to Azure Container Apps using the Azure Developer CLI (in-depth guide)](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-azd-in-depth?branch=pr-en-us-98) |
=> Add note about ACR admin user

docs/messaging/quickstart-messaging.md
---
|:--|:--|
| [docs/messaging/quickstart-messaging.md](https://github.com/dotnet/docs-aspire/blob/422b3e728477511c88442ff74442cf7b9b776368/docs/messaging/quickstart-messaging.md) | [Tutorial: Use .NET Aspire messaging components in ASP.NET Core](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/quickstart-messaging?branch=pr-en-us-115) |
=> fixed appsettings.json name/italicization in quickstart-messaging.md

docs/deployment/azure/includes/aca-deployment-azd.md
Fix incorrect image
Fixes #124
=> Fix incorrect image

docs/deployment/azure/k8s-deployment.md, docs/deployment/k8s-deployment.md, docs/toc.yml
A new document that covers deployment to a Kubernetes cluster by using the [Aspirate tool](https://www.nuget.org/packages/Aspirate)
---
|:--|:--|
| [docs/deployment/k8s-deployment.md](https://github.com/dotnet/docs-aspire/blob/8c17346bdb05a5ee71e3c3f9444e1aab0ae00b96/docs/deployment/k8s-deployment.md) | [Deploy .NET Aspire apps to a Kubernetes cluster](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/k8s-deployment?branch=pr-en-us-134) |
=> Deploy to to Kubernetes by using the Aspirate tool

.openpublishing.redirection.json, docs/caching/caching-components.md, docs/dashboard.md, docs/database/sql-server-components.md, docs/deployment/k8s-deployment.md, docs/get-started/aspire-overview.md, docs/get-started/build-your-first-aspire-app.md, docs/index.yml, docs/messaging/messaging-components.md, docs/reference/aspire-faq.yml, docs/service-defaults.md, docs/storage/azure-storage-components.md, docs/toc.yml
Adjust hub, `ms.topics`, `title` and H1 prefixes, etc. Fixes: #141
---
|:--|:--|
| [docs/caching/caching-components.md](https://github.com/dotnet/docs-aspire/blob/36e9b3fd8a0a7b7514f00e1a48c3554b527e67d0/docs/caching/caching-components.md) | [Tutorial: Implement caching with .NET Aspire components](https://review.learn.microsoft.com/en-us/dotnet/aspire/caching/caching-components?branch=pr-en-us-140) |
| [docs/dashboard.md](https://github.com/dotnet/docs-aspire/blob/36e9b3fd8a0a7b7514f00e1a48c3554b527e67d0/docs/dashboard.md) | [.NET Aspire dashboard overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/dashboard?branch=pr-en-us-140) |
| [docs/database/sql-server-components.md](https://github.com/dotnet/docs-aspire/blob/36e9b3fd8a0a7b7514f00e1a48c3554b5 …
=> Let's see what this looks like

docfx.json
=> Update the repo config, docfx.json

docs/fundamentals/components-overview.md
---
|:--|:--|
| [docs/fundamentals/components-overview.md](https://github.com/dotnet/docs-aspire/blob/4087b50af0506bdec34c8bfb7f40767dd46ccd5f/docs/fundamentals/components-overview.md) | [.NET Aspire components overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/components-overview?branch=pr-en-us-250) |
=> Fix broken component table

docs/database/snippets/tutorial/aspiresqlefcore/AspireSQLEFCore.AppHost/AspireSQLEFCore.AppHost.csproj, docs/database/snippets/tutorial/aspiresqlefcore/AspireSQLEFCore/AspireSQLEFCore.csproj, docs/fundamentals/snippets/components/AspireApp/AspireApp.AppHost/AspireApp.AppHost.csproj, docs/fundamentals/snippets/template/YourAppName/YourAppName.ServiceDefaults.csproj, docs/get-started/snippets/quickstart/AspireSample/AspireSample.AppHost/AspireSample.AppHost.csproj, docs/storage/snippets/tutorial/AspireStorage/AspireStorage.AppHost/AspireStorage.AppHost.csproj
=> Bump version

docs/caching/caching-components.md
Change order of tutorial items in cache tutorial
closes #278
---
|:--|:--|
| [docs/caching/caching-components.md](https://github.com/dotnet/docs-aspire/blob/bdf8ee19d3f66c1e8a20a5fccad2054f0526aae5/docs/caching/caching-components.md) | [Tutorial: Implement caching with .NET Aspire components](https://review.learn.microsoft.com/en-us/dotnet/aspire/caching/caching-components?branch=pr-en-us-293) |
=> New Cache tutorial

.github/workflows/check-for-build-warnings.yml, .github/workflows/snippets5000.yml
Prevents hanging build validations... For example, https://github.com/dotnet/docs-aspire/pull/312
=> Only trigger Snippets 5000 and status checks on valid code changes.

.github/workflows/check-for-build-warnings.yml, .github/workflows/snippets5000.yml
Reverts dotnet/docs-aspire#313
=> Revert "Only trigger Snippets 5000 and status checks on valid code changes."

docs/caching/stackexchange-redis-component.md, docs/caching/stackexchange-redis-distributed-caching-component.md, docs/caching/stackexchange-redis-output-caching-component.md, docs/database/azure-cosmos-db-component.md, docs/database/azure-cosmos-db-entity-framework-component.md, docs/database/mongodb-component.md, docs/database/mysql-component.md, docs/database/postgresql-component.md, docs/database/postgresql-entity-framework-component.md, docs/database/sql-server-component.md, docs/database/sql-server-components.md, docs/database/sql-server-entity-framework-component.md, docs/fundamentals/components-overview.md, docs/get-started/aspire-overview.md, docs/includes/azure-component-nuget.md, docs/messaging/azure-service-bus-component.md, docs/messaging/messaging-components.md, docs/messaging/rabbitmq-client-component.md, docs/security/azure-security-key-vault-component.md, docs/storage/azure-storage-blobs-component.md, docs/storage/azure-storage-components.md, docs/storage/azure-storage-queues-component.md, docs/storage/azure-storage-tables-component.md
- Restructure components, example usage, then app host, then config.
- Add `Aspire.Hosting.Azure` for Azure components.
- Normalize app host, AppHost, and Orchestrator terminology.
Issues fixed by this PR:
- Fixes #311
- Fixes #314
---
|:--|:--|
| [docs/caching/stackexchange-redis-component.md](https://github.com/dotnet/docs-aspire/blob/ec45ab4dc0ae6d2945151768c9a15fad6d44edbe/docs/caching/stackexchange-redis-component.md) | [.NET Aspire StackExchange Redis component](https://review.learn.microsoft.com/en-us/dotnet/aspire/caching/stackexchange-redis-component?branch=pr-en-us-315) |
| [docs/caching/stackexchange-redis-distributed-caching-component.md](https://github.com/dotnet/docs-aspire/bl …
=> Restructure components, and add Azure hosting bits

docs/get-started/build-aspire-apps-with-nodejs.md
This PR updates the description for the sample that's changed in https://github.com/dotnet/aspire-samples/pull/101
cc @IEvangelist 
---
|:--|:--|
| [docs/get-started/build-aspire-apps-with-nodejs.md](https://github.com/dotnet/docs-aspire/blob/db4c9337561e9f580aa10a63c7fa045070733780/docs/get-started/build-aspire-apps-with-nodejs.md) | [Build .NET Aspire apps with Node.js](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/build-aspire-apps-with-nodejs?branch=pr-en-us-328) |
=> update Angular Aspire description to match the sample

docs/deployment/manifest-format.md
---
|:--|:--|
| [docs/deployment/manifest-format.md](https://github.com/dotnet/docs-aspire/blob/014cd10158cf3ae29ebf3fb2d7da2da307159287/docs/deployment/manifest-format.md) | [.NET Aspire manifest format for deployment tool builders](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/manifest-format?branch=pr-en-us-330) |
=> Fixed run -> build in sample

docs/reference/aspire-faq.yml
Fixes #332 - Preview: [Frequently asked questions about .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/reference/aspire-faq?branch=pr-en-us-333)
=> Add FAQ from Aspire discussion

docs/reference/aspire-faq.yml
Adds a link to the Dapr sample to the FAQ page
=> adds dapr sample link to faq

.github/workflows/quest-bulk.yml, .github/workflows/quest.yml
Related to https://github.com/dotnet/docs-tools/pull/303
=> add org-level app keys

.github/workflows/snippets5000.yml
=> Fix up workflow/load

.github/workflows/snippets5000.yml, docs/database/snippets/tutorial/aspiresqlefcore/AspireSQLEFCore.AppHost/AspireSQLEFCore.AppHost.csproj, docs/database/snippets/tutorial/aspiresqlefcore/AspireSQLEFCore.AppHost/Program.cs, docs/database/snippets/tutorial/aspiresqlefcore/AspireSQLEFCore.ServiceDefaults/AspireSQLEFCore.ServiceDefaults.csproj, docs/database/snippets/tutorial/aspiresqlefcore/AspireSQLEFCore/AspireSQLEFCore.csproj, docs/fundamentals/snippets/components/AspireApp/AspireApp.AppHost/AspireApp.AppHost.csproj, docs/fundamentals/snippets/components/AspireApp/AspireApp.ServiceDefaults/AspireApp.ServiceDefaults.csproj, docs/fundamentals/snippets/components/AspireApp/WorkerService/WorkerService.csproj, docs/fundamentals/snippets/networking/Networking.AppHost/Networking.AppHost.csproj, docs/fundamentals/snippets/template/YourAppName/YourAppName.ServiceDefaults.csproj, docs/get-started/snippets/quickstart/AspireSample/AspireSample.AppHost/AspireSample.AppHost.csproj, docs/get-started/snippets/quickstart/AspireSample/AspireSample.ServiceDefaults/AspireSample.ServiceDefaults.csproj, docs/get-started/snippets/quickstart/AspireSample/AspireSample.Web/AspireSample.Web.csproj, docs/index.yml, docs/storage/snippets/tutorial/AspireStorage/AspireStorage.AppHost/AspireStorage.AppHost.csproj, docs/storage/snippets/tutorial/AspireStorage/AspireStorage.ServiceDefaults/AspireStorage.ServiceDefaults.csproj, docs/storage/snippets/tutorial/AspireStorage/AspireStorage.Worker/AspireStorage.Worker.csproj, docs/storage/snippets/tutorial/AspireStorage/AspireStorage/AspireStorage.csproj, docs/toc.yml
Upgrade bits and add What's new to top-level TOC
=> Upgrade bits and add What's new to top-level TOC

docs/fundamentals/networking-overview.md
Remove obsolete APIs, that were missed.
Fixes #393
---
|:--|:--|
| [docs/fundamentals/networking-overview.md](https://github.com/dotnet/docs-aspire/blob/d20e11ffef366542ed1ad520943bb9ed59244f0b/docs/fundamentals/networking-overview.md) | [.NET Aspire inner-loop networking overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/networking-overview?branch=pr-en-us-394) |
=> Remove obsolete APIs, that were missed.

docs/fundamentals/app-host-overview.md
Fixes #347 
---
|:--|:--|
| [docs/fundamentals/app-host-overview.md](https://github.com/dotnet/docs-aspire/blob/398e933e67ae7888dbde68b4237f393b2c2f856c/docs/fundamentals/app-host-overview.md) | [.NET Aspire orchestration overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/app-host-overview?branch=pr-en-us-405) |
=> Added clarification and links to related content

docs/fundamentals/setup-tooling.md
Fixes #411
---
|:--|:--|
| [docs/fundamentals/setup-tooling.md](https://github.com/dotnet/docs-aspire/blob/af8315a7cf4ddce77ae70f84c96ca1e2066dd7ce/docs/fundamentals/setup-tooling.md) | [.NET Aspire setup and tooling](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/setup-tooling?branch=pr-en-us-412) |
=> Update the results from running dotnet new list aspire

docs/storage/azure-storage-components.md, docs/zones/zone-pivot-groups.yml
---
|:--|:--|
| [docs/storage/azure-storage-components.md](https://github.com/dotnet/docs-aspire/blob/6c3ac032c206d8e5ce745e4aef50c0437a6a0bfd/docs/storage/azure-storage-components.md) | [Tutorial: Connect an ASP.NET Core app to .NET Aspire storage components](https://review.learn.microsoft.com/en-us/dotnet/aspire/storage/azure-storage-components?branch=pr-en-us-414) |
=> Update storage tutorial with an azd flow and template

docs/deployment/overview.md
Fixes #429
---
|:--|:--|
| [docs/deployment/overview.md](https://github.com/dotnet/docs-aspire/blob/4c967c7be125b36ee279c1840a6489f657c4350d/docs/deployment/overview.md) | [.NET Aspire deployments](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/overview?branch=pr-en-us-433) |
=> Remove reference to preview 1

docs/database/oracle-entity-framework-component.md, docs/toc.yml
Add new `Aspire.Oracle.EntityFrameworkCore` component.
Fixes #370
---
|:--|:--|
| [docs/database/oracle-entity-framework-component.md](https://github.com/dotnet/docs-aspire/blob/3fabfcd991a58528cb949c891bdb69db48f71cd4/docs/database/oracle-entity-framework-component.md) | [.NET Aspire Oracle Entity Framework Component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/oracle-entity-framework-component?branch=pr-en-us-438) |
=> Add new `Aspire.Oracle.EntityFrameworkCore` component.

docs/database/snippets/tutorial/aspiresqlefcore/AspireSQLEFCore.AppHost/AspireSQLEFCore.AppHost.csproj, docs/database/snippets/tutorial/aspiresqlefcore/AspireSQLEFCore.AppHost/Program.cs, docs/database/snippets/tutorial/aspiresqlefcore/AspireSQLEFCore.ServiceDefaults/AspireSQLEFCore.ServiceDefaults.csproj, docs/database/snippets/tutorial/aspiresqlefcore/AspireSQLEFCore.ServiceDefaults/Extensions.cs, docs/database/snippets/tutorial/aspiresqlefcore/AspireSQLEFCore.sln, docs/database/snippets/tutorial/aspiresqlefcore/AspireSQLEFCore/AspireSQLEFCore.csproj, docs/fundamentals/snippets/components/AspireApp/AspireApp.AppHost/AspireApp.AppHost.csproj, docs/fundamentals/snippets/components/AspireApp/AspireApp.ServiceDefaults/AspireApp.ServiceDefaults.csproj, docs/fundamentals/snippets/components/AspireApp/AspireApp.ServiceDefaults/Extensions.cs, docs/fundamentals/snippets/components/AspireApp/WorkerService/WorkerService.csproj, docs/fundamentals/snippets/networking/Networking.AppHost/Networking.AppHost.csproj, docs/fundamentals/snippets/networking/networking.sln, docs/fundamentals/snippets/template/YourAppName/YourAppName.ServiceDefaults.csproj, docs/get-started/snippets/quickstart/AspireSample/AspireSample.AppHost/AspireSample.AppHost.csproj, docs/get-started/snippets/quickstart/AspireSample/AspireSample.ServiceDefaults/AspireSample.ServiceDefaults.csproj, docs/get-started/snippets/quickstart/AspireSample/AspireSample.ServiceDefaults/Extensions.cs, docs/get-started/snippets/quickstart/AspireSample/AspireSample.Web/AspireSample.Web.csproj, docs/real-time/snippets/signalr/SignalR.AppHost/SignalR.AppHost.csproj, docs/real-time/snippets/signalr/SignalR.ServiceDefaults/Extensions.cs, docs/real-time/snippets/signalr/SignalR.ServiceDefaults/SignalR.ServiceDefaults.csproj, docs/storage/snippets/tutorial/AspireStorage/AspireStorage.AppHost/AspireStorage.AppHost.csproj, docs/storage/snippets/tutorial/AspireStorage/AspireStorage.ServiceDefaults/AspireStorage.ServiceDefaults.csproj, docs/storage/snippets/tutorial/AspireStorage/AspireStorage.ServiceDefaults/Extensions.cs, docs/storage/snippets/tutorial/AspireStorage/AspireStorage.Worker/AspireStorage.Worker.csproj, docs/storage/snippets/tutorial/AspireStorage/AspireStorage/AspireStorage.csproj, docs/whats-new/index.yml
Upgrade to `8.0.0 preview.4.24129.7`.
Fixes #459
=> Upgrade to `8.0.0 preview.4.24129.7`

docs/whats-new/preview-4.md
Added known issues for Aspire Preview 4
Updated version of Aspire Preview 4 and VS 17.10 Preview to the correct versions. 
---
|:--|:--|
| [docs/whats-new/preview-4.md](https://github.com/dotnet/docs-aspire/blob/d7a4b3424e266c958f93abe6d761e9e6ffc8702a/docs/whats-new/preview-4.md) | [.NET Aspire preview 4](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/preview-4?branch=pr-en-us-481) |
=> Added known issues for Aspire preview 4, fixed some minor typos

docs/azureai/azureai-openai-component.md, docs/azureai/azureai-search-document-component.md, docs/database/azure-cosmos-db-component.md, docs/messaging/azure-service-bus-component.md, docs/security/azure-security-key-vault-component.md, docs/storage/snippets/tutorial/AspireStorage/AspireStorage.AppHost/Program.cs
Related to https://github.com/dotnet/aspire/issues/2395
---
|:--|:--|
| [docs/azureai/azureai-openai-component.md](https://github.com/dotnet/docs-aspire/blob/52d3976972cfd6e144666c34e7dc364777dd9813/docs/azureai/azureai-openai-component.md) | [.NET Aspire Azure AI OpenAI component](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-openai-component?branch=pr-en-us-485) |
| [docs/azureai/azureai-search-document-component.md](https://github.com/dotnet/docs-aspire/blob/52d3976972cfd6e144666c34e7dc364777dd9813/docs/azureai/azureai-search-document-component.md) | [NET Aspire Azure AI Search Documents component](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-search-document-component?branch=pr-en-us-485) |
| …
=> Updates for publish mode

docs/whats-new/preview-4.md
Removed dublicate description of _database managment tools_
---
|:--|:--|
| [docs/whats-new/preview-4.md](https://github.com/dotnet/docs-aspire/blob/60a747404e6656b24b8c2cac41a300d34dcbecbe/docs/whats-new/preview-4.md) | [.NET Aspire preview 4](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/preview-4?branch=pr-en-us-519) |
=> Removed dublicate description

docs/fundamentals/setup-tooling.md
Add details about container runtime.
Fixes #537
---
|:--|:--|
| [docs/fundamentals/setup-tooling.md](https://github.com/dotnet/docs-aspire/blob/fc3e01c00416bfa16689f254bb4a0a35e153ca10/docs/fundamentals/setup-tooling.md) | [.NET Aspire setup and tooling](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/setup-tooling?branch=pr-en-us-544) |
=> Add details about container runtime

docs/messaging/messaging-components.md
---
|:--|:--|
| [docs/messaging/messaging-components.md](https://github.com/dotnet/docs-aspire/blob/7c831679954af99d62097f14fc559f8ea8fa76a3/docs/messaging/messaging-components.md) | [Tutorial: Use .NET Aspire messaging components in ASP.NET Core](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/messaging-components?branch=pr-en-us-547) |
=> Add cli path to manage app

docs/storage/azure-storage-components.md
---
|:--|:--|
| [docs/storage/azure-storage-components.md](https://github.com/dotnet/docs-aspire/blob/cced4587fe1df52173c48e3aec7449191a459d51/docs/storage/azure-storage-components.md) | [Tutorial: Connect an ASP.NET Core app to .NET Aspire storage components](https://review.learn.microsoft.com/en-us/dotnet/aspire/storage/azure-storage-components?branch=pr-en-us-553) |
=> Added CLI path to storage

docs/index.yml, docs/toc.yml, docs/whats-new/index.yml, docs/whats-new/preview-5.md, docs/whats-new/toc.yml
Add placeholder for preview-5 what's new content.
---
|:--|:--|
| [docs/whats-new/preview-5.md](https://github.com/dotnet/docs-aspire/blob/1bfd96a0391e230684a0d9abab328e6e8fb8184a/docs/whats-new/preview-5.md) | [.NET Aspire preview 5](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/preview-5?branch=pr-en-us-558) |
=> Add placeholder for preview-5 what's new content.

docs/fundamentals/service-defaults.md
Added a section about custom service defaults.
Fixes #549
---
|:--|:--|
| [docs/fundamentals/service-defaults.md](https://github.com/dotnet/docs-aspire/blob/fbe44aece1340684a316907ab6a69d6cba54b3a9/docs/fundamentals/service-defaults.md) | [.NET Aspire service defaults](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/service-defaults?branch=pr-en-us-560) |
=> Added a section about custom service defaults

docs/deployment/azure/aca-deployment-github-actions.md
* Typo "Create a Azure DevOps"→"Create an Azure DevOps"
* https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-github-actions?tabs=macos%2Cvisual-studio&pivots=azure-pipelines 
* https://github.com/dotnet/docs-aspire/blob/main/docs/deployment/azure/aca-deployment-github-actions.md 
* #PingMSFTDocs
---
|:--|:--|
| [docs/deployment/azure/aca-deployment-github-actions.md](https://github.com/dotnet/docs-aspire/blob/ed5b6adc2fd433f33c2994315b7c994c50aab693/docs/deployment/azure/aca-deployment-github-actions.md) | [Tutorial: Deploy a .NET Aspire app using the Azure Developer CLI and GitHub Actions](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deploy …
=> Typo "Create a Azure DevOps"→"Create an Azure DevOps"

docs/database/snippets/tutorial/aspiresqlefcore/AspireSQLEFCore.ServiceDefaults/AspireSQLEFCore.ServiceDefaults.csproj, docs/database/snippets/tutorial/aspiresqlefcore/AspireSQLEFCore.ServiceDefaults/Extensions.cs, docs/fundamentals/service-defaults.md, docs/fundamentals/snippets/components/AspireApp/AspireApp.ServiceDefaults/AspireApp.ServiceDefaults.csproj, docs/fundamentals/snippets/components/AspireApp/AspireApp.ServiceDefaults/Extensions.cs, docs/fundamentals/snippets/healthz/Healthz.ServiceDefaults/Healthz.ServiceDefaults.csproj, docs/fundamentals/snippets/networking/Networking.ServiceDefaults/Extensions.cs, docs/fundamentals/snippets/networking/Networking.ServiceDefaults/Networking.ServiceDefaults.csproj, docs/fundamentals/snippets/params/Parameters.ServiceDefaults/Extensions.cs, docs/fundamentals/snippets/params/Parameters.ServiceDefaults/Parameters.ServiceDefaults.csproj, docs/fundamentals/snippets/template/YourAppName/Extensions.cs, docs/fundamentals/snippets/template/YourAppName/YourAppName.ServiceDefaults.csproj, docs/get-started/snippets/quickstart/AspireSample/AspireSample.ServiceDefaults/AspireSample.ServiceDefaults.csproj, docs/get-started/snippets/quickstart/AspireSample/AspireSample.ServiceDefaults/Extensions.cs, docs/real-time/snippets/signalr/SignalR.ServiceDefaults/Extensions.cs, docs/real-time/snippets/signalr/SignalR.ServiceDefaults/SignalR.ServiceDefaults.csproj, docs/storage/snippets/tutorial/AspireStorage/AspireStorage.ServiceDefaults/AspireStorage.ServiceDefaults.csproj, docs/storage/snippets/tutorial/AspireStorage/AspireStorage.ServiceDefaults/Extensions.cs
Try sync with source.
Fixes #568
---
|:--|:--|
| [docs/fundamentals/service-defaults.md](https://github.com/dotnet/docs-aspire/blob/56fa5ddc2024f5d6f6fa013d40eb1c2262b46344/docs/fundamentals/service-defaults.md) | [.NET Aspire service defaults](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/service-defaults?branch=pr-en-us-570) |
=> Try sync with source

.github/workflows/markdownlint.yml
Upgrade node-version.
Contributes to #566
=> Upgrade node-version

docs/deployment/overview.md, docs/get-started/snippets/quickstart/AspireSample/AspireSample.ServiceDefaults/Extensions.cs
Deployment scenarios with k8s.
Fixes #546
---
|:--|:--|
| [docs/deployment/overview.md](https://github.com/dotnet/docs-aspire/blob/d2840d57fad451d912e168a044d2df45f64594f3/docs/deployment/overview.md) | [.NET Aspire deployments](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/overview?branch=pr-en-us-583) |
=> Deployment scenarios with k8s

docs/logging/seq-component.md
Fixes #484
---
|:--|:--|
| [docs/logging/seq-component.md](https://github.com/dotnet/docs-aspire/blob/f3612cd9d78e2ee2a1d9aa904d974eb01bbed16b/docs/logging/seq-component.md) | [.NET Aspire Seq component](https://review.learn.microsoft.com/en-us/dotnet/aspire/logging/seq-component?branch=pr-en-us-584) |
=> Add seq component

docs/get-started/add-aspire-existing-app.md
---
|:--|:--|
| [docs/get-started/add-aspire-existing-app.md](https://github.com/dotnet/docs-aspire/blob/4a57cdbf13944d242c3548dfff1cb1bf2b87e399/docs/get-started/add-aspire-existing-app.md) | [Tutorial: Add .NET Aspire to an existing .NET 8 microservices app](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/add-aspire-existing-app?branch=pr-en-us-591) |
=> Add info about service discovery when added existing app

.openpublishing.redirection.json
=> This should work

docs/whats-new/preview-5.md
Fixes #601
---
|:--|:--|
| [docs/whats-new/preview-5.md](https://github.com/dotnet/docs-aspire/blob/0d803bff2ce008570dfbd1d6a3868d8bf5f1227b/docs/whats-new/preview-5.md) | [.NET Aspire preview 5](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/preview-5?branch=pr-en-us-640) |
=> Upgrade path

docs/service-discovery/overview.md
Related to https://github.com/dotnet/docs/issues/40433
---
|:--|:--|
| [docs/service-discovery/overview.md](https://github.com/dotnet/docs-aspire/blob/65d3add01e8b4802477c7dc444bf04e249bf6626/docs/service-discovery/overview.md) | [.NET Aspire service discovery](https://review.learn.microsoft.com/en-us/dotnet/aspire/service-discovery/overview?branch=pr-en-us-641) |
=> Let's get this fixed too

docs/whats-new/preview-5.md
Add known issues section. Fixes #644
---
|:--|:--|
| [docs/whats-new/preview-5.md](https://github.com/dotnet/docs-aspire/blob/1f39c45b01bc44cb2b41a00cdeb8f04bd42920b9/docs/whats-new/preview-5.md) | [.NET Aspire preview 5](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/preview-5?branch=pr-en-us-645) |
=> Add known issues section

docs/fundamentals/dashboard/overview.md
---
|:--|:--|
| [docs/fundamentals/dashboard/overview.md](https://github.com/dotnet/docs-aspire/blob/c2ce2313dffd6922830391076f4390fdad1bb66f/docs/fundamentals/dashboard/overview.md) | [.NET Aspire dashboard overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/overview?branch=pr-en-us-678) |
=> Add note that only OTLP/grpc is currently supported

docs/fundamentals/setup-tooling.md
Just a fix for a small typo.
---
|:--|:--|
| [docs/fundamentals/setup-tooling.md](https://github.com/dotnet/docs-aspire/blob/17971ea122a163018659a71743a6473c6b554512/docs/fundamentals/setup-tooling.md) | [.NET Aspire setup and tooling](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/setup-tooling?branch=pr-en-us-684) |
=> Update setup-tooling.md (typo)

docs/deployment/azure/local-provisioning.md, docs/whats-new/preview-5.md
Edit pass on paragraph.
Fixes #673
---
|:--|:--|
| [docs/whats-new/preview-5.md](https://github.com/dotnet/docs-aspire/blob/cf3d35d8e643cf2434675c04da85d0565ed1263f/docs/whats-new/preview-5.md) | [.NET Aspire preview 5](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/preview-5?branch=pr-en-us-683) |
=> Edit pass on paragraph

docs/azureai/azureai-openai-component.md, docs/azureai/azureai-search-document-component.md, docs/database/azure-cosmos-db-component.md, docs/database/azure-cosmos-db-entity-framework-component.md, docs/includes/azure-provisioning.md, docs/messaging/azure-event-hubs-component.md, docs/messaging/azure-service-bus-component.md, docs/real-time/azure-signalr-scenario.md, docs/real-time/snippets/signalr/SignalR.AppHost/Program.cs, docs/real-time/snippets/signalr/SignalR.AppHost/SignalR.AppHost.csproj, docs/security/azure-security-key-vault-component.md, docs/storage/azure-storage-blobs-component.md, docs/storage/azure-storage-queues-component.md, docs/storage/azure-storage-tables-component.md
Add details to all Azure resource-related content, with provisioning and credential source config.
Fixes #639
---
|:--|:--|
| [docs/azureai/azureai-openai-component.md](https://github.com/dotnet/docs-aspire/blob/7d2990495022881f5a090fae63511e3ceb372ed8/docs/azureai/azureai-openai-component.md) | [.NET Aspire Azure AI OpenAI component](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-openai-component?branch=pr-en-us-693) |
| [docs/azureai/azureai-search-document-component.md](https://github.com/dotnet/docs-aspire/blob/7d2990495022881f5a090fae63511e3ceb372ed8/docs/azureai/azureai-search-document-component.md) | [NET Aspire Azure AI Search Documents …
=> Content for configuring Azure credential source.

docs/whats-new/preview-5.md
Typo fix.
---
|:--|:--|
| [docs/whats-new/preview-5.md](https://github.com/dotnet/docs-aspire/blob/2fa531895956661e6215cc3943ba5aea32eb3b4d/docs/whats-new/preview-5.md) | [.NET Aspire preview 5](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/preview-5?branch=pr-en-us-694) |
=> Fix typo on Kafka

docs/messaging/messaging-components.md
Contributes to https://github.com/dotnet/docs/issues/39126
---
|:--|:--|
| [docs/messaging/messaging-components.md](https://github.com/dotnet/docs-aspire/blob/689d109f11dc15716a9b13a5b5952a5282dd7e92/docs/messaging/messaging-components.md) | [Tutorial: Use .NET Aspire messaging components in ASP.NET Core](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/messaging-components?branch=pr-en-us-706) |
=> Fix broken link

docs/fundamentals/dashboard/explore.md, docs/fundamentals/dashboard/security-considerations.md
Add a section for securing telemetry to security considerations. This will be linked to from the Aspire app for people who  want more information.
---
|:--|:--|
| [docs/fundamentals/dashboard/explore.md](https://github.com/dotnet/docs-aspire/blob/de5b7ccc00dad38c8141b0b23cd31babc0d92fd8/docs/fundamentals/dashboard/explore.md) | [Explore the .NET Aspire dashboard](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/explore?branch=pr-en-us-710) |
| [docs/fundamentals/dashboard/security-considerations.md](https://github.com/dotnet/docs-aspire/blob/de5b7ccc00dad38c8141b0b23cd31babc0d92fd8/docs/fundamentals/dashboard/security-considerations.md) | [.NET Aspire dashboard security considerations](https://review.learn.microsoft.com/en-us/dotnet/ …
=> Add section for securing telemetry

docs/whats-new/preview-6.md
Merge the update commands into a single block
---
|:--|:--|
| [docs/whats-new/preview-6.md](https://github.com/dotnet/docs-aspire/blob/7449c9898d1fe70be6ab98e26a70b3c9e258b336/docs/whats-new/preview-6.md) | [.NET Aspire preview 6](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/preview-6?branch=pr-en-us-714) |
=> preview-6 update commands

docs/azureai/azureai-openai-component.md, docs/database/azure-cosmos-db-component.md, docs/database/azure-cosmos-db-entity-framework-component.md, docs/fundamentals/networking-overview.md, docs/get-started/aspire-overview.md, docs/messaging/azure-service-bus-component.md, docs/messaging/messaging-components.md, docs/messaging/rabbitmq-client-component.md, docs/service-discovery/overview.md, docs/storage/azure-storage-blobs-component.md, docs/storage/azure-storage-components.md, docs/storage/azure-storage-queues-component.md, docs/storage/azure-storage-tables-component.md, docs/storage/snippets/tutorial/AspireStorage/AspireStorage.Worker/Program.cs, docs/storage/snippets/tutorial/AspireStorage/AspireStorage/Program.cs, docs/whats-new/preview-3.md
Fix invalidated xref's since API updates.
Fixes #742
---
|:--|:--|
| [docs/azureai/azureai-openai-component.md](https://github.com/dotnet/docs-aspire/blob/861d4a04a2e8190df5f2eaeed86263e1f883ed94/docs/azureai/azureai-openai-component.md) | [.NET Aspire Azure AI OpenAI component](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-openai-component?branch=pr-en-us-743) |
| [docs/database/azure-cosmos-db-component.md](https://github.com/dotnet/docs-aspire/blob/861d4a04a2e8190df5f2eaeed86263e1f883ed94/docs/database/azure-cosmos-db-component.md) | [.NET Aspire Azure Cosmos DB component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/azure-cosmos-db-component?b …
=> Fix invalidated xref's since API updates

docs/deployment/azure/aca-deployment-github-actions.md, docs/deployment/azure/includes/init-workflow.md, docs/includes/file-new-aspire.md
- [Fix requires Docker wording](https://github.com/dotnet/docs-aspire/commit/f0e40924656ad0fa8a1316e68fdebca2e6f53d9f)
- [Fix azd init bits](https://github.com/dotnet/docs-aspire/commit/03bdc202e79824916b7aaf66a5473561e25cd590)
- [Add details about azd pipeline config](https://github.com/dotnet/docs-aspire/commit/1f052450c5d57c03ef77709835855f94793295bd)
Fixes #747
---
|:--|:--|
| [docs/deployment/azure/aca-deployment-github-actions.md](https://github.com/dotnet/docs-aspire/blob/1f052450c5d57c03ef77709835855f94793295bd/docs/deployment/azure/aca-deployment-github-actions.md) | [Tutorial: Deploy a .NET Aspire app using the Azure Developer CLI and GitHub Actions](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-github-actions?b …
=> Address multiple issues

docs/caching/stackexchange-redis-distributed-caching-component.md
---
|:--|:--|
| [docs/caching/stackexchange-redis-distributed-caching-component.md](https://github.com/dotnet/docs-aspire/blob/b3fe37a5c88a64498d5a406ce0e9869936597770/docs/caching/stackexchange-redis-distributed-caching-component.md) | [.NET Aspire StackExchange Redis distributed caching component](https://review.learn.microsoft.com/en-us/dotnet/aspire/caching/stackexchange-redis-distributed-caching-component?branch=pr-en-us-764) |
=> Fix link md

docs/fundamentals/health-checks.md
Fixes #700
---
|:--|:--|
| [docs/fundamentals/health-checks.md](https://github.com/dotnet/docs-aspire/blob/fba189b968d2e734883dd9ca20d08a0f80ef3deb/docs/fundamentals/health-checks.md) | [Health checks in .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/health-checks?branch=pr-en-us-778) |
=> Update health-checks verbiage

docs/extensibility/custom-resources.md
---
|:--|:--|
| [docs/extensibility/custom-resources.md](https://github.com/dotnet/docs-aspire/blob/3479fe3c4e5390ad36386cf885734469f655892b/docs/extensibility/custom-resources.md) | [Create custom resource types for .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/extensibility/custom-resources?branch=pr-en-us-782) |
=> Another fix

.github/actions/azure-oidc-auth.yml, .github/workflows/quest-bulk.yml, .github/workflows/quest.yml, .github/workflows/whats-new-automation.yml
Added Azure OIDC auth.
Contributes to #566
=> Added Azure OIDC auth

.github/actions/azure-oidc-auth/action.yml, .github/workflows/quest-bulk.yml, .github/workflows/quest.yml, .github/workflows/whats-new-automation.yml
=> Oops, input over secret

docs/fundamentals/dashboard/standalone.md
---
|:--|:--|
| [docs/fundamentals/dashboard/standalone.md](https://github.com/dotnet/docs-aspire/blob/2f4af7a94769e6a978f54d960b1cb2ef0d35f463/docs/fundamentals/dashboard/standalone.md) | [Standalone .NET Aspire dashboard](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/standalone?branch=pr-en-us-796) |
=> Add docs about dashboard in-memory telemetry limitations

.github/workflows/quest-bulk.yml
Added duration input option, defaults to "5".
=> Added duration option

.github/workflows/quest-bulk.yml
Search "ternary" here... the syntax is a bit weird. https://docs.github.com/en/actions/learn-github-actions/expressions
=> Use a TS ternary

docs/fundamentals/dashboard/explore.md
Explains what the advanced filter dialog is
Fixes #812
---
|:--|:--|
| [docs/fundamentals/dashboard/explore.md](https://github.com/dotnet/docs-aspire/blob/f1b5a09683bef1ec365a0822ebf83563bcf8570b/docs/fundamentals/dashboard/explore.md) | [Explore the .NET Aspire dashboard](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/explore?branch=pr-en-us-819) |
=> Modify blurb about advanced filter dialog

docs/fundamentals/persist-data-volumes.md
Fixes #831
---
|:--|:--|
| [docs/fundamentals/persist-data-volumes.md](https://github.com/dotnet/docs-aspire/blob/8c0a8986e22318bb099eaf22a0e23de71f720bc6/docs/fundamentals/persist-data-volumes.md) | [Persist .NET Aspire app data using volumes](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/persist-data-volumes?branch=pr-en-us-832) |
=> Fix PostgreSQL typo in persist-data-volumes.md

docs/deployment/overview.md
---
|:--|:--|
| [docs/deployment/overview.md](https://github.com/dotnet/docs-aspire/blob/4ee0d6e092b05f4bd76ebcbcd78d84e1743df44c/docs/deployment/overview.md) | [.NET Aspire deployments](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/overview?branch=pr-en-us-828) |
=> Minor casing fix

docs/real-time/azure-signalr-scenario.md
---
|:--|:--|
| [docs/real-time/azure-signalr-scenario.md](https://github.com/dotnet/docs-aspire/blob/f4adbb51566b66969fdd584fc089feeb66a2ee65/docs/real-time/azure-signalr-scenario.md) | [.NET Aspire support for Azure SignalR Service](https://review.learn.microsoft.com/en-us/dotnet/aspire/real-time/azure-signalr-scenario?branch=pr-en-us-829) |
=> Minor grammatical edits to Azure SignalR scenario

docs/deployment/overview.md
---
|:--|:--|
| [docs/deployment/overview.md](https://github.com/dotnet/docs-aspire/blob/29093c7cd8432670220f764f72cc3f268f23a222/docs/deployment/overview.md) | [.NET Aspire deployments](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/overview?branch=pr-en-us-839) |
=> Edit pass on deployment doc

docs/database/azure-cosmos-db-component.md, docs/database/azure-cosmos-db-entity-framework-component.md, docs/database/mongodb-component.md, docs/database/mysql-component.md, docs/database/mysql-entity-framework-component.md, docs/database/oracle-entity-framework-component.md, docs/database/postgresql-component.md, docs/database/postgresql-entity-framework-component.md, docs/database/sql-server-component.md, docs/database/sql-server-entity-framework-component.md
---
|:--|:--|
| [docs/database/azure-cosmos-db-component.md](https://github.com/dotnet/docs-aspire/blob/b9f36f2c83d44210f57e99945cfaed884544bf1e/docs/database/azure-cosmos-db-component.md) | [.NET Aspire Azure Cosmos DB component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/azure-cosmos-db-component?branch=pr-en-us-843) |
| [docs/database/azure-cosmos-db-entity-framework-component.md](https://github.com/dotnet/docs-aspire/blob/b9f36f2c83d44210f57e99945cfaed884544bf1e/docs/database/azure-cosmos-db-entity-framework-component.md) | [.NET Aspire Microsoft Entity Framework Core Cosmos DB component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/azure-cosmos-db-entity-f …
=> Update Database Clarity

docs/toc.yml
Adding a few links under troubleshooting. Related to #845
Internal Preview: https://review.learn.microsoft.com/dotnet/aspire/troubleshooting/allow-unsecure-transport?branch=pr-en-us-856
=> Added a few links under troubleshooting

docs/toc.yml
=> New TOC node

docs/deployment/azure/aca-deployment-github-actions.md
Tested this deployment with Azure pipelines.
Fixes #541
---
|:--|:--|
| [docs/deployment/azure/aca-deployment-github-actions.md](https://github.com/dotnet/docs-aspire/blob/41b15f117d77c5f90c1e52c2c03b05541082a2e4/docs/deployment/azure/aca-deployment-github-actions.md) | [Tutorial: Deploy a .NET Aspire app using the Azure Developer CLI and GitHub Actions](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-github-actions?branch=pr-en-us-901) |
=> fix deployment yaml

docs/toc.yml
TOC -> POC
[Preview Link](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/components-overview?branch=pr-en-us-932&tabs=dotnet-cli)
=> Let's try a few updates for the TOC

docs/toc.yml
Shift a few things here. [Live preview](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/overview?branch=pr-en-us-945).
**After**
=> Lift Deployment and split Azure

docs/messaging/azure-service-bus-component.md
Correct Service Bus tracing details.
Fixes #974
---
|:--|:--|
| [docs/messaging/azure-service-bus-component.md](https://github.com/dotnet/docs-aspire/blob/c6c87d8788a52a67a95db49cf523652d237a2011/docs/messaging/azure-service-bus-component.md) | [.NET Aspire Azure Service Bus component](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/azure-service-bus-component?branch=pr-en-us-1017) |
=> Correct Service Bus tracing details.

docs/fundamentals/dashboard/explore.md, docs/fundamentals/dashboard/security-considerations.md
Update cookie auth details.
Fixes #716
---
|:--|:--|
| [docs/fundamentals/dashboard/explore.md](https://github.com/dotnet/docs-aspire/blob/6105c2fe41cee9628f6937afa72d2a085ca5af13/docs/fundamentals/dashboard/explore.md) | [Explore the .NET Aspire dashboard](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/explore?branch=pr-en-us-1022) |
| [docs/fundamentals/dashboard/security-considerations.md](https://github.com/dotnet/docs-aspire/blob/6105c2fe41cee9628f6937afa72d2a085ca5af13/docs/fundamentals/dashboard/security-considerations.md) | [.NET Aspire dashboard security considerations](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/security-considerations?branch=pr-en-us-1022) |
=> Update cookie auth details.

docs/get-started/add-aspire-existing-app.md
Add external HTTP, and update content.
Fixes #1029
---
|:--|:--|
| [docs/get-started/add-aspire-existing-app.md](https://github.com/dotnet/docs-aspire/blob/cd7e67b9af0bf9391e11568c0354caeea9320d88/docs/get-started/add-aspire-existing-app.md) | [Tutorial: Add .NET Aspire to an existing .NET app](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/add-aspire-existing-app?branch=pr-en-us-1031) |
=> Add external HTTP and update corresponding content. 

docs/azureai/azureai-openai-component.md, docs/azureai/azureai-search-document-component.md, docs/caching/stackexchange-redis-component.md, docs/caching/stackexchange-redis-distributed-caching-component.md, docs/caching/stackexchange-redis-output-caching-component.md, docs/database/azure-cosmos-db-component.md, docs/database/azure-cosmos-db-entity-framework-component.md, docs/database/includes/postgresql-flexible-server.md, docs/database/mongodb-component.md, docs/database/mysql-component.md, docs/database/mysql-entity-framework-component.md, docs/database/oracle-entity-framework-component.md, docs/database/postgresql-component.md, docs/database/postgresql-entity-framework-component.md, docs/database/qdrant-component.md, docs/database/sql-server-component.md, docs/database/sql-server-entity-framework-component.md, docs/fundamentals/app-host-overview.md, docs/logging/seq-component.md, docs/messaging/azure-event-hubs-component.md, docs/messaging/azure-service-bus-component.md, docs/messaging/kafka-component.md, docs/messaging/nats-component.md, docs/messaging/rabbitmq-client-component.md, docs/security/azure-security-key-vault-component.md, docs/storage/azure-storage-blobs-component.md, docs/storage/azure-storage-queues-component.md, docs/storage/azure-storage-tables-component.md
Ok, I got a little carried away, but these were missing.
Fixes #428
---
|:--|:--|
| [docs/azureai/azureai-openai-component.md](https://github.com/dotnet/docs-aspire/blob/ae2de99bae62d0e6eaa032cd97b8589951adc594/docs/azureai/azureai-openai-component.md) | [.NET Aspire Azure AI OpenAI component](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-openai-component?branch=pr-en-us-1046) |
| [docs/azureai/azureai-search-document-component.md](https://github.com/dotnet/docs-aspire/blob/ae2de99bae62d0e6eaa032cd97b8589951adc594/docs/azureai/azureai-search-document-component.md) | [.NET Aspire Azure AI Search Documents component](https://review.learn.microsoft.com/en-us/dotnet/asp …
=> Add missing code, and add flexible PostgreSQL

docs/deployment/azure/aca-deployment-azd-in-depth.md, docs/deployment/azure/includes/init-workflow.md
---
|:--|:--|
| [docs/deployment/azure/aca-deployment-azd-in-depth.md](https://github.com/dotnet/docs-aspire/blob/360d9c7559966164a6c70f986ed89acf881f4182/docs/deployment/azure/aca-deployment-azd-in-depth.md) | [Deploy a .NET Aspire app to Azure Container Apps using the Azure Developer CLI (in-depth guide)](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-azd-in-depth?branch=pr-en-us-1052) |
=> remove out of date docs

docs/azureai/azureai-openai-component.md, docs/messaging/rabbitmq-client-component.md, docs/whats-new/preview-7.md
Fix #1054
---
|:--|:--|
| [docs/azureai/azureai-openai-component.md](https://github.com/dotnet/docs-aspire/blob/4356f1487a4b98a3395c87d38f361c685ff24f31/docs/azureai/azureai-openai-component.md) | [.NET Aspire Azure AI OpenAI component](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-openai-component?branch=pr-en-us-1057) |
| [docs/messaging/rabbitmq-client-component.md](https://github.com/dotnet/docs-aspire/blob/4356f1487a4b98a3395c87d38f361c685ff24f31/docs/messaging/rabbitmq-client-component.md) | [.NET Aspire RabbitMQ component](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/rabbitmq-client-component?branch=pr-en-us-1057) |
| [docs/whats-new/preview-7.md](https://github.com/dotnet/docs-aspire/blob/4356f1487a4b98a3395c8 …
=> Fix RabbitMQ docs usage of AddRabbitMQ for connection string based connection

docs/toc.yml
Move networking under the App Host TOC.
=> Move networking to App Host

docs/azureai/azureai-search-document-component.md
Fix incorrect API and add xrefs. 
Fixes #1050
---
|:--|:--|
| [docs/azureai/azureai-search-document-component.md](https://github.com/dotnet/docs-aspire/blob/750a1e5a9b6ae1cc4417d87ab461ade0019797d4/docs/azureai/azureai-search-document-component.md) | [.NET Aspire Azure AI Search Documents component](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-search-document-component?branch=pr-en-us-1090) |
=> Fix incorrect API and add xrefs.

docs/reference/aspire-faq.yml
=> update GA on aspire :)

docs/toc.yml
it is the title of the doc so I think would be good
=> Update toc.yml - existing .NET Apps

docs/get-started/build-aspire-apps-with-nodejs.md, docs/toc.yml
---
|:--|:--|
| [docs/get-started/build-aspire-apps-with-nodejs.md](https://github.com/dotnet/docs-aspire/blob/62fc86515f65acfd027a5b2cd0d5589ea8a29f44/docs/get-started/build-aspire-apps-with-nodejs.md) | [Build .NET Aspire apps with Node.js](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/build-aspire-apps-with-nodejs?branch=pr-en-us-1100) |
=> Update toc.yml - node.js app

docs/get-started/build-your-first-aspire-app.md, docs/toc.yml
---
|:--|:--|
| [docs/get-started/build-your-first-aspire-app.md](https://github.com/dotnet/docs-aspire/blob/d10dcb0b2bedd57f577d8b48db1ffc97a077b921/docs/get-started/build-your-first-aspire-app.md) | [Quickstart: Build your first .NET Aspire project](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/build-your-first-aspire-app?branch=pr-en-us-1101) |
=> Update build-your-first-aspire-app.md - app -> project

docs/real-time/azure-signalr-scenario.md, docs/real-time/snippets/signalr/SignalR.ApiService/Properties/launchSettings.json, docs/real-time/snippets/signalr/SignalR.AppHost/Properties/launchSettings.json, docs/real-time/snippets/signalr/SignalR.AppHost/SignalR.AppHost.csproj, docs/real-time/snippets/signalr/SignalR.ServiceDefaults/Extensions.cs, docs/real-time/snippets/signalr/SignalR.ServiceDefaults/SignalR.ServiceDefaults.csproj, docs/real-time/snippets/signalr/SignalR.Shared/SignalR.Shared.csproj, docs/real-time/snippets/signalr/SignalR.Web/Components/Pages/Home.razor.cs, docs/real-time/snippets/signalr/SignalR.Web/Extensions/ConfigurationExtensions.cs, docs/real-time/snippets/signalr/SignalR.Web/Properties/launchSettings.json, docs/real-time/snippets/signalr/SignalR.Web/SignalR.Web.csproj, docs/real-time/snippets/signalr/signalr.sln, docs/toc.yml
Move SignalR and Custom Bicep articles.
Fixes #1092
---
|:--|:--|
| [docs/real-time/azure-signalr-scenario.md](https://github.com/dotnet/docs-aspire/blob/52101c30c9a1e9c3fb9e1c7e7125ea051fa5dc99/docs/real-time/azure-signalr-scenario.md) | [.NET Aspire support for Azure SignalR Service](https://review.learn.microsoft.com/en-us/dotnet/aspire/real-time/azure-signalr-scenario?branch=pr-en-us-1093) |
=> Move SignalR and Custom Bicep articles

docs/deployment/azure/aca-deployment-azd-in-depth.md, docs/deployment/azure/aca-deployment-github-actions.md, docs/deployment/azure/aca-deployment-visual-studio.md, docs/deployment/azure/aca-deployment.md, docs/includes/azure-container-app-naming.md
Add an include about resource naming.
Fixes #1094
---
|:--|:--|
| [docs/deployment/azure/aca-deployment-azd-in-depth.md](https://github.com/dotnet/docs-aspire/blob/37c0923653cb20fed814770fb8731e80796985ee/docs/deployment/azure/aca-deployment-azd-in-depth.md) | [Deploy a .NET Aspire project to Azure Container Apps using the Azure Developer CLI (in-depth guide)](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-azd-in-depth?branch=pr-en-us-1104) |
| [docs/deployment/azure/aca-deployment-github-actions.md](https://github.com/dotnet/docs-aspire/blob/37c0923653cb20fed814770fb8731e80796985ee/docs/deployment/azure/aca-deployment-github-actions.md) | [[Windows](#tab/windows)](https://review.learn.microsoft.com/en-us/dotnet/aspire/dep …
=> Add an include about resource naming.

docs/database/snippets/tutorial/aspiresqlefcore/AspireSQLEFCore/AspireSQLEFCore.csproj, docs/database/sql-server-components.md
Fix code and content. 
Fixes #723
---
|:--|:--|
| [docs/database/sql-server-components.md](https://github.com/dotnet/docs-aspire/blob/aa78da61392d2b6a14a91858cfabbf8645e43c59/docs/database/sql-server-components.md) | [Tutorial: Connect an ASP.NET Core app to SQL Server using .NET Aspire and Entity Framework Core](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/sql-server-components?branch=pr-en-us-1158) |
=> Fix code and content.

docs/azureai/azureai-search-document-component.md
Fix incorrect NuGet hosting package.
Fixes #1111
---
|:--|:--|
| [docs/azureai/azureai-search-document-component.md](https://github.com/dotnet/docs-aspire/blob/01d694686dea5ea830d6d63e58a0aa1d4820aad5/docs/azureai/azureai-search-document-component.md) | [.NET Aspire Azure AI Search Documents component](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-search-document-component?branch=pr-en-us-1155) |
=> Fix incorrect NuGet hosting package.

.github/policies/label-prs.yml
Describe your changes here. Related to https://github.com/dotnet/docs-aspire/issues/1156
=> Auto merge

docs/azureai/azureai-openai-component.md
Add a bit more context about connection string formats. Fixes #1065
---
|:--|:--|
| [docs/azureai/azureai-openai-component.md](https://github.com/dotnet/docs-aspire/blob/aae8fe961fb586cd938ed08b109ad80fd5f78c4c/docs/azureai/azureai-openai-component.md) | [.NET Aspire Azure AI OpenAI component](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-openai-component?branch=pr-en-us-1161) |
=> Add a bit more context

docs/reference/aspire-faq.yml
Remove references to previews and ensure content is up-to-date.
Fixes #1166
=> Remove references to previews and ensure content is up-to-date

.github/policies/label-prs.yml
Added another variation of the policy
=> Added another variation of the policy

.github/policies/auto-merge.yml, .github/policies/label-prs.yml
Related to https://github.com/dotnet/docs/issues/41522
=> Follow dotnet/docs

docfx.json
Added `ms.collection` tags for AI.
Fixes #1348
=> Added `ms.collection` tags

.github/workflows/markdownlint.yml
Use a non-pinned version. Fixes #1350
=> Use a non-pinned version.

docs/database/sql-server-entity-framework-component.md
Remove duplicate log category
---
|:--|:--|
| [docs/database/sql-server-entity-framework-component.md](https://github.com/dotnet/docs-aspire/blob/4c4100d4cbfd60670fa389ae7d7b650bbcd63fc2/docs/database/sql-server-entity-framework-component.md) | [docs/database/sql-server-entity-framework-component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/sql-server-entity-framework-component?branch=pr-en-us-1352) |
=> Remove duplicate log category

docs/azureai/azureai-openai-component.md, docs/azureai/azureai-search-document-component.md, docs/caching/includes/redis-app-host.md, docs/caching/stackexchange-redis-component.md, docs/caching/stackexchange-redis-distributed-caching-component.md, docs/caching/stackexchange-redis-output-caching-component.md, docs/database/azure-cosmos-db-component.md, docs/database/azure-cosmos-db-entity-framework-component.md, docs/database/includes/mysql-app-host.md, docs/database/includes/postgresql-app-host.md, docs/database/includes/sql-app-host.md, docs/database/mongodb-component.md, docs/database/mysql-entity-framework-component.md, docs/database/oracle-entity-framework-component.md, docs/database/postgresql-component.md, docs/database/postgresql-entity-framework-component.md, docs/database/qdrant-component.md, docs/database/sql-server-component.md, docs/database/sql-server-entity-framework-component.md, docs/fundamentals/app-host-overview.md, docs/logging/seq-component.md, docs/messaging/azure-event-hubs-component.md, docs/messaging/azure-service-bus-component.md, docs/messaging/kafka-component.md, docs/messaging/nats-component.md, docs/messaging/rabbitmq-client-component.md, docs/security/azure-security-key-vault-component.md, docs/storage/azure-storage-blobs-component.md, docs/storage/azure-storage-queues-component.md, docs/storage/azure-storage-tables-component.md
Explicitly define each target project install for NuGet.
Fixes #1375
---
|:--|:--|
| [docs/azureai/azureai-openai-component.md](https://github.com/dotnet/docs-aspire/blob/17ef370fb4c5920e0d6e10633439d5824b2c4df9/docs/azureai/azureai-openai-component.md) | [docs/azureai/azureai-openai-component](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-openai-component?branch=pr-en-us-1376) |
| [docs/azureai/azureai-search-document-component.md](https://github.com/dotnet/docs-aspire/blob/17ef370fb4c5920e0d6e10633439d5824b2c4df9/docs/azureai/azureai-search-document-component.md) | [docs/azureai/azureai-search-document-component](https://review.learn.microsoft.com/en-us/dotnet/asp …
=> Explicitly define each target project install for NuGet

docs/deployment/azure/aca-deployment-azd-in-depth.md
---
|:--|:--|
| [docs/deployment/azure/aca-deployment-azd-in-depth.md](https://github.com/dotnet/docs-aspire/blob/054e3d9b5c17238d264bba70aad76ed4f339d6b6/docs/deployment/azure/aca-deployment-azd-in-depth.md) | [docs/deployment/azure/aca-deployment-azd-in-depth](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-azd-in-depth?branch=pr-en-us-1395) |
=> Fix supported -> support typo

docs/fundamentals/app-host-overview.md
Add missing resources from new hosting packages
Fixes #1398
---
|:--|:--|
| [docs/fundamentals/app-host-overview.md](https://github.com/dotnet/docs-aspire/blob/de97f2906048e3f483a20335d481c470e8de7050/docs/fundamentals/app-host-overview.md) | [docs/fundamentals/app-host-overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/app-host-overview?branch=pr-en-us-1399) |
=> Add missing resources from new hosting packages

docs/messaging/kafka-component.md
Updating the Kafka docs to mention KafkaUI.
---
|:--|:--|
| [docs/messaging/kafka-component.md](https://github.com/dotnet/docs-aspire/blob/78ce83ce7fcc587cebaee1ef0e301b2323618472/docs/messaging/kafka-component.md) | [docs/messaging/kafka-component](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/kafka-component?branch=pr-en-us-1401) |
=> Kafka UI mention.

.github/policies/auto-merge.yml, .github/policies/label-prs.yml
Sync a few bits from .NET docs proper
=> Sync a few bits from .NET docs proper

.github/ISSUE_TEMPLATE/03-customer-support.yml
=> Add CSS template

docs/security/azure-security-key-vault-component.md
Address UUF issues for Azure Key Vault content.
Fixes #1380.
---
|:--|:--|
| [docs/security/azure-security-key-vault-component.md](https://github.com/dotnet/docs-aspire/blob/98625ff7b5cba020920e79e928534a4205f6442d/docs/security/azure-security-key-vault-component.md) | [docs/security/azure-security-key-vault-component](https://review.learn.microsoft.com/en-us/dotnet/aspire/security/azure-security-key-vault-component?branch=pr-en-us-1414) |
=> Address UUF issues for Azure Key Vault content

docs/database/mongodb-component.md
Added some additional information regarding support for MongoDB Atlas. 
Also removed a section around the configuration extensions which doesn't appear to be supported by the component.
744
---
|:--|:--|
| [docs/database/mongodb-component.md](https://github.com/dotnet/docs-aspire/blob/9b99a738cabf7425a39006ea44bcf38eb33d5efe/docs/database/mongodb-component.md) | [docs/database/mongodb-component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/mongodb-component?branch=pr-en-us-1410) |
=> Update to MongoDB Component Doc

docs/database/mongodb-component.md
Changed one line back relating to database requirements due to incorrect knowledge on my part when making the change.
Related to #744
---
|:--|:--|
| [docs/database/mongodb-component.md](https://github.com/dotnet/docs-aspire/blob/b6ec45d9206bb79318076cacb94b38e8ee4690d4/docs/database/mongodb-component.md) | [docs/database/mongodb-component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/mongodb-component?branch=pr-en-us-1423) |
=> Updated line that was changed incorrectly

docs/database/ef-core-migrations.md
Fixes #1012 
Fixes https://github.com/MicrosoftDocs/aspire-docs-samples/issues/1
---
|:--|:--|
| [docs/database/ef-core-migrations.md](https://github.com/dotnet/docs-aspire/blob/667f8f52c99e02f3df36e51ac5d2b2615cd3a2f8/docs/database/ef-core-migrations.md) | [docs/database/ef-core-migrations](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/ef-core-migrations?branch=pr-en-us-1443) |
=> Fixes issue on EF Migration doc

docs/fundamentals/dashboard/standalone.md
Update to latest images for standalone dashboards
---
|:--|:--|
| [docs/fundamentals/dashboard/standalone.md](https://github.com/dotnet/docs-aspire/blob/ee598490eedd83dea6d00b371fd7f9ffb6ac3cc3/docs/fundamentals/dashboard/standalone.md) | [docs/fundamentals/dashboard/standalone](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/standalone?branch=pr-en-us-1514) |
=> Update standalone.md 8.1.0 dash

docs/reference/aspire-faq.yml
Address all open FAQ issues.
- Fixes #1097
- Fixes #1116
- Fixes #1483
=> Address all open FAQ issues

docs/fundamentals/networking-overview.md
Correct port. 
Fixes #1523
---
|:--|:--|
| [docs/fundamentals/networking-overview.md](https://github.com/dotnet/docs-aspire/blob/e489774a0faf06d144218d04ad3c13130422acba/docs/fundamentals/networking-overview.md) | [docs/fundamentals/networking-overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/networking-overview?branch=pr-en-us-1524) |
=> Correct port.

docs/fundamentals/external-parameters.md
Remove manifest JSON, replace with link.
Fixes #1521
---
|:--|:--|
| [docs/fundamentals/external-parameters.md](https://github.com/dotnet/docs-aspire/blob/ea14bbc9f72c3a8f94ba835475477382dd7c6b41/docs/fundamentals/external-parameters.md) | [docs/fundamentals/external-parameters](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/external-parameters?branch=pr-en-us-1525) |
=> Remove manifest JSON, replace with link

docs/azureai/azureai-openai-component.md
Add content about details for deployments.
Fixes #1479
---
|:--|:--|
| [docs/azureai/azureai-openai-component.md](https://github.com/dotnet/docs-aspire/blob/37b2272b24ca4bffdba9a166ba857d7912b0d6b1/docs/azureai/azureai-openai-component.md) | [docs/azureai/azureai-openai-component](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-openai-component?branch=pr-en-us-1526) |
=> Add content about details for deployments

docfx.json, docs/database/milvus-integration.md
Add milvus content for release 8.2.
Fixes #1475
---
|:--|:--|
| [docs/database/milvus-integration.md](https://github.com/dotnet/docs-aspire/blob/54eead6c05859c9b24654ab159d16070a58740e0/docs/database/milvus-integration.md) | [docs/database/milvus-integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/milvus-integration?branch=pr-en-us-1554) |
=> Add milvus content for release 8.2.

docs/database/includes/postgresql-pgweb.md, docs/database/postgresql-entity-framework-integration.md, docs/database/postgresql-integration.md
Added PgWeb details. 
Fixes #1472
---
|:--|:--|
| [docs/database/postgresql-entity-framework-integration.md](https://github.com/dotnet/docs-aspire/blob/93fbca518e942dd7764f394126a253a65be52544/docs/database/postgresql-entity-framework-integration.md) | [docs/database/postgresql-entity-framework-integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/postgresql-entity-framework-integration?branch=pr-en-us-1555) |
| [docs/database/postgresql-integration.md](https://github.com/dotnet/docs-aspire/blob/93fbca518e942dd7764f394126a253a65be52544/docs/database/postgresql-integration.md) | [docs/database/postgresql-integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/postgresql-integration?branch=pr-en-us-1555) |
=> Added PgWeb details

docs/database/includes/postgresql-pgadmin.md, docs/database/postgresql-entity-framework-integration.md, docs/database/postgresql-integration.md
Add simple document for PgAdmin section in postgresql integration
---
|:--|:--|
| [docs/database/postgresql-entity-framework-integration.md](https://github.com/dotnet/docs-aspire/blob/c9cb72da2510cdf058c4c71acec06bef053a6191/docs/database/postgresql-entity-framework-integration.md) | [docs/database/postgresql-entity-framework-integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/postgresql-entity-framework-integration?branch=pr-en-us-1603) |
| [docs/database/postgresql-integration.md](https://github.com/dotnet/docs-aspire/blob/c9cb72da2510cdf058c4c71acec06bef053a6191/docs/database/postgresql-integration.md) | [docs/database/postgresql-integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/postgresql-integration?branch …
=> Add PgAdmin in postgresql integration

docs/reference/aspire-faq.yml, docs/toc.yml
Add FAQ style details regarding IIS. 
Fixes #1113 — [Preview](https://review.learn.microsoft.com/en-us/dotnet/aspire/reference/aspire-faq?branch=pr-en-us-1606)
=> Add FAQ style details regarding IIS.

docs/deployment/azure/application-insights.md
Updates developemnt to development
---
|:--|:--|
| [docs/deployment/azure/application-insights.md](https://github.com/dotnet/docs-aspire/blob/83bd25353485dedb0c7a18023377ac8beabcfc69/docs/deployment/azure/application-insights.md) | [docs/deployment/azure/application-insights](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/application-insights?branch=pr-en-us-1665) |
=> Fix spelling error in the article about Application Insights

docs/azureai/azureai-openai-integration.md, docs/fundamentals/app-host-overview.md, docs/fundamentals/external-parameters.md, docs/get-started/aspire-overview.md, docs/get-started/build-your-first-aspire-app.md, docs/toc.yml
In this PR:
- Addressing issues with Mac experience and Aspire connection to logs and redis
- Added a note about MacOS and Safari
- Edit pass with Acrolinx
Issues addressed:
- Fixes #1152
- Fixes #1519
- Fixes #1108
---
|:--|:--|
| [docs/azureai/azureai-openai-integration.md](https://github.com/dotnet/docs-aspire/blob/7b88a04db7c6e03ee7e4c2fbc3b020d66909bd5e/docs/azureai/azureai-openai-integration.md) | [docs/azureai/azureai-openai-integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-openai-integration?branch=pr-en-us-1702) |
| [docs/fundamentals/app-host-overview.md](https://github.com/dotnet/docs-aspire/blob/7b88a04db7c6e03ee7e4c2fbc3b020d66909bd5e/docs/fundamentals/app-host-overview.md) | …
=> Addressing several issues

quest-config.json
I also moved the default node down one so it's easier to find. the value for the freshness node didn't change.
=> fix default nodes

docs/extensibility/snippets/MailDevResourceAndComponent/MailKit.Client/MailKit.Client.csproj
Fix Microsoft.Extensions.Configuration.Binder version typo in the docs.
=> Fix typo in the docs

docs/messaging/kafka-integration.md, docs/messaging/nats-integration.md, docs/messaging/rabbitmq-integration.md
Demote messaging integration headings.
Fixes #1811
---
|:--|:--|
| [docs/messaging/kafka-integration.md](https://github.com/dotnet/docs-aspire/blob/e1c8302ec51b1a893807e505fbac411c357f5e8c/docs/messaging/kafka-integration.md) | [docs/messaging/kafka-integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/kafka-integration?branch=pr-en-us-1812) |
| [docs/messaging/nats-integration.md](https://github.com/dotnet/docs-aspire/blob/e1c8302ec51b1a893807e505fbac411c357f5e8c/docs/messaging/nats-integration.md) | [docs/messaging/nats-integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/nats-integration?branch=pr-en-us-1812) |
| [docs/messaging/rabbitmq-integration.md](https://github.com/dotnet/docs-aspire/blob/e1c8302ec51b1a8 …
=> Demote messaging integration headings

docs/community-toolkit/ollama.md
---
|:--|:--|
| [docs/community-toolkit/ollama.md](https://github.com/dotnet/docs-aspire/blob/afa3923a732052f0ed7ab0a259e11ec0989d04b4/docs/community-toolkit/ollama.md) | [.NET Aspire Community Toolkit Ollama integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/community-toolkit/ollama?branch=pr-en-us-1819) |
=> Wrong method in Ollama hosting docs

docs/fundamentals/dashboard/configuration.md, docs/fundamentals/dashboard/enable-browser-telemetry.md, docs/fundamentals/dashboard/overview.md, docs/fundamentals/dashboard/security-considerations.md, docs/fundamentals/dashboard/standalone-for-python.md, docs/fundamentals/dashboard/standalone.md
* Consistently recommend 8.2 image of dashboard. Note that there is an 8.2.1 but no 8.2.0. Seems like leaving out the 3 decimal place is best?
* Refactor browser telemetry docs into two sections.
* Some cleanup on browser telemetry
---
|:--|:--|
| [docs/fundamentals/dashboard/configuration.md](https://github.com/dotnet/docs-aspire/blob/a0372d2001e0b534227881a0721f5f5f3f476515/docs/fundamentals/dashboard/configuration.md) | [docs/fundamentals/dashboard/configuration](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/configuration?branch=pr-en-us-1833) |
| [docs/fundamentals/dashboard/enable-browser-telemetry.md](https://github.com/dotnet/docs-aspire/blob/a0372d2001e0b534227881a0721f5f5f3f476515/docs/fundamentals/dashboard/enable-browse …
=> Various dashboard and telemetry docs updates

docs/whats-new/dotnet-aspire-9-release-candidate-1.md
---
|:--|:--|
| [docs/whats-new/dotnet-aspire-9-release-candidate-1.md](https://github.com/dotnet/docs-aspire/blob/fcb7d292a8ace605e3e75e8aea0e44fdc039423e/docs/whats-new/dotnet-aspire-9-release-candidate-1.md) | [.NET Aspire 9.0 (Release Candidate 1)](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9-release-candidate-1?branch=pr-en-us-1838) |
=> Remove videos

docs/whats-new/dotnet-aspire-9-release-candidate-1.md
---
|:--|:--|
| [docs/whats-new/dotnet-aspire-9-release-candidate-1.md](https://github.com/dotnet/docs-aspire/blob/9a3cfc0c91798c5a48a0a3d2d28a051af28dfa75/docs/whats-new/dotnet-aspire-9-release-candidate-1.md) | [.NET Aspire 9.0 (Release Candidate 1)](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9-release-candidate-1?branch=pr-en-us-1841) |
=> Update OpenAI section in 9.0-rc1 whats-new

docs/whats-new/dotnet-aspire-9-release-candidate-1.md
I added it in the link name to the package too, feel free to remove if it doesn't matter.
---
|:--|:--|
| [docs/whats-new/dotnet-aspire-9-release-candidate-1.md](https://github.com/dotnet/docs-aspire/blob/8733a5007fbaa8f25c1ec9a173e58fa93ec8f398/docs/whats-new/dotnet-aspire-9-release-candidate-1.md) | [.NET Aspire 9.0 (Release Candidate 1)](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9-release-candidate-1?branch=pr-en-us-1843) |
=> Add Preview moniker to the OpenAI integration

docs/whats-new/dotnet-aspire-9-release-candidate-1.md
Add example code for how to configure your application to talk to Azure PostgreSQL and Redis using Entra ID.
---
|:--|:--|
| [docs/whats-new/dotnet-aspire-9-release-candidate-1.md](https://github.com/dotnet/docs-aspire/blob/28a423007435f6cd5911d9d5a919ed05ae0877bb/docs/whats-new/dotnet-aspire-9-release-candidate-1.md) | [.NET Aspire 9.0 (Release Candidate 1)](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9-release-candidate-1?branch=pr-en-us-1842) |
=> Add code for using managed identity for postgres and redis

docs/caching/includes/garnet-intro.md, docs/caching/includes/redis-client-json-settings.md, docs/caching/includes/redis-hosting-health-checks.md, docs/caching/includes/redis-intro.md, docs/caching/includes/redis-trademark.md, docs/caching/includes/valkey-intro.md, docs/caching/stackexchange-redis-caching-overview.md, docs/caching/stackexchange-redis-distributed-caching-integration.md, docs/caching/stackexchange-redis-integration.md, docs/caching/stackexchange-redis-output-caching-integration.md, docs/includes/integration-health-checks.md, docs/includes/integration-observability-and-telemetry.md, docs/zones/zone-pivot-groups.yml
Updates to other Redis-protocol docs.
Fixes #1847 and fixes #1848
---
|:--|:--|
| [docs/caching/stackexchange-redis-caching-overview.md](https://github.com/dotnet/docs-aspire/blob/19d8216096b546f82c07799ae354fa110fcdf764/docs/caching/stackexchange-redis-caching-overview.md) | [Stack Exchange Redis&reg;<sup>**[*](#registered)**</sup> caching overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/caching/stackexchange-redis-caching-overview?branch=pr-en-us-1849) |
| [docs/caching/stackexchange-redis-distributed-caching-integration.md](https://github.com/dotnet/docs-aspire/blob/19d8216096b546f82c07799ae354fa110fcdf764/docs/caching/stackexchange-redis-distributed-caching-integration.md) | [.NET Aspire Redis&reg;<sup>**[*](#registered)**</sup> distributed …
=> Updates to other Redis-protocol docs

docs/community-toolkit/ollama.md
Add a sample scenario to run ollama in the container using GPUs instead of CPUs (cpu is the default value)
---
|:--|:--|
| [docs/community-toolkit/ollama.md](https://github.com/dotnet/docs-aspire/blob/1b8d732568aad99e63a690c9c913d5f9f98e1529/docs/community-toolkit/ollama.md) | [.NET Aspire Community Toolkit Ollama integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/community-toolkit/ollama?branch=pr-en-us-1887) |
=> Update ollama.md, add support for GPUs

docs/extensibility/secure-communication-between-integrations.md
Fix typo at cred**ne**tials
---
|:--|:--|
| [docs/extensibility/secure-communication-between-integrations.md](https://github.com/dotnet/docs-aspire/blob/b05b4f8942235a2e997b5b31220852151de4d251/docs/extensibility/secure-communication-between-integrations.md) | [Secure communication between hosting and client integrations](https://review.learn.microsoft.com/en-us/dotnet/aspire/extensibility/secure-communication-between-integrations?branch=pr-en-us-2008) |
=> Fix typo in secure-communication-between-integrations.md

docs/toc.yml
---
|:--|:--|
| [docs/toc.yml](https://github.com/dotnet/docs-aspire/blob/9ca30902141a78c007d3466545e19f2ab4f87908/docs/toc.yml) | [docs/toc](https://review.learn.microsoft.com/en-us/dotnet/aspire/toc?branch=pr-en-us-2047) |
=> Update toc.yml so telemetry doc matches OpenTelemetry search

docs/caching/includes/redis-app-host.md
Docs for adding Redis Insight were incorrect with a small typo.
=> Fix incorrect code snippet for Redis Insight

docs/whats-new/dotnet-aspire-9.md
The docs for custom resource commands didn't read great, hopefully this is a little better. 
---
|:--|:--|
| [docs/whats-new/dotnet-aspire-9.md](https://github.com/dotnet/docs-aspire/blob/954c5e72db1b2d5ea0bcf4bbd4dab798923eb235/docs/whats-new/dotnet-aspire-9.md) | [What's new in .NET Aspire 9.0](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9?branch=pr-en-us-2043) |
=> Update custom resource commands section of aspire 9 docs page

docs/reference/aspire-faq.yml
---
|:--|:--|
| [docs/reference/aspire-faq.yml](https://github.com/dotnet/docs-aspire/blob/b9da826c738d88619b2b4e8a69ae9f71b42dacd2/docs/reference/aspire-faq.yml) | [Frequently asked questions about .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/reference/aspire-faq?branch=pr-en-us-2082) |
=> add link to functions integration

docs/community-toolkit/ollama.md
- Aligned with newer doc format
- Added  info on HuggingFace models
- Added info on MEAI usage with OllamaSharp
Closes #2042
---
|:--|:--|
| [docs/community-toolkit/ollama.md](https://github.com/dotnet/docs-aspire/blob/381dc02b0634ec850bd9f89e19a5004da6aaf797/docs/community-toolkit/ollama.md) | [.NET Aspire Community Toolkit Ollama integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/community-toolkit/ollama?branch=pr-en-us-2092) |
=> Overhaul of the Ollama docs

docs/community-toolkit/hosting-golang.md
Updates Golang doc to describe port changes.
Fixes #2126
---
|:--|:--|
| [docs/community-toolkit/hosting-golang.md](https://github.com/dotnet/docs-aspire/blob/9d3ea3aa046f1df5fc0241074cd6b7beae459e85/docs/community-toolkit/hosting-golang.md) | [.NET Aspire Go hosting](https://review.learn.microsoft.com/en-us/dotnet/aspire/community-toolkit/hosting-golang?branch=pr-en-us-2127) |
=> Updates golang doc

docs/community-toolkit/hosting-data-api-builder.md, docs/toc.yml
Adds dab documentation
Fixes #1994
---
|:--|:--|
| [docs/community-toolkit/hosting-data-api-builder.md](https://github.com/dotnet/docs-aspire/blob/3c700499a2c69883f85e65aaa26476ef9a42f359/docs/community-toolkit/hosting-data-api-builder.md) | [Community Toolkit Azure Data API Builder hosting integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/community-toolkit/hosting-data-api-builder?branch=pr-en-us-2129) |
| [docs/toc.yml](https://github.com/dotnet/docs-aspire/blob/3c700499a2c69883f85e65aaa26476ef9a42f359/docs/toc.yml) | [docs/toc](https://review.learn.microsoft.com/en-us/dotnet/aspire/toc?branch=pr-en-us-2129) |
=> Article for dab

docs/database/includes/postgresql-app-host.md
In the PostgreSQL document there is a reference to RabbitMQ, from my perspective this should be PostgreSQL
Fixes no issue created, searched for an existing issue, but that was also not found. Just a quick fix
=> Fix copy paste error

docs/reference/aspire-faq.yml, docs/toc.yml
Shorten questions and fix #2128.
---
|:--|:--|
| [docs/reference/aspire-faq.yml](https://github.com/dotnet/docs-aspire/blob/4503d347b46ac7b3a8bcc89b331cb38916dfc141/docs/reference/aspire-faq.yml) | [Frequently asked questions about .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/reference/aspire-faq?branch=pr-en-us-2130) |
| [docs/toc.yml](https://github.com/dotnet/docs-aspire/blob/4503d347b46ac7b3a8bcc89b331cb38916dfc141/docs/toc.yml) | [docs/toc](https://review.learn.microsoft.com/en-us/dotnet/aspire/toc?branch=pr-en-us-2130) |
=> Shorten questions and fix issues with rendering.

docs/community-toolkit/hosting-eventstore.md, docs/toc.yml
CommunityToolkit docs for EventStore integration
Integration PR: https://github.com/CommunityToolkit/Aspire/pull/277
---
|:--|:--|
| [docs/community-toolkit/hosting-eventstore.md](https://github.com/dotnet/docs-aspire/blob/f5884dee78ec2b59e1ffd4ac99533f26abbc5a74/docs/community-toolkit/hosting-eventstore.md) | [.NET Aspire Community Toolkit EventStore integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/community-toolkit/hosting-eventstore?branch=pr-en-us-2143) |
| [docs/toc.yml](https://github.com/dotnet/docs-aspire/blob/f5884dee78ec2b59e1ffd4ac99533f26abbc5a74/docs/toc.yml) | [docs/toc](https://review.learn.microsoft.com/en-us/dotnet/aspire/toc?branch=pr-en-us-2143) |
=> CommunityToolkit docs for EventStore integration

docs/app-host/configuration.md, docs/fundamentals/dashboard/configuration.md, docs/fundamentals/launch-profiles.md, docs/toc.yml
Fixes https://github.com/dotnet/docs-aspire/issues/1602
---
|:--|:--|
| [docs/app-host/configuration.md](https://github.com/dotnet/docs-aspire/blob/1518b486deef707f081e2470c5d5ca5d2490a3d8/docs/app-host/configuration.md) | [App host configuration](https://review.learn.microsoft.com/en-us/dotnet/aspire/app-host/configuration?branch=pr-en-us-2141) |
| [docs/fundamentals/dashboard/configuration.md](https://github.com/dotnet/docs-aspire/blob/1518b486deef707f081e2470c5d5ca5d2490a3d8/docs/fundamentals/dashboard/configuration.md) | [.NET Aspire dashboard configuration](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/configuration?branch=pr-en-us-2141) |
| [docs/fundamentals/launch-profiles.md](https://github.com/dotnet/docs-aspire/blob/151 …
=> Add app host configuration page

docs/database/sql-server-entity-framework-integration.md, docs/database/sql-server-integration.md, docs/database/sql-server-integrations.md
Rewrite SQL Server EF Core integration. Fixes #2170
---
|:--|:--|
| [docs/database/sql-server-entity-framework-integration.md](https://github.com/dotnet/docs-aspire/blob/98dc1095e961a27ac2f4b3393eb2d808e508d2e0/docs/database/sql-server-entity-framework-integration.md) | [.NET Aspire SQL Server Entity Framework Core integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/sql-server-entity-framework-integration?branch=pr-en-us-2171) |
| [docs/database/sql-server-integration.md](https://github.com/dotnet/docs-aspire/blob/98dc1095e961a27ac2f4b3393eb2d808e508d2e0/docs/database/sql-server-integration.md) | [.NET Aspire SQL Server integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/sql-server-integration?branch=pr-en-us-217 …
=> Rewrite SQL Server EF Core integration.

docs/database/mysql-entity-framework-integration.md, docs/database/oracle-entity-framework-integration.md, docs/whats-new/dotnet-aspire-9.md
Fixing typos
---
|:--|:--|
| [docs/database/mysql-entity-framework-integration.md](https://github.com/dotnet/docs-aspire/blob/232d6d063e4f711366ea45c7788e8488380e99af/docs/database/mysql-entity-framework-integration.md) | [.NET Aspire Pomelo MySQL Entity Framework Component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/mysql-entity-framework-integration?branch=pr-en-us-2179) |
| [docs/database/oracle-entity-framework-integration.md](https://github.com/dotnet/docs-aspire/blob/232d6d063e4f711366ea45c7788e8488380e99af/docs/database/oracle-entity-framework-integration.md) | [Oracle Entity Framework Component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/oracle-entity-framework-integration?branch=pr-en-us-2179) |
| …
=> Remove a few instances of redundant "the"

.github/workflows/create-monthly-issues.yml
Fix monthly workflow. Fix this: https://github.com/dotnet/docs-aspire/actions/runs/11991569857
---
|:--|:--|
| [.github/workflows/create-monthly-issues.yml](https://github.com/dotnet/docs-aspire/blob/f852b67febe78b4e854c8a2fb898fd52fd372055/.github/workflows/create-monthly-issues.yml) | [.github/workflows/create-monthly-issues](https://review.learn.microsoft.com/en-us/dotnet/aspire/.github/workflows/create-monthly-issues?branch=pr-en-us-2242) |
=> Fix monthly workflow.

docs/fundamentals/service-defaults.md
Split up long sentence.
Avoid please
remove jargon
---
|:--|:--|
| [docs/fundamentals/service-defaults.md](https://github.com/dotnet/docs-aspire/blob/f57d3d484f5cf6409c3162317e1802a33eeb07c0/docs/fundamentals/service-defaults.md) | [.NET Aspire service defaults](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/service-defaults?branch=pr-en-us-2245) |
=> Update service-defaults.md per MS style guide

docs/database/mysql-entity-framework-integration.md
Fix issue with MD - see https://github.com/dotnet/docs-aspire/actions/runs/12300908251/job/34330225078?pr=2285
---
|:--|:--|
| [docs/database/mysql-entity-framework-integration.md](https://github.com/dotnet/docs-aspire/blob/12b65801ca9bfef8dea244487a0f43807bda83e1/docs/database/mysql-entity-framework-integration.md) | [.NET Aspire Pomelo MySQL Entity Framework Core integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/mysql-entity-framework-integration?branch=pr-en-us-2288) |
=> Fix issue with MD

docs/azure/integrations-overview.md
Add content about connecting to existing resources. 
Fixes #2319
---
|:--|:--|
| [docs/azure/integrations-overview.md](https://github.com/dotnet/docs-aspire/blob/06300832c8d2102a82d9b943d65e89b01f9e0318/docs/azure/integrations-overview.md) | [.NET Aspire Azure integrations overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/azure/integrations-overview?branch=pr-en-us-2320) |
=> Add content about connecting to existing resources

docs/frameworks/orleans.md, docs/frameworks/snippets/Orleans/OrleansAppHost/Program.cs
More description, simpler structure.
Fixes #2302
---
|:--|:--|
| [docs/frameworks/orleans.md](https://github.com/dotnet/docs-aspire/blob/56b4a8da69ffd105016ef377f6994d98881ba087/docs/frameworks/orleans.md) | [.NET Aspire Orleans integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/frameworks/orleans?branch=pr-en-us-2355) |
=> Orleans integration article rewrite

docs/database/milvus-integration.md
Restructured and expanded.
Fixes #2303
---
|:--|:--|
| [docs/database/milvus-integration.md](https://github.com/dotnet/docs-aspire/blob/db0e744228343edd351a49442d140f89134d0315/docs/database/milvus-integration.md) | [.NET Aspire Milvus database integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/milvus-integration?branch=pr-en-us-2367) |
=> Update Milvus integration doc

docs/database/qdrant-integration.md
Expands and restructures the Qdrant integration article.
Fixes #2304 
---
|:--|:--|
| [docs/database/qdrant-integration.md](https://github.com/dotnet/docs-aspire/blob/14cdb8f10fef356cf86b4f846444ba0ead9aa309/docs/database/qdrant-integration.md) | [.NET Aspire Qdrant integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/qdrant-integration?branch=pr-en-us-2424) |
=> Qdrant integration rewrite

docs/deployment/azure/aca-deployment-github-actions.md
Update docs for azd pipeline config.
azd automatically generates the pipelines files. Removing the part of the manual adding from the docs.
---
|:--|:--|
| [docs/deployment/azure/aca-deployment-github-actions.md](https://github.com/dotnet/docs-aspire/blob/90e0303529d7f4193a6c7ccf4d406a8ee0ec4100/docs/deployment/azure/aca-deployment-github-actions.md) | [Tutorial: Deploy a .NET Aspire project using the Azure Developer CLI](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-github-actions?branch=pr-en-us-2484) |
=> remove instructions to add the workflow manually

docs/compatibility/9.0/index.md, docs/compatibility/9.1/container-image-name-and-tag-updates.md, docs/compatibility/9.1/cosmos-db-obsolete-apis.md, docs/compatibility/9.1/index.md, docs/compatibility/9.1/python-hosting-integration-api-changes.md, docs/compatibility/9.1/service-bus-obsolete-apis.md, docs/compatibility/9.1/testing-builder-api-changes.md, docs/compatibility/categories.md, docs/compatibility/toc.yml
Fixes breaking changes doc issues:
- Fixes #2327
- Fixes #2428
- Fixes #2557
- Fixes #2559
- Fixes #2616
---
|:--|:--|
| [docs/compatibility/9.0/index.md](https://github.com/dotnet/docs-aspire/blob/9d6eff6519db5a8ea838d4bfbe9277f617dde8fc/docs/compatibility/9.0/index.md) | [Breaking changes in .NET Aspire 9](https://review.learn.microsoft.com/en-us/dotnet/aspire/compatibility/9.0/index?branch=pr-en-us-2619) |
| [docs/compatibility/9.1/container-image-name-and-tag-updates.md](https://github.com/dotnet/docs-aspire/blob/9d6eff6519db5a8ea838d4bfbe9277f617dde8fc/docs/compatibility/9.1/container-image-name-and-tag-updates.md) | [Default container image name and tag changed](https://review.learn.microsoft.com/en-us/dotnet/aspire/compatibility/9.1/container-image-name-a …
=> Fixes breaking changes doc issues

docs/toc.yml, docs/whats-new/dotnet-aspire-9.1.md, docs/whats-new/index.yml, docs/whats-new/toc.yml
Shell for what's new content.
---
|:--|:--|
| [docs/toc.yml](https://github.com/dotnet/docs-aspire/blob/decb5e73b1ac2e1a30c9e4569f6d1ad88de1e254/docs/toc.yml) | [docs/toc](https://review.learn.microsoft.com/en-us/dotnet/aspire/toc?branch=pr-en-us-2620) |
| [docs/whats-new/dotnet-aspire-9.1.md](https://github.com/dotnet/docs-aspire/blob/decb5e73b1ac2e1a30c9e4569f6d1ad88de1e254/docs/whats-new/dotnet-aspire-9.1.md) | [What's new in .NET Aspire 9.1](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9.1?branch=pr-en-us-2620) |
| [docs/whats-new/index.yml](https://github.com/dotnet/docs-aspire/blob/decb5e73b1ac2e1a30c9e4569f6d1ad88de1e254/docs/whats-new/index.yml) | [.NET Aspire — what's …
=> Shell for what's new content

docs/fundamentals/dashboard/configuration.md
Add missing configuration.
Fixes #1659
---
|:--|:--|
| [docs/fundamentals/dashboard/configuration.md](https://github.com/dotnet/docs-aspire/blob/13f7a2c1d6fad82bd1350c78087ca721cc9f0bb4/docs/fundamentals/dashboard/configuration.md) | [Dashboard configuration](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/configuration?branch=pr-en-us-2621) |
=> Add missing configuration

docs/fundamentals/app-host-overview.md
=> Fix invalid file link warning

docs/azure/integrations-overview.md
Current code doesn't compile
https://github.com/dotnet/aspire/discussions/7543#discussioncomment-12162851
---
|:--|:--|
| [docs/azure/integrations-overview.md](https://github.com/dotnet/docs-aspire/blob/15d08e15309a57100079e409f4ae8a5594c331ee/docs/azure/integrations-overview.md) | [.NET Aspire Azure integrations overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/azure/integrations-overview?branch=pr-en-us-2644) |
=> Fix sample in integrations-overview.md

docs/messaging/nats-integration.md
Adds the NATS 9.1 API and fixes obsolete API. 
Closes #1817
---
|:--|:--|
| [docs/messaging/nats-integration.md](https://github.com/dotnet/docs-aspire/blob/46ae38dfc0b6efe7bc4eab2631309f1aa8964cca/docs/messaging/nats-integration.md) | [.NET Aspire NATS integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/nats-integration?branch=pr-en-us-2650) |
=> Adds the NATS 9.1 API and fixes obsolete API.

docs/compatibility/9.1/cosmos-db-obsolete-apis.md, docs/compatibility/9.1/event-hubs-obsolete-apis.md, docs/compatibility/9.1/index.md, docs/compatibility/9.1/service-bus-obsolete-apis.md, docs/compatibility/toc.yml
See https://github.com/dotnet/docs-aspire/issues/2327#issuecomment-2673088907
---
|:--|:--|
| [docs/compatibility/9.1/cosmos-db-obsolete-apis.md](https://github.com/dotnet/docs-aspire/blob/656e10e46635c8291f6800dc404650eb6cf3b29d/docs/compatibility/9.1/cosmos-db-obsolete-apis.md) | [Cosmos DB hosting integration obsolete API and default managed identity support](https://review.learn.microsoft.com/en-us/dotnet/aspire/compatibility/9.1/cosmos-db-obsolete-apis?branch=pr-en-us-2651) |
| [docs/compatibility/9.1/event-hubs-obsolete-apis.md](https://github.com/dotnet/docs-aspire/blob/656e10e46635c8291f6800dc404650eb6cf3b29d/docs/compatibility/9.1/event-hubs-obsolete-apis.md) | [Azure Event Hubs hosting integration obsolete …
=> Update breaking changes docs

docs/azure/integrations-overview.md, docs/snippets/azure/AppHost/aspire-manifest.json, docs/snippets/azure/AppHost/config.module.bicep, docs/snippets/azure/AppHost/cosmos.module.bicep, docs/snippets/azure/AppHost/event-hubs.module.bicep, docs/snippets/azure/AppHost/key-vault.module.bicep, docs/snippets/azure/AppHost/openai.module.bicep, docs/snippets/azure/AppHost/search.module.bicep, docs/snippets/azure/AppHost/service-bus.module.bicep, docs/snippets/azure/AppHost/signalr.module.bicep, docs/snippets/azure/AppHost/storage.module.bicep, docs/snippets/azure/AppHost/web-pub-sub.module.bicep
Existing Azure resources: New content detailing the `AsExisting`, `RunAsExisting`, and `PublishAsExisting` APIs.
Closes #2642 and fixes #2549
---
|:--|:--|
| [docs/azure/integrations-overview.md](https://github.com/dotnet/docs-aspire/blob/7e3a361c868bfddfb62b5d3f4499491c8f269711/docs/azure/integrations-overview.md) | [.NET Aspire Azure integrations overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/azure/integrations-overview?branch=pr-en-us-2653) |
=> Existing Azure resources

docs/database/includes/cosmos-app-host.md
=> Add CosmosDB container creation

docs/azure/integrations-overview.md, docs/whats-new/dotnet-aspire-9.1.md
Adding more content to what's new in 9.1 for integrations.
---
|:--|:--|
| [docs/azure/integrations-overview.md](https://github.com/dotnet/docs-aspire/blob/dba9e66085d8a0ad5063fcc08949eb98bc509b9c/docs/azure/integrations-overview.md) | [.NET Aspire Azure integrations overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/azure/integrations-overview?branch=pr-en-us-2657) |
| [docs/whats-new/dotnet-aspire-9.1.md](https://github.com/dotnet/docs-aspire/blob/dba9e66085d8a0ad5063fcc08949eb98bc509b9c/docs/whats-new/dotnet-aspire-9.1.md) | [What's new in .NET Aspire 9.1](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9.1?branch=pr-en-us-2657) |
=> Enhance Integrations What's New in 9.1

docs/whats-new/dotnet-aspire-9.1.md
---
|:--|:--|
| [docs/whats-new/dotnet-aspire-9.1.md](https://github.com/dotnet/docs-aspire/blob/ffca71f792a5f8bfde2bb57c705b616fd833b90b/docs/whats-new/dotnet-aspire-9.1.md) | [What's new in .NET Aspire 9.1](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9.1?branch=pr-en-us-2669) |
=> Add code snippet for using new Azure emulators

.github/ISSUE_TEMPLATE/04-breaking-change.yml
Update the breaking changes template versions.
@DamianEdwards - do we have a full list of potential future versions, so that I might add more to this list?
---
|:--|:--|
| [.github/ISSUE_TEMPLATE/04-breaking-change.yml](https://github.com/dotnet/docs-aspire/blob/77a215e3f39a83b3ed35a1c88c0ec0662fce2ae5/.github/ISSUE_TEMPLATE/04-breaking-change.yml) | ["[Breaking change]: "](https://review.learn.microsoft.com/en-us/dotnet/aspire/.github/ISSUE_TEMPLATE/04-breaking-change?branch=pr-en-us-2561) |
=> Update the breaking changes template versions

docs/azure/integrations-overview.md, docs/messaging/azure-event-hubs-integration.md, docs/messaging/azure-service-bus-integration.md
---
|:--|:--|
| [docs/azure/integrations-overview.md](https://github.com/dotnet/docs-aspire/blob/b53532f4e7db5361cddec67fb2fbaf77639ee74f/docs/azure/integrations-overview.md) | [.NET Aspire Azure integrations overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/azure/integrations-overview?branch=pr-en-us-2675) |
| [docs/messaging/azure-event-hubs-integration.md](https://github.com/dotnet/docs-aspire/blob/b53532f4e7db5361cddec67fb2fbaf77639ee74f/docs/messaging/azure-event-hubs-integration.md) | [.NET Aspire Azure Event Hubs integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/azure-event-hubs-integration?branch=pr-en-us-2675) |
| [docs/messaging/azure-service-bus-integration.md](https://github.com/dotnet/docs-aspire/blob/b5353 …
=> Add several missing xrefs

docs/whats-new/index.yml, docs/whats-new/toc.yml
---
|:--|:--|
| [docs/whats-new/index.yml](https://github.com/dotnet/docs-aspire/blob/67238c57166e79fd3952001142e06ec9af8cdd75/docs/whats-new/index.yml) | [.NET Aspire — what's new?](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/index?branch=pr-en-us-2676) |
| [docs/whats-new/toc.yml](https://github.com/dotnet/docs-aspire/blob/67238c57166e79fd3952001142e06ec9af8cdd75/docs/whats-new/toc.yml) | [docs/whats-new/toc](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/toc?branch=pr-en-us-2676) |
=> Add release tag links

docs/database/sql-server-integrations.md
I've added a demo of data volumes and data persistence at the end. This addresses one of the complaints raised here: https://www.youtube.com/watch?v=uIN7iEsRkS4
Contributes to #1846
---
|:--|:--|
| [docs/database/sql-server-integrations.md](https://github.com/dotnet/docs-aspire/blob/862e9df10095c88a279c65bd5950b0ebfa81532f/docs/database/sql-server-integrations.md) | [Tutorial: Connect an ASP.NET Core app to SQL Server using .NET Aspire and Entity Framework Core](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/sql-server-integrations?branch=pr-en-us-2673) |
=> Add data volumes and persistence to the EF Core tutorial.

.github/ISSUE_TEMPLATE/z-customer-feedback.yml
---
|:--|:--|
| [.github/ISSUE_TEMPLATE/z-customer-feedback.yml](https://github.com/dotnet/docs-aspire/blob/6cb6c33503721fa796a9410c446d6078d1889a51/.github/ISSUE_TEMPLATE/z-customer-feedback.yml) | [.github/ISSUE_TEMPLATE/z-customer-feedback](https://review.learn.microsoft.com/en-us/dotnet/aspire/.github/ISSUE_TEMPLATE/z-customer-feedback?branch=pr-en-us-2711) |
=> Add platform id to feedback template

docs/whats-new/dotnet-aspire-9.1.md
adjust variable names for existing resource example
---
|:--|:--|
| [docs/whats-new/dotnet-aspire-9.1.md](https://github.com/dotnet/docs-aspire/blob/14da08bb7b5dd14d6a7005e382f4f484cc282651/docs/whats-new/dotnet-aspire-9.1.md) | [What's new in .NET Aspire 9.1](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9.1?branch=pr-en-us-2707) |
=> adjust variable names for existing resource example

docs/reference/aspire-faq.yml
Add FAQ about local dev and client integrations.
Fixes #2482
---
|:--|:--|
| [docs/reference/aspire-faq.yml](https://github.com/dotnet/docs-aspire/blob/5b90e62aadbe45f96e11e6102b6efd06f61f5109/docs/reference/aspire-faq.yml) | [Frequently asked questions about .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/reference/aspire-faq?branch=pr-en-us-2717) |
=> Add FAQ about local dev and client integrations

docs/azureai/azureai-search-document-integration.md, docs/snippets/azure/AppHost/Program.ConfigureSearchInfra.cs, docs/toc.yml
Rewrote the .NET Aspire Azure AI Search doc.
Fixes #2315
---
|:--|:--|
| [docs/azureai/azureai-search-document-integration.md](https://github.com/dotnet/docs-aspire/blob/d0a1d8fecb029c561b6bf371aeeb0562e5acf64a/docs/azureai/azureai-search-document-integration.md) | [.NET Aspire Azure AI Search integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-search-document-integration?branch=pr-en-us-2766) |
| [docs/toc.yml](https://github.com/dotnet/docs-aspire/blob/d0a1d8fecb029c561b6bf371aeeb0562e5acf64a/docs/toc.yml) | [docs/toc](https://review.learn.microsoft.com/en-us/dotnet/aspire/toc?branch=pr-en-us-2766) |
=> Rewrote the .NET Aspire Azure AI Search doc

.github/workflows/clean-repo.yml, .github/workflows/dependabot-bot.yml, .github/workflows/whats-new-automation.yml
Use the forked version of GHA to minimize the attack surface area.
---
|:--|:--|
| [.github/workflows/clean-repo.yml](https://github.com/dotnet/docs-aspire/blob/f801c79cd1929741d1e54af5c6303a7a576ae1ee/.github/workflows/clean-repo.yml) | [.github/workflows/clean-repo](https://review.learn.microsoft.com/en-us/dotnet/aspire/.github/workflows/clean-repo?branch=pr-en-us-2872) |
| [.github/workflows/dependabot-bot.yml](https://github.com/dotnet/docs-aspire/blob/f801c79cd1929741d1e54af5c6303a7a576ae1ee/.github/workflows/dependabot-bot.yml) | [The name used in the GitHub UI for the workflow](https://review.learn.microsoft.com/en-us/dotnet/aspire/.github/workflows/dependabot-bot?branch=pr-en-us-2872) |
| [.github/workflows/whats-new-automation.yml](https://github.com/do …
=> Use the dotnet fork to create PRs

docs/messaging/messaging-integrations.md
---
|:--|:--|
| [docs/messaging/messaging-integrations.md](https://github.com/dotnet/docs-aspire/blob/9c47a2005cabbcd265d272b48cce9ba42a0393f8/docs/messaging/messaging-integrations.md) | [Tutorial: Use .NET Aspire messaging integrations in ASP.NET Core](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/messaging-integrations?branch=pr-en-us-2876) |
=> Fix build issue

docs/database/sql-server-integration.md
Added a link to https://github.com/Azure-Samples/azure-sql-db-aspire to help developers find samples on Azure SQL and SQL Server with Aspire
---
|:--|:--|
| [docs/database/sql-server-integration.md](https://github.com/dotnet/docs-aspire/blob/46d1e1ae981fdb2e84cd0b24623aecdc374ecc5e/docs/database/sql-server-integration.md) | [.NET Aspire SQL Server integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/sql-server-integration?branch=pr-en-us-2881) |
=> Added link to Azure SQL and SQL Server samples

.github/prompts/adhere-to-writing-style.prompt.md, .github/prompts/rephrase-selected-text.prompt.md, docs/get-started/aspire-overview.md
Adding GitHub Copilot prompts, for testing and iterating on.
---
|:--|:--|
| [.github/prompts/adhere-to-writing-style.prompt.md](https://github.com/dotnet/docs-aspire/blob/f29de5b6566d8c8a0ab555226080e7247b551246/.github/prompts/adhere-to-writing-style.prompt.md) | [.github/prompts/adhere-to-writing-style.prompt](https://review.learn.microsoft.com/en-us/dotnet/aspire/.github/prompts/adhere-to-writing-style.prompt?branch=pr-en-us-2896) |
| [.github/prompts/rephrase-selected-text.prompt.md](https://github.com/dotnet/docs-aspire/blob/f29de5b6566d8c8a0ab555226080e7247b551246/.github/prompts/rephrase-selected-text.prompt.md) | [.github/prompts/rephrase-selected-text.prompt](https://review.learn.microsoft.com/en-us/dotnet/aspire/.github/prompts/rephrase-selected-text. …
=> Adding GitHub Copilot prompts

quest-config.json
Remove dilithium parents, and add the Bromine tags.
=> Update parent IDs for Bromine

docs/deployment/azure/aca-deployment-azd-in-depth.md
Terminate inline azd code snippet
---
|:--|:--|
| [docs/deployment/azure/aca-deployment-azd-in-depth.md](https://github.com/dotnet/docs-aspire/blob/dfd92418bc1e7be41bb4986bc5526f4cec7a942a/docs/deployment/azure/aca-deployment-azd-in-depth.md) | [Deploy a .NET Aspire project to Azure Container Apps using the Azure Developer CLI (in-depth guide)](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-azd-in-depth?branch=pr-en-us-2908) |
=> Terminate inline azd code snippet

docs/database/snippets/tutorial/aspiresqldeploycontainer/AspireSql.AppHost/Program.cs, docs/database/sql-server-integration-deployment.md, docs/deployment/azure/includes/azd-up-workflow.md, docs/deployment/azure/includes/init-workflow.md
Updates the tutorial to .NET Aspire 9.1 and makes other small corrections. Fixes the case of the solution name ( Now "AspireSql") so that it matches the snippets and no longer causes errors.
Fixes #2840
---
|:--|:--|
| [docs/database/sql-server-integration-deployment.md](https://github.com/dotnet/docs-aspire/blob/8442cda55768dcb103c34a741955e7121ae915d4/docs/database/sql-server-integration-deployment.md) | [Tutorial: Deploy a .NET Aspire project with a SQL Server Database to Azure](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/sql-server-integration-deployment?branch=pr-en-us-2915) |
=> Update the Tutorial: Deploy a .NET Aspire project with a SQL Server Database to Azure

docs/caching/stackexchange-redis-distributed-caching-integration.md
Fixes https://github.com/dotnet/docs-aspire/issues/2625
---
|:--|:--|
| [docs/caching/stackexchange-redis-distributed-caching-integration.md](https://github.com/dotnet/docs-aspire/blob/29991584386f0a61ed9a6ff96483ce8518d43bdc/docs/caching/stackexchange-redis-distributed-caching-integration.md) | [.NET Aspire Redis&reg;<sup>**[*](#registered)**</sup> distributed caching integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/caching/stackexchange-redis-distributed-caching-integration?branch=pr-en-us-2929) |
=> Correct keyed IDistributedCache registration and usage

.github/policies/labelAdded-mapQuest.yml
---
|:--|:--|
| [.github/policies/labelAdded-mapQuest.yml](https://github.com/dotnet/docs-aspire/blob/96c246bb4214a7874686cf3f1c57f092dc143876/.github/policies/labelAdded-mapQuest.yml) | [.github/policies/labelAdded-mapQuest](https://review.learn.microsoft.com/en-us/dotnet/aspire/.github/policies/labelAdded-mapQuest?branch=pr-en-us-3061) |
=> [Policy] Auto remove mapquest label

docs/whats-new/dotnet-aspire-9.2.md
Fixes #3071
---
|:--|:--|
| [docs/whats-new/dotnet-aspire-9.2.md](https://github.com/dotnet/docs-aspire/blob/489d2584c92f728ff2c507c5873bd954c23e8921/docs/whats-new/dotnet-aspire-9.2.md) | [What's new in .NET Aspire 9.2](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9.2?branch=pr-en-us-3074) |
=> Fix a typo.

.github/ISSUE_TEMPLATE/01-general-issue.yml, .github/ISSUE_TEMPLATE/02-docs-request.yml, .github/ISSUE_TEMPLATE/03-customer-support.yml, .github/ISSUE_TEMPLATE/04-breaking-change.yml, .github/ISSUE_TEMPLATE/05-community-toolkit-docs-request.yml, .github/ISSUE_TEMPLATE/06-diagnostic-addition.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/z-customer-feedback.yml
Add new diagnostic issue template and update/clean up existing templates.
---
|:--|:--|
| [.github/ISSUE_TEMPLATE/01-general-issue.yml](https://github.com/dotnet/docs-aspire/blob/f7436169752761dd8e94d7389740a203a137c905/.github/ISSUE_TEMPLATE/01-general-issue.yml) | [.github/ISSUE_TEMPLATE/01-general-issue](https://review.learn.microsoft.com/en-us/dotnet/aspire/.github/ISSUE_TEMPLATE/01-general-issue?branch=pr-en-us-3075) |
| [.github/ISSUE_TEMPLATE/02-docs-request.yml](https://github.com/dotnet/docs-aspire/blob/f7436169752761dd8e94d7389740a203a137c905/.github/ISSUE_TEMPLATE/02-docs-request.yml) | ["[New article]: "](https://review.learn.microsoft.com/en-us/dotnet/aspire/.github/ISSUE_TEMPLATE/02-docs-request?branch=pr-en-us-3075) |
| …
=> Add diagnostic issue template

docs/whats-new/index.yml, docs/whats-new/toc.yml
Added .NET Aspire 9.2 release link
---
|:--|:--|
| [docs/whats-new/index.yml](https://github.com/dotnet/docs-aspire/blob/6563b2431e03aa331c806b62fc596345711372cc/docs/whats-new/index.yml) | [.NET Aspire — what's new?](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/index?branch=pr-en-us-3114) |
| [docs/whats-new/toc.yml](https://github.com/dotnet/docs-aspire/blob/6563b2431e03aa331c806b62fc596345711372cc/docs/whats-new/toc.yml) | [docs/whats-new/toc](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/toc?branch=pr-en-us-3114) |
=> Added .NET Aspire 9.2 release link

docs/storage/azure-storage-queues-integration.md
Correct URL to JSON config schema.
Fixes #3375
---
|:--|:--|
| [docs/storage/azure-storage-queues-integration.md](https://github.com/dotnet/docs-aspire/blob/1040b07ab49754dc94e8728f9c18ee58e6c05242/docs/storage/azure-storage-queues-integration.md) | [.NET Aspire Azure Queue Storage integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/storage/azure-storage-queues-integration?branch=pr-en-us-3381) |
=> Correct URL to JSON config schema.

docs/index.yml
---
|:--|:--|
| [docs/index.yml](https://github.com/dotnet/docs-aspire/blob/53c30fb7915636eca204460d305491bf63db33b6/docs/index.yml) | [Limit summary to 400 characters](https://review.learn.microsoft.com/en-us/dotnet/aspire/index?branch=pr-en-us-3385) |
=> Update Azure Friday show link

docs/app-host/eventing.md, docs/app-host/snippets/AspireApp/AspireApp.AppHost/AspireApp.AppHost.csproj, docs/app-host/snippets/AspireApp/AspireApp.AppHost/Console.txt, docs/app-host/snippets/AspireApp/AspireApp.AppHost/Program.cs, docs/app-host/snippets/AspireApp/AspireApp.ResourceAppHost/AspireApp.ResourceAppHost.csproj, docs/app-host/snippets/AspireApp/AspireApp.ResourceAppHost/Console.txt, docs/app-host/snippets/AspireApp/AspireApp.ResourceAppHost/Program.cs, docs/authentication/snippets/AspireApp/AspireApp.AppHost/AspireApp.AppHost.csproj, docs/fundamentals/snippets/lifecycles/AspireApp/AspireApp.AppHost/Console.txt, docs/fundamentals/snippets/lifecycles/AspireApp/AspireApp.AppHost/Program.cs
Add content for new eventing APIs:
- `InitializeResourceEvent`
- `ResourceEndpointsAllocatedEvent`
Fixes #3372.
---
|:--|:--|
| [docs/app-host/eventing.md](https://github.com/dotnet/docs-aspire/blob/f9dd014bf73bca2ffab78eb4084705a2ce6c9f34/docs/app-host/eventing.md) | [Eventing in .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/app-host/eventing?branch=pr-en-us-3392) |
=> Adds new eventing APIs.

docs/whats-new/dotnet-aspire-9.3.md
This variable declaration isn't used.
---
|:--|:--|
| [docs/whats-new/dotnet-aspire-9.3.md](https://github.com/dotnet/docs-aspire/blob/91e9e4174e3ffcbc6b0ca48111c7419cc1d09f45/docs/whats-new/dotnet-aspire-9.3.md) | [What's new in .NET Aspire 9.3](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9.3?branch=pr-en-us-3613) |
=> Remove unused variable

docs/community-toolkit/hosting-postgresql-extensions.md, docs/community-toolkit/hosting-sqlserver-extensions.md
This pull request updates the documentation for `.NET Aspire Community Toolkit` hosting extensions for PostgreSQL and SQL Server. It introduces the Adminer management UI as a new feature and provides instructions for integrating it into the hosting setup.
---
|:--|:--|
| [docs/community-toolkit/hosting-postgresql-extensions.md](https://github.com/dotnet/docs-aspire/blob/c820004dd8d4daf4406ce29964c0ebc58c831709/docs/community-toolkit/hosting-postgresql-extensions.md) | [.NET Aspire Community Toolkit PostgreSQL hosting extensions](https://review.learn.microsoft.com/en-us/dotnet/aspire/community-toolkit/hosting-postgresql-extensions?branch=pr-en-us-3666) |
| [docs/community-toolkit/hosting-sqlserver-extensions.md](https://github.com/dotnet/docs-aspire/blob/c820004d …
=> Mention Adminer in SqlServer and Postgres Extensions

.github/copilot-instructions.md, .github/prompts/breaking-change.md
---
|:--|:--|
| [.github/copilot-instructions.md](https://github.com/dotnet/docs-aspire/blob/4c04b6af733b24441f9ccb395424183a36d18987/.github/copilot-instructions.md) | [.github/copilot-instructions](https://review.learn.microsoft.com/en-us/dotnet/aspire/.github/copilot-instructions?branch=pr-en-us-3667) |
| [.github/prompts/breaking-change.md](https://github.com/dotnet/docs-aspire/blob/4c04b6af733b24441f9ccb395424183a36d18987/.github/prompts/breaking-change.md) | [.github/prompts/breaking-change](https://review.learn.microsoft.com/en-us/dotnet/aspire/.github/prompts/breaking-change?branch=pr-en-us-3667) |
=> Adding instructions and prompt

docs/testing/overview.md
---
|:--|:--|
| [docs/testing/overview.md](https://github.com/dotnet/docs-aspire/blob/3434d5757874b685b7c7268013d3558a3cdfa579/docs/testing/overview.md) | [.NET Aspire testing overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/testing/overview?branch=pr-en-us-3928) |
=> remove extraneous word

docs/fundamentals/snippets/custom-commands/AspireApp/AspireApp.AppHost/RedisResourceBuilderExtensions.cs
This update refactors the WithCommand method usage in RedisResourceBuilderExtensions to align with the latest .NET Aspire conventions.
Replaced obsolete method overload of WithCommand with the updated overload that uses CommandOptions.
Ensured UpdateState, IconName, and IconVariant are now passed through the new CommandOptions object.
Maintained existing logic for cache clearing and command state update.
This change ensures compatibility with the current Aspire APIs and resolves potential warnings from obsolete API usage.
=> Refactor Redis Clear Command to Use New CommandOptions API

docs/whats-new/dotnet-aspire-9.4.md
Change to using `dotnet new install Aspire.ProjectTemplates` instead of `dotnet new update` so that it covers scenario where folks have only got templates from VS and never installed via the CLI before.
---
|:--|:--|
| [docs/whats-new/dotnet-aspire-9.4.md](https://github.com/dotnet/docs-aspire/blob/d405244cfac2e38f52a9dae40e1fb7ac3cded47c/docs/whats-new/dotnet-aspire-9.4.md) | [docs/whats-new/dotnet-aspire-9.4](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9.4?branch=pr-en-us-4159) |
=> Update template update instructions in dotnet-aspire-9.4.md

docs/whats-new/dotnet-aspire-9.4.md
---
|:--|:--|
| [docs/whats-new/dotnet-aspire-9.4.md](https://github.com/dotnet/docs-aspire/blob/5a454224dcbf256e3b0e287dd1f8b15fd2b3cbf8/docs/whats-new/dotnet-aspire-9.4.md) | [What's new in .NET Aspire 9.4](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9.4?branch=pr-en-us-4158) |
=> adding back xrefs

docs/azureai/ai-integrations-compatibility-matrix.md
---
|:--|:--|
| [docs/azureai/ai-integrations-compatibility-matrix.md](https://github.com/dotnet/docs-aspire/blob/15715a54cfc022db2a12983842fbad71a1873f48/docs/azureai/ai-integrations-compatibility-matrix.md) | [Aspire AI integrations compatibility matrix](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/ai-integrations-compatibility-matrix?branch=pr-en-us-4296) |
=> Fix connection string format for Aspire.OpenAI

docs/fundamentals/dashboard/standalone-for-python.md
- Minor copy fix one of the code snippet
- Typo in import statement 
---
|:--|:--|
| [docs/fundamentals/dashboard/standalone-for-python.md](https://github.com/dotnet/docs-aspire/blob/2470de8ca1ea4760f427e5a976ac13f500d155a8/docs/fundamentals/dashboard/standalone-for-python.md) | [Tutorial: Use the .NET Aspire dashboard with Python apps](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/standalone-for-python?branch=pr-en-us-4304) |
=> Import copy fix in document

docs/whats-new/dotnet-aspire-9.4.md
Fix typo in "capabilities".
---
|:--|:--|
| [docs/whats-new/dotnet-aspire-9.4.md](https://github.com/dotnet/docs-aspire/blob/2c7acf2a8b60b2f13421248c85da5c44bf96a5a2/docs/whats-new/dotnet-aspire-9.4.md) | [What's new in .NET Aspire 9.4](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9.4?branch=pr-en-us-4354) |
=> Fix minor typo

docs/cli-reference/aspire-config-delete.md, docs/cli-reference/aspire-config-get.md, docs/cli-reference/aspire-config-set.md, docs/cli-reference/aspire-config.md, docs/cli/config-settings.md, docs/cli/overview.md, docs/toc.yml
- Added new CLI config overview.
- Altered header text for settings in command reference. I think `Available commands` helps set it apart from the CLI sections.
- TOC header adjusted to move `[command]` to the parent. I think it stands out a little better. I'm not tied to it one way or the other.
Fixes #4804
---
|:--|:--|
| [docs/cli-reference/aspire-config-delete.md](https://github.com/dotnet/docs-aspire/blob/d57c589296bebe3d4165454bab571f183aa8e68f/docs/cli-reference/aspire-config-delete.md) | [docs/cli-reference/aspire-config-delete](https://review.learn.microsoft.com/en-us/dotnet/aspire/cli-reference/aspire-config-delete?branch=pr-en-us-4805) |
| [docs/cli-reference/aspire-config-get.md](https://github.com/dotnet/docs-aspire/blob/d57c589296bebe3d4165454bab57 …
=> Add new config settings overview
