dotnet/docs-aspire

- docs/database/postgresql-entity-framework-component.md
Replace Azure Cosmos DB with PostgreSQL
Replaced Azure Cosmos DB with PostgreSQL
---
|:--|:--|
| [docs/database/postgresql-entity-framework-component.md](https://github.com/dotnet/docs-aspire/blob/6a9a32f662955c11eeff3faa20f05069c2b4d9b3/docs/database/postgresql-entity-framework-component.md) | [.NET Aspire PostgreSQL Entity Framework Core component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/postgresql-entity-framework-component?branch=pr-en-us-59) |
> Update postgresql-entity-framework-component.md: Replace Azure Cosmos DB with PostgreSQL

- docs/setup-tooling.md
I was trying to install Aspire on my machine and got confused by following the instructions. This tries to improve it.
---
|:--|:--|
| [docs/setup-tooling.md](https://github.com/dotnet/docs-aspire/blob/fef7fa140d18670e21b81634eeede975abb15bb5/docs/setup-tooling.md) | [.NET Aspire setup and tooling](https://review.learn.microsoft.com/en-us/dotnet/aspire/setup-tooling?branch=pr-en-us-77) |
> Clarify VS version on setup

- docs/deployment/azure/includes/aca-deployment-bicep.md
Since the example uses `az group create --location westus --name aspiretoacarg` to create the subscription-level resource group, the bicep files don't need the `targetScope` to be set to `'subscription'`. Fixes #74
> removed `targetScope='subscription'` in aca-deployment-bicep.md

- docs/storage/azure-storage-queues-component.md
- docs/storage/azure-storage-tables-component.md
This PR is to:
- Improve consistency on variables among blobs, queues and tables
```csharp
// blobs
var blobs = builder.AddAzureStorage("storage")
.AddBlobs("blobs");
// queues
var queues = builder.AddAzureStorage("storage")
.AddQueues("queues");
// tables
var tables = builder.AddAzureStorage("storage")
.AddTables("tables");
```
---
|:--|:--|
| [docs/storage/azure-storage-queues-component.md](https://github.com/dotnet/docs-aspire/blob/88576d109fe318d4f716de99839ae59cb7a208a5/docs/storage/azure-storage-queues-component.md) | [.NET Aspire Azure Queue Storage component](https://review.learn.microsoft.com/en-us/dotnet/aspire/storage/azure-storage-queues-component?branch=pr-en-us-85) |
| [docs/storage/azure-storage-tables-component.md](https://github.com/dotnet/docs- …
> Fix typo on Table Storage Component

- docs/get-started/quickstart-build-your-first-aspire-app.md
Replaced "redis" with "cache" to match what's added in Program.cs
Fixes #89
---
|:--|:--|
| [docs/get-started/quickstart-build-your-first-aspire-app.md](https://github.com/dotnet/docs-aspire/blob/17a671543f22b0932983e715b92c4a0dd2c9bd1e/docs/get-started/quickstart-build-your-first-aspire-app.md) | [Quickstart: Build your first .NET Aspire app](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/quickstart-build-your-first-aspire-app?branch=pr-en-us-91) |
> Fixed typo identified in #89

- docs/reference/aspire-faq.yml
Corrected grammar in documentation: removed duplicate 'the'
> Corrected grammar in documentation: removed duplicate 'the'

- docs/get-started/aspire-overview.md
Fixes #62
---
|:--|:--|
| [docs/get-started/aspire-overview.md](https://github.com/dotnet/docs-aspire/blob/c05ec9d7f3afdcafce4bfe9db71e1adb2933516f/docs/get-started/aspire-overview.md) | [.NET Aspire overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/aspire-overview?branch=pr-en-us-99) |
> Add a benefits blurb and heading

- docs/database/sql-server-component.md
Fix typo and be more consistent with naming.
Fixes #111
---
|:--|:--|
| [docs/database/sql-server-component.md](https://github.com/dotnet/docs-aspire/blob/a536a7ad2bd309da444b9f7cb845ba23a19dbf63/docs/database/sql-server-component.md) | [.NET Aspire SQL Server component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/sql-server-component?branch=pr-en-us-113) |
> Fix typo and be more consistent with naming.

- docs/storage/azure-storage.md
- docs/storage/snippets/tutorial/AspireStorage/AspireStorage.Worker/appsettings.json
- docs/storage/snippets/tutorial/AspireStorage/AspireStorage/appsettings.json
Remove _appsettings.json_ connection strings as the AppHost does this.
---
|:--|:--|
| [docs/storage/azure-storage.md](https://github.com/dotnet/docs-aspire/blob/5c61373fc738ea4c7cd328902fdd549e0880b736/docs/storage/azure-storage.md) | [Tutorial: Connect an ASP.NET Core app to .NET Aspire storage components](https://review.learn.microsoft.com/en-us/dotnet/aspire/storage/azure-storage?branch=pr-en-us-118) |
> Remove appsettings.json connection strings as the apphost does this

- docs/app-host-overview.md
- docs/components-overview.md
- docs/database/postgresql-component.md
- docs/snippets/components/AspireApp/AspireApp.AppHost/AspireApp.AppHost.csproj
- docs/snippets/components/AspireApp/AspireApp.AppHost/Program.cs
- docs/snippets/components/AspireApp/AspireApp.AppHost/Properties/launchSettings.json
- docs/snippets/components/AspireApp/AspireApp.AppHost/appsettings.Development.json
- docs/snippets/components/AspireApp/AspireApp.AppHost/appsettings.json
- docs/snippets/components/AspireApp/AspireApp.ServiceDefaults/AspireApp.ServiceDefaults.csproj
- docs/snippets/components/AspireApp/AspireApp.ServiceDefaults/Extensions.cs
- docs/snippets/components/AspireApp/AspireApp.sln
- docs/snippets/components/AspireApp/WorkerService/Program.cs
- docs/snippets/components/AspireApp/WorkerService/Properties/launchSettings.json
- docs/snippets/components/AspireApp/WorkerService/Worker.cs
- docs/snippets/components/AspireApp/WorkerService/WorkerService.csproj
- docs/snippets/components/AspireApp/WorkerService/appsettings.Development.json
- docs/snippets/components/AspireApp/WorkerService/appsettings.json
- Add AppHost details to the components article
- Add snippets directory with CI-buildable example code
Fixes #4
---
|:--|:--|
| [docs/app-host-overview.md](https://github.com/dotnet/docs-aspire/blob/b455bd70eba3e28e452d4a754ceaced725e487bb/docs/app-host-overview.md) | [.NET Aspire orchestration overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/app-host-overview?branch=pr-en-us-129) |
| [docs/components-overview.md](https://github.com/dotnet/docs-aspire/blob/b455bd70eba3e28e452d4a754ceaced725e487bb/docs/components-overview.md) | [.NET Aspire components overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/components-overview?branch=pr-en-us-129) |
| [docs/database/postgresql-component.md](https://github.com/dotnet/docs-aspire/blob/b455b …
> Add AppHost details to the components article

- docs/deployment/k8s-deployment.md
Fix typos and grammar in k8s deployment documentation
---
|:--|:--|
| [docs/deployment/k8s-deployment.md](https://github.com/dotnet/docs-aspire/blob/9ac0c78e956e209055f90293f2a055679e2cba17/docs/deployment/k8s-deployment.md) | [Deploy .NET Aspire apps to a Kubernetes cluster](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/k8s-deployment?branch=pr-en-us-152) |
> Fix typos and grammar in k8s deployment documentation

- docs/database/azure-cosmos-db-component.md
Docs are incorrect. There is no AddDatabase(...) method on the Cosmos resource builder.
Removed reference to the extension method.
Fixes #154 
---
|:--|:--|
| [docs/database/azure-cosmos-db-component.md](https://github.com/dotnet/docs-aspire/blob/7b81dbbd8c829ef623067ed200bc1dfd2506c169/docs/database/azure-cosmos-db-component.md) | [.NET Aspire Azure Cosmos DB component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/azure-cosmos-db-component?branch=pr-en-us-155) |
> Remove AddDatabase from Cosmos DB resource.

- .github/workflows/merge-main-to-live.yml
Explicit handling of no commits. See the [`go-live`](https://github.com/dotnet/docs-aspire/actions/workflows/merge-main-to-live.yml) workflow errors...
Related to #149
> Explicit handling of no commits

- docs/caching/caching-components.md
- docs/caching/stackexchange-redis-component.md
- docs/caching/stackexchange-redis-distributed-caching-component.md
- docs/caching/stackexchange-redis-output-caching-component.md
- docs/database/mongodb-component.md
- docs/database/mysql-component.md
- docs/database/postgresql-component.md
- docs/database/postgresql-entity-framework-component.md
- docs/database/snippets/tutorial/aspiresqlefcore/AspireSQLEFCore.AppHost/Program.cs
- docs/database/sql-server-component.md
- docs/database/sql-server-entity-framework-component.md
- docs/deployment/azure/aca-deployment-azd-in-depth.md
- docs/deployment/azure/application-insights.md
- docs/deployment/manifest-format.md
- docs/fundamentals/app-host-overview.md
- docs/fundamentals/components-overview.md
- docs/fundamentals/snippets/components/AspireApp/AspireApp.AppHost/Program.cs
- docs/get-started/aspire-overview.md
- docs/get-started/build-your-first-aspire-app.md
- docs/get-started/snippets/quickstart/AspireSample/AspireSample.AppHost/Program.cs
- docs/messaging/rabbitmq-client-component.md
It isn't recommended to use the "AddXYZContainer" methods, but instead just "AddXYZ". Using the Container methods means that you want a container even after publishing to a cloud service, which has hosted versions of these resources.
Contributes to https://github.com/dotnet/aspire/issues/1528
---
|:--|:--|
| [docs/caching/caching-components.md](https://github.com/dotnet/docs-aspire/blob/0090eb1f0bdabcb7f625a5dcdc412892f5a37ede/docs/caching/caching-components.md) | [Tutorial: Implement caching with .NET Aspire components](https://review.learn.microsoft.com/en-us/dotnet/aspire/caching/caching-components?branch=pr-en-us-274) |
| [docs/caching/stackexchange-redis-component.md](https://github.co …
> Remove Container methods from AppHost docs

- docs/fundamentals/dashboard.md
`resourcece` => `resource`
---
|:--|:--|
| [docs/fundamentals/dashboard.md](https://github.com/dotnet/docs-aspire/blob/b9bdb70050eadbca5abcf67993c67b1aac8a20fe/docs/fundamentals/dashboard.md) | [.NET Aspire dashboard overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard?branch=pr-en-us-350) |
> Fix typo in dashboard docs

- docs/get-started/snippets/quickstart/AspireSample/AspireSample.Web/Program.cs
removes the static keyword from HttpClient lambda in the Web project to align with the [latest version of the starter project template](https://github.com/dotnet/aspire/blob/f2d158bf2b02e370a6c0714313823e5a612ab962/src/Aspire.ProjectTemplates/templates/aspire-starter/AspireStarterApplication.1.Web/Program.cs#L20-L24)
> removing static keyword from HttpClient lambda

- docs/get-started/build-your-first-aspire-app.md
Fixes #364 
---
|:--|:--|
| [docs/get-started/build-your-first-aspire-app.md](https://github.com/dotnet/docs-aspire/blob/ab98909a385e40386c63f8d912ff68e3b23cfd54/docs/get-started/build-your-first-aspire-app.md) | [Quickstart: Build your first .NET Aspire app](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/build-your-first-aspire-app?branch=pr-en-us-363) |
> reorder quickstart

- docs/deployment/manifest-format.md
- docs/fundamentals/app-host-overview.md
- docs/fundamentals/snippets/networking/Networking.AppHost/Program.ContainerPort.cs
- docs/fundamentals/snippets/networking/Networking.AppHost/Program.EnvVarPort.cs
- docs/fundamentals/snippets/networking/Networking.AppHost/Program.HostPortAndRandomPort.cs
- docs/fundamentals/snippets/networking/Networking.AppHost/Program.OmitHostPort.cs
- docs/fundamentals/snippets/networking/Networking.AppHost/Program.WithLaunchProfile.cs
- docs/fundamentals/snippets/networking/Networking.AppHost/Program.WithReplicas.cs
- docs/service-discovery/overview.md
Remove obsolete APIs, still waiting on `xref` indexing.
Fixes #388
---
|:--|:--|
| [docs/deployment/manifest-format.md](https://github.com/dotnet/docs-aspire/blob/fcec0ad24670f1afde15d356a33c96ce8281952e/docs/deployment/manifest-format.md) | [.NET Aspire manifest format for deployment tool builders](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/manifest-format?branch=pr-en-us-389) |
| [docs/fundamentals/app-host-overview.md](https://github.com/dotnet/docs-aspire/blob/fcec0ad24670f1afde15d356a33c96ce8281952e/docs/fundamentals/app-host-overview.md) | [.NET Aspire orchestration overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/app-host-overview?branch=pr-en-us-389) |
| …
> Remove obsolete APIs

- docs/fundamentals/networking-overview.md
- docs/fundamentals/snippets/networking/Networking.ApiService/Networking.ApiService.csproj
- docs/fundamentals/snippets/networking/Networking.ApiService/Networking.ApiService.http
- docs/fundamentals/snippets/networking/Networking.ApiService/Program.cs
- docs/fundamentals/snippets/networking/Networking.ApiService/Properties/launchSettings.json
- docs/fundamentals/snippets/networking/Networking.ApiService/appsettings.Development.json
- docs/fundamentals/snippets/networking/Networking.ApiService/appsettings.json
- docs/fundamentals/snippets/networking/Networking.AppHost/Networking.AppHost.csproj
- docs/fundamentals/snippets/networking/Networking.AppHost/Program.WithEndpoint.cs
- docs/fundamentals/snippets/networking/Networking.AppHost/Program.cs
- docs/fundamentals/snippets/networking/Networking.Frontend/Networking.Frontend/Components/Pages/Weather.razor
- docs/fundamentals/snippets/networking/Networking.Frontend/Networking.Frontend/Networking.Frontend.csproj
- docs/fundamentals/snippets/networking/Networking.Frontend/Networking.Frontend/Program.cs
- docs/fundamentals/snippets/networking/Networking.Frontend/Networking.Frontend/WeatherApiClient.cs
- docs/fundamentals/snippets/networking/Networking.ServiceDefaults/Extensions.cs
- docs/fundamentals/snippets/networking/Networking.ServiceDefaults/Networking.ServiceDefaults.csproj
- docs/fundamentals/snippets/networking/networking.sln
Add content for the `WithEndpoint` that exposes the callback delegate. Also, ensure the networking article uses the `WithHttpEndpoint` and `WithHttpsEndpoint` APIs.
Fixes #426
---
|:--|:--|
| [docs/fundamentals/networking-overview.md](https://github.com/dotnet/docs-aspire/blob/c24e0783b5dab27a04c317ee2adccb23f6d73ee8/docs/fundamentals/networking-overview.md) | [.NET Aspire inner-loop networking overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/networking-overview?branch=pr-en-us-472) |
> Add content covering `WithEndpoint` and the `callback` delegate.

- .github/workflows/quest-bulk.yml
- .github/workflows/quest.yml
GitHub permissions are ANDed, not ORed. So, even though the sequester app was given permission to read and write pull requests, the configuration in YAML prevented it.
This ensures that if a PR is tagged as a work item, it will be imported correctly.
> Add write permissions for pull requests

- docs/diagnostics/overview.md
- docs/toc.yml
Add diagnostics overview page.
Fixes #521
---
|:--|:--|
| [docs/diagnostics/overview.md](https://github.com/dotnet/docs-aspire/blob/30a75a32da4269293e8f2c155ba736fcc9238713/docs/diagnostics/overview.md) | [.NET Aspire diagnostics overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/diagnostics/overview?branch=pr-en-us-543) |
> Add diagnostics overview page

- docs/deployment/manifest-format.md
- docs/index.yml
- docs/toc.yml
- docs/troubleshooting/allow-unsecure-transport.md
- Add article for allowing unsecure transports.
- Update TOC to include new article and missing messaging article.
- Add to the manifest tooling article an example of a launch profile for generating the manifest.
Fixes #551
---
|:--|:--|
| [docs/deployment/manifest-format.md](https://github.com/dotnet/docs-aspire/blob/7650b6bf949b02affc3a8e5e67f8bb3a67eada36/docs/deployment/manifest-format.md) | [.NET Aspire manifest format for deployment tool builders](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/manifest-format?branch=pr-en-us-562) |
| [docs/troubleshooting/allow-unsecure-transport.md](https://github.com/dotnet/docs-aspire/blob/7650b6bf949b02affc3a8e5e67f8bb3a67eada36/docs/troubleshooting/allow-unsecure-transport.md) | [Allow unsecure …
> Add new article to fix #551

- .github/workflows/markdownlint.yml
- docs/fundamentals/health-checks.md
- docs/fundamentals/snippets/healthz/Healthz.ServiceDefaults/Extensions.cs
- docs/fundamentals/snippets/healthz/Healthz.ServiceDefaults/Healthz.ServiceDefaults.csproj
- docs/fundamentals/snippets/healthz/Healthz.ServiceDefaults/healthz.sln
- docs/whats-new/preview-5.md
Update health checks content to include details about environments, and recommendations.
Fixes #539
---
|:--|:--|
| [docs/fundamentals/health-checks.md](https://github.com/dotnet/docs-aspire/blob/141b4face39e2026123877b89da1bfe4a70c87f5/docs/fundamentals/health-checks.md) | [Health checks in .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/health-checks?branch=pr-en-us-563) |
| [docs/whats-new/preview-5.md](https://github.com/dotnet/docs-aspire/blob/141b4face39e2026123877b89da1bfe4a70c87f5/docs/whats-new/preview-5.md) | [.NET Aspire preview 5](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/preview-5?branch=pr-en-us-563) |
> Add healthz details

- docs/fundamentals/service-defaults.md
- docs/fundamentals/snippets/params/Parameters.ServiceDefaults/Extensions.cs
- docs/fundamentals/snippets/template/YourAppName/Extensions.cs
Update the documentation to use built-in OpenTelemetry instrumentation.
See https://github.com/dotnet/aspire/pull/2900.
---
|:--|:--|
| [docs/fundamentals/service-defaults.md](https://github.com/dotnet/docs-aspire/blob/7fc003425f3a76cba6ec07cf6b1464b677d710a3/docs/fundamentals/service-defaults.md) | [.NET Aspire service defaults](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/service-defaults?branch=pr-en-us-518) |
> Remove AddBuiltInMeters()

- docs/fundamentals/networking-overview.md
Corrected a minor typo in the port numbers at the end of the Ports and proxies section: The diagram shows port 5067, the description said 5607, corrected to 5067 to match the diagram.
---
|:--|:--|
| [docs/fundamentals/networking-overview.md](https://github.com/dotnet/docs-aspire/blob/0144745c0f158cdbe908e4b297038bedd0a81f54/docs/fundamentals/networking-overview.md) | [.NET Aspire inner-loop networking overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/networking-overview?branch=pr-en-us-573) |
> Corrected port number description to match associated diagram

- docs/whats-new/preview-5.md
@IEvangelist some more updates for P5.
---
|:--|:--|
| [docs/whats-new/preview-5.md](https://github.com/dotnet/docs-aspire/blob/56c96c5fbf5e97a2df32942524964e2aca65c830/docs/whats-new/preview-5.md) | [.NET Aspire preview 5](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/preview-5?branch=pr-en-us-596) |
> More P5 updates across Azure, AppModel and manifest.

- docs/deployment/azure/application-insights.md
Correct NuGet package for App Insights.
Fixes #649
---
|:--|:--|
| [docs/deployment/azure/application-insights.md](https://github.com/dotnet/docs-aspire/blob/ff6fe1f6324ebf875494ada61892cdca3fca69b4/docs/deployment/azure/application-insights.md) | [Use Application Insights for .NET Aspire telemetry](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/application-insights?branch=pr-en-us-651) |
> Correct NuGet package

- docs/fundamentals/app-host-overview.md
- docs/fundamentals/networking-overview.md
- docs/get-started/build-aspire-apps-with-nodejs.md
Fix the env var format for service endpoints. /cc @ReubenBond 
Fixes #704
---
|:--|:--|
| [docs/fundamentals/app-host-overview.md](https://github.com/dotnet/docs-aspire/blob/07182aae5fed72c9129a74372b7ee985d5fd5a6c/docs/fundamentals/app-host-overview.md) | [.NET Aspire orchestration overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/app-host-overview?branch=pr-en-us-705) |
| [docs/fundamentals/networking-overview.md](https://github.com/dotnet/docs-aspire/blob/07182aae5fed72c9129a74372b7ee985d5fd5a6c/docs/fundamentals/networking-overview.md) | [.NET Aspire inner loop networking overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/networking-overview?branch=pr-en-us-705) |
| …
> Fix the env var format for service endpoints

- docs/diagnostics/overview.md
In Aspire 8.0 preview 5+ we changed the analytics code from ASPIRE0001 to AZPROVISION001.
---
|:--|:--|
| [docs/diagnostics/overview.md](https://github.com/dotnet/docs-aspire/blob/ae28abbe2da736919edba137a59a55173193b614/docs/diagnostics/overview.md) | [.NET Aspire diagnostics overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/diagnostics/overview?branch=pr-en-us-709) |
> ASPIRE0001 --> AZPROVISION001

- docs/get-started/build-aspire-apps-with-nodejs.md
Fixed: Changed spelling from `Dockefile ` to `Dockerfile`
---
|:--|:--|
| [docs/get-started/build-aspire-apps-with-nodejs.md](https://github.com/dotnet/docs-aspire/blob/09a7b8e9e0f7c39a00a8143781099c9ad960fd2f/docs/get-started/build-aspire-apps-with-nodejs.md) | [Build .NET Aspire apps with Node.js](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/build-aspire-apps-with-nodejs?branch=pr-en-us-785) |
> nit: fixed spelling

- docs/azureai/azureai-search-document-component.md
Fixes #822
Added the `.` to .NET
---
|:--|:--|
| [docs/azureai/azureai-search-document-component.md](https://github.com/dotnet/docs-aspire/blob/aaa47ddcfa533056fe2c1c2a0a0c08c61f259086/docs/azureai/azureai-search-document-component.md) | [.NET Aspire Azure AI Search Documents component](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-search-document-component?branch=pr-en-us-824) |
> Fix ".NET" usage in Azure AI Search page

- docs/azureai/azureai-openai-component.md
- docs/azureai/azureai-search-document-component.md
- docs/caching/stackexchange-redis-component.md
- docs/caching/stackexchange-redis-distributed-caching-component.md
- docs/caching/stackexchange-redis-output-caching-component.md
- docs/database/azure-cosmos-db-component.md
- docs/database/azure-cosmos-db-entity-framework-component.md
- docs/database/mongodb-component.md
- docs/database/mysql-component.md
- docs/database/mysql-entity-framework-component.md
- docs/database/oracle-entity-framework-component.md
- docs/database/postgresql-component.md
- docs/database/postgresql-entity-framework-component.md
- docs/database/sql-server-component.md
- docs/database/sql-server-entity-framework-component.md
- docs/fundamentals/components-overview.md
- docs/fundamentals/health-checks.md
- docs/logging/seq-component.md
- docs/messaging/azure-event-hubs-component.md
- docs/messaging/azure-service-bus-component.md
- docs/messaging/kafka-component.md
- docs/messaging/nats-component.md
- docs/messaging/rabbitmq-client-component.md
- docs/security/azure-security-key-vault-component.md
- docs/storage/azure-storage-blobs-component.md
- docs/storage/azure-storage-queues-component.md
- docs/storage/azure-storage-tables-component.md
- Fixes #842
- Fixes #853
---
|:--|:--|
| [docs/azureai/azureai-openai-component.md](https://github.com/dotnet/docs-aspire/blob/3dd98d00f6295a9d036113d01962b8f4eb2d53a6/docs/azureai/azureai-openai-component.md) | [.NET Aspire Azure AI OpenAI component](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-openai-component?branch=pr-en-us-846) |
| [docs/azureai/azureai-search-document-component.md](https://github.com/dotnet/docs-aspire/blob/3dd98d00f6295a9d036113d01962b8f4eb2d53a6/docs/azureai/azureai-search-document-component.md) | [NET Aspire Azure AI Search Documents component](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-search-document-componen …
> Update code samples to reflect API changes in preview-7

- docs/fundamentals/dashboard/explore.md
Fix dashboard login verbiage.
Fixes #809
---
|:--|:--|
| [docs/fundamentals/dashboard/explore.md](https://github.com/dotnet/docs-aspire/blob/8c079039e87741042a7180d11b6d8b9991f937f8/docs/fundamentals/dashboard/explore.md) | [Explore the .NET Aspire dashboard](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/explore?branch=pr-en-us-864) |
> Fix dashboard login verbiage

- docs/caching/caching-components.md
Updates AppHost cache code and adds a new required step for the hosting package
Fixes #857
---
|:--|:--|
| [docs/caching/caching-components.md](https://github.com/dotnet/docs-aspire/blob/6a6e77a6725b7a559ab35a58069a67af0af3ed8d/docs/caching/caching-components.md) | [Tutorial: Implement caching with .NET Aspire components](https://review.learn.microsoft.com/en-us/dotnet/aspire/caching/caching-components?branch=pr-en-us-875) |
> Caching tutorial fixes

- docs/get-started/build-your-first-aspire-app.md
Highlight the correct line in the code snippet
---
|:--|:--|
| [docs/get-started/build-your-first-aspire-app.md](https://github.com/dotnet/docs-aspire/blob/978e6d1484a974ba348a7ab47737f2ad2754b7eb/docs/get-started/build-your-first-aspire-app.md) | [Quickstart: Build your first .NET Aspire app](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/build-your-first-aspire-app?branch=pr-en-us-884) |
> Update build-your-first-aspire-app.md to highlight the correct line

- docs/frameworks/dapr.md
Add an intro to the new doc for using Dapr with .NET Aspire.
Partially fixes #534 
Related PR: #894 
---
|:--|:--|
| [docs/frameworks/dapr.md](https://github.com/dotnet/docs-aspire/blob/0681b4baa3ff135871cabc83289911ccc3b50f6c/docs/frameworks/dapr.md) | [Use Dapr with .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/frameworks/dapr?branch=pr-en-us-902) |
> Intro to the Dapr/Aspire doc

- docs/fundamentals/setup-tooling.md
- docs/get-started/build-your-first-aspire-app.md
- docs/toc.yml
- docs/troubleshooting/unable-to-install-workload.md
- docs/troubleshooting/untrusted-localhost-certificate.md
Add a few troubleshooting bits.
- Fixes #837
- Fixes #845
---
|:--|:--|
| [docs/fundamentals/setup-tooling.md](https://github.com/dotnet/docs-aspire/blob/a13283d12e4067dd0382756e27324ef59bcbb893/docs/fundamentals/setup-tooling.md) | [.NET Aspire setup and tooling](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/setup-tooling?branch=pr-en-us-900) |
| [docs/get-started/build-your-first-aspire-app.md](https://github.com/dotnet/docs-aspire/blob/a13283d12e4067dd0382756e27324ef59bcbb893/docs/get-started/build-your-first-aspire-app.md) | [Quickstart: Build your first .NET Aspire app](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/build-your-first-aspire-app?branch=pr-en-us-900) |
| …
> Troubleshooting bits

- docs/database/sql-server-component-deployment.md
- docs/deployment/azure/aca-deployment.md
- docs/deployment/azure/includes/azd-up-workflow.md
- docs/deployment/azure/includes/init-workflow.md
Update init and up workflows to the latest 
Fixes #926
---
|:--|:--|
| [docs/database/sql-server-component-deployment.md](https://github.com/dotnet/docs-aspire/blob/7569d0827ac79c0a66fdd11929aa09f9bd86e9a9/docs/database/sql-server-component-deployment.md) | [Tutorial: Deploy a .NET Aspire app with a SQL Server Database to Azure](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/sql-server-component-deployment?branch=pr-en-us-930) |
| [docs/deployment/azure/aca-deployment.md](https://github.com/dotnet/docs-aspire/blob/7569d0827ac79c0a66fdd11929aa09f9bd86e9a9/docs/deployment/azure/aca-deployment.md) | [Deploy .NET Aspire apps to Azure Container Apps](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment?branch=pr-en-u …
> Updated init steps and up workflow

- docs/extensibility/custom-resources.md
- docs/frameworks/orleans.md
- docs/fundamentals/components-overview.md
- docs/fundamentals/external-parameters.md
- docs/index.yml
- docs/toc.yml
Rework TOC, fixes #880.
https://github.com/dotnet/docs-aspire/assets/7679720/18a5bad7-8c4b-48c1-8e55-bbc108328af2
---
|:--|:--|
| [docs/extensibility/custom-resources.md](https://github.com/dotnet/docs-aspire/blob/d83a9e9c60186a50b1e2b99bec36eb86c347d188/docs/extensibility/custom-resources.md) | [Create custom resource types for .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/extensibility/custom-resources?branch=pr-en-us-928) |
| [docs/frameworks/orleans.md](https://github.com/dotnet/docs-aspire/blob/d83a9e9c60186a50b1e2b99bec36eb86c347d188/docs/frameworks/orleans.md) | [Use Orleans with .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/frameworks/orleans?branch=pr-en-us-928) |
| …
> Rework TOC

- docs/extensibility/custom-resources.md
Fixes some minor issues in the custom resources doc observed while watching https://www.youtube.com/watch?v=4rVrR9haWlg
---
|:--|:--|
| [docs/extensibility/custom-resources.md](https://github.com/dotnet/docs-aspire/blob/e16f9b7f8cd82886c64099695ffeed77b6effcfc/docs/extensibility/custom-resources.md) | [Create custom resource types for .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/extensibility/custom-resources?branch=pr-en-us-934) |
> Fix typos in Update custom-resources.md

- docs/frameworks/dapr.md
Per @philliphoff review in dotnet/docs-aspire#894
Fixes #534
---
|:--|:--|
| [docs/frameworks/dapr.md](https://github.com/dotnet/docs-aspire/blob/925a4806f6c0c05e73e137edb13bf2e3a75b20f3/docs/frameworks/dapr.md) | [Use Dapr with .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/frameworks/dapr?branch=pr-en-us-939) |
> [Dapr] Small updates to content

- docs/fundamentals/dashboard/configuration.md
- docs/fundamentals/dashboard/overview.md
- docs/fundamentals/dashboard/security-considerations.md
Add missing image updates. Related to #941
---
|:--|:--|
| [docs/fundamentals/dashboard/configuration.md](https://github.com/dotnet/docs-aspire/blob/a5438c3fd7b6357e12c364c5b57fe347eb09553a/docs/fundamentals/dashboard/configuration.md) | [Dashboard configuration](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/configuration?branch=pr-en-us-942) |
| [docs/fundamentals/dashboard/overview.md](https://github.com/dotnet/docs-aspire/blob/a5438c3fd7b6357e12c364c5b57fe347eb09553a/docs/fundamentals/dashboard/overview.md) | [.NET Aspire dashboard overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/overview?branch=pr-en-us-942) |
| [docs/fundamentals/dashboard/security-considerations.md](https://github.com/d …
> Add missing image updates

- docs/deployment/azure/aca-deployment-azd-in-depth.md
Assed missing '--output-path' parameter from dotnet cli command under point 1 of 'How Azure Developer CLI integration works' section
---
|:--|:--|
| [docs/deployment/azure/aca-deployment-azd-in-depth.md](https://github.com/dotnet/docs-aspire/blob/aecc13ee479dadec62551b8fbe4fb7af683134da/docs/deployment/azure/aca-deployment-azd-in-depth.md) | [Deploy a .NET Aspire app to Azure Container Apps using the Azure Developer CLI (in-depth guide)](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-azd-in-depth?branch=pr-en-us-973) |
> Update aca-deployment-azd-in-depth.md - Add missing dotnet cli command argument

- docs/database/qdrant-component.md
The command to install `Aspire.Qdrant.Client` installed `Qdrant.Client`.  
---
|:--|:--|
| [docs/database/qdrant-component.md](https://github.com/dotnet/docs-aspire/blob/468220498daf2e89710d06d1121166e4f9a42467/docs/database/qdrant-component.md) | [.NET Aspire Qdrant component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/qdrant-component?branch=pr-en-us-969) |
> Fix wrong nuget package in installation documentation.

- docs/get-started/aspire-overview.md
Hey! I was just reading up on Aspire and noticed this small typo.
---
|:--|:--|
| [docs/get-started/aspire-overview.md](https://github.com/dotnet/docs-aspire/blob/41fe63700d9c32fa7363db668beac2cf3bc72a29/docs/get-started/aspire-overview.md) | [.NET Aspire overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/aspire-overview?branch=pr-en-us-979) |
> Fixes typo in .NET Aspire Overview

- docs/fundamentals/app-host-overview.md
- docs/fundamentals/components-overview.md
- docs/fundamentals/service-defaults.md
- docs/get-started/aspire-overview.md
Help more clearly define local dev.
Fixes #937
---
|:--|:--|
| [docs/fundamentals/app-host-overview.md](https://github.com/dotnet/docs-aspire/blob/1e2db48a39d900b1d90605fc683cf87024549188/docs/fundamentals/app-host-overview.md) | [.NET Aspire orchestration overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/app-host-overview?branch=pr-en-us-968) |
| [docs/fundamentals/components-overview.md](https://github.com/dotnet/docs-aspire/blob/1e2db48a39d900b1d90605fc683cf87024549188/docs/fundamentals/components-overview.md) | [.NET Aspire components overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/components-overview?branch=pr-en-us-968) |
| [docs/fundamentals/service-defaults.md](https://github.com/dotnet/docs-aspir …
> Help more clearly define local dev.

- docs/extensibility/custom-resources.md
Add a few bits about HTTPS.
Fixes #977
---
|:--|:--|
| [docs/extensibility/custom-resources.md](https://github.com/dotnet/docs-aspire/blob/74ab64ba4626cecf9b0a9ee5bf8f3dce925a4132/docs/extensibility/custom-resources.md) | [Create custom resource types for .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/extensibility/custom-resources?branch=pr-en-us-1007) |
> Add a few bits about HTTPS

- docs/logging/seq-component.md
Clean up and fix Seq doc issues
Fixes #1001
---
|:--|:--|
| [docs/logging/seq-component.md](https://github.com/dotnet/docs-aspire/blob/bb1f64932933e914a809481fe744bda04286ac93/docs/logging/seq-component.md) | [.NET Aspire Seq component](https://review.learn.microsoft.com/en-us/dotnet/aspire/logging/seq-component?branch=pr-en-us-1008) |
> Clean up and fix Seq doc issues

- docs/deployment/azure/aca-deployment-github-actions.md
- docs/includes/clean-up-resources.md
Add link to supporting content for `az group delete` and help macOS users create _.github_.
Fixes #972
---
|:--|:--|
| [docs/deployment/azure/aca-deployment-github-actions.md](https://github.com/dotnet/docs-aspire/blob/a9343b7f4167293b920fb9c413de0e5c95f02dc4/docs/deployment/azure/aca-deployment-github-actions.md) | [Tutorial: Deploy a .NET Aspire app using the Azure Developer CLI and GitHub Actions](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-github-actions?branch=pr-en-us-1018) |
> Add link to supporting content for `az group delete` and help macOS users create .github

- docs/deployment/azure/local-provisioning.md
The docs are wrong, currently. See the corresponding code: https://github.com/dotnet/aspire/blob/26742d30609f8a96c6eb41aa80f64496bb158ea6/src/Aspire.Hosting.Azure/Provisioning/AzureProvisionerOptions.cs#L23-L27
---
|:--|:--|
| [docs/deployment/azure/local-provisioning.md](https://github.com/dotnet/docs-aspire/blob/b5d0c232aa53e67736bf0ac1392716e32f833597/docs/deployment/azure/local-provisioning.md) | [Local Azure provisioning](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/local-provisioning?branch=pr-en-us-1021) |
> Fix AzureProvisioner config docs

- docs/get-started/add-aspire-existing-app.md
Remove .NET CLI command that was mistakenly included.
Fixes #1027
---
|:--|:--|
| [docs/get-started/add-aspire-existing-app.md](https://github.com/dotnet/docs-aspire/blob/06e2ed65989989f6acfc3a031ac25b3c46c45399/docs/get-started/add-aspire-existing-app.md) | [Tutorial: Add .NET Aspire to an existing .NET app](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/add-aspire-existing-app?branch=pr-en-us-1032) |
> Remove .NET CLI command that was mistakenly included.

- docs/fundamentals/app-host-overview.md
Add details about container runtime args.
Fixes #707
---
|:--|:--|
| [docs/fundamentals/app-host-overview.md](https://github.com/dotnet/docs-aspire/blob/d39e31abfe9d1ea037de640a125eaa537ad39231/docs/fundamentals/app-host-overview.md) | [.NET Aspire orchestration overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/app-host-overview?branch=pr-en-us-1033) |
> Add details about container runtime args.

- docs/index.yml
- docs/toc.yml
- docs/troubleshooting/name-is-already-in-use.md
Add troubleshooting for name in use.
Fixes #681
---
|:--|:--|
| [docs/troubleshooting/name-is-already-in-use.md](https://github.com/dotnet/docs-aspire/blob/29709af8a42eb4d96bf31ec4836d6011db455bea/docs/troubleshooting/name-is-already-in-use.md) | [The specified name is already in use](https://review.learn.microsoft.com/en-us/dotnet/aspire/troubleshooting/name-is-already-in-use?branch=pr-en-us-1037) |
> Add troubleshooting for name in use.

- docs/database/includes/postgresql-explicit-username-password.md
- docs/database/mysql-component.md
- docs/database/oracle-entity-framework-component.md
- docs/database/postgresql-component.md
- docs/database/postgresql-entity-framework-component.md
- docs/database/qdrant-component.md
- docs/database/sql-server-component.md
- docs/messaging/rabbitmq-client-component.md
Adds parameters to app host usage examples, where applicable.
Fixes #1009
---
|:--|:--|
| [docs/database/mysql-component.md](https://github.com/dotnet/docs-aspire/blob/3c20ed335be0930b260c7a12824e3624578935ff/docs/database/mysql-component.md) | [.NET Aspire MySQL database component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/mysql-component?branch=pr-en-us-1035) |
| [docs/database/oracle-entity-framework-component.md](https://github.com/dotnet/docs-aspire/blob/3c20ed335be0930b260c7a12824e3624578935ff/docs/database/oracle-entity-framework-component.md) | [Oracle Entity Framework Component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/oracle-entity-framework-component?branch=pr-en-us-1035) |
| …
> Adds parameters to app host usage examples, where applicable

- docs/fundamentals/health-checks.md
Add info about required middleware to health checks. 
Fixes #680
---
|:--|:--|
| [docs/fundamentals/health-checks.md](https://github.com/dotnet/docs-aspire/blob/ae4f4a774e10d17b0f12c76b6f9cd169c4656a62/docs/fundamentals/health-checks.md) | [Health checks in .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/health-checks?branch=pr-en-us-1036) |
> Add info about required middleware to health checks.

- docs/security/azure-security-key-vault-component.md
The current documentation is out of date. Updating to match current APIs and behavior.
Related to #1041
---
|:--|:--|
| [docs/security/azure-security-key-vault-component.md](https://github.com/dotnet/docs-aspire/blob/47d6dd102c0ab5365171dcfc2aa671c906435f66/docs/security/azure-security-key-vault-component.md) | [.NET Aspire Azure Key Vault component](https://review.learn.microsoft.com/en-us/dotnet/aspire/security/azure-security-key-vault-component?branch=pr-en-us-1042) |
> Update KeyVault usage documentation

- docs/frameworks/dapr.md
- docs/frameworks/snippets/Dapr/Dapr.AppHost/Program.cs
- docs/frameworks/snippets/Dapr/Dapr.Web/Dapr.Web.csproj
- docs/frameworks/snippets/Dapr/Dapr.Web/Program.cs
- docs/frameworks/snippets/Dapr/Dapr.Web/WeatherApiClient.cs
Address Dapr feedback. 
Fixes #947
---
|:--|:--|
| [docs/frameworks/dapr.md](https://github.com/dotnet/docs-aspire/blob/c7b4b02e52102b4eb068c8dcda7e0071d95fc3b2/docs/frameworks/dapr.md) | [Use Dapr with .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/frameworks/dapr?branch=pr-en-us-1038) |
> Address Dapr feedback.

- docs/storage/azure-storage-components.md
Minor clean up and verify that this fixed #719.
---
|:--|:--|
| [docs/storage/azure-storage-components.md](https://github.com/dotnet/docs-aspire/blob/4358db70b70ff0e93eee1ea8abd972dad4639c17/docs/storage/azure-storage-components.md) | [Tutorial: Connect an ASP.NET Core app to .NET Aspire storage components](https://review.learn.microsoft.com/en-us/dotnet/aspire/storage/azure-storage-components?branch=pr-en-us-1045) |
> Minor clean up

- docs/caching/caching-components.md
Update AppHost package install bits, verified it's correct.
Fixes #717
---
|:--|:--|
| [docs/caching/caching-components.md](https://github.com/dotnet/docs-aspire/blob/a87485ade66cec67a67cee70749649a80b15edc1/docs/caching/caching-components.md) | [Tutorial: Implement caching with .NET Aspire components](https://review.learn.microsoft.com/en-us/dotnet/aspire/caching/caching-components?branch=pr-en-us-1044) |
> Update and correct hosting bits.

- docs/deployment/azure/local-provisioning.md
Make the JSON valid, remove the squiggly
---
|:--|:--|
| [docs/deployment/azure/local-provisioning.md](https://github.com/dotnet/docs-aspire/blob/f217872a64d3f3f2e19c942e29f1bb77902d6224/docs/deployment/azure/local-provisioning.md) | [Local Azure provisioning](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/local-provisioning?branch=pr-en-us-1061) |
> Remove invalid trailing comma in config example

- docs/caching/caching-components-deployment.md
- docs/caching/caching-components.md
- docs/caching/includes/redis-app-host.md
- docs/caching/stackexchange-redis-caching-overview.md
- docs/caching/stackexchange-redis-caching.md
- docs/caching/stackexchange-redis-component.md
- docs/caching/stackexchange-redis-distributed-caching-component.md
- docs/caching/stackexchange-redis-output-caching-component.md
- docs/index.yml
- docs/toc.yml
- docs/whats-new/dotnet-docs-aspire-mod1.md
- docs/whats-new/dotnet-docs-aspire-mod2.md
- Add an overview of Stack Exchange Redis caching.
- Add TOC entry, and update Hub page.
- Fix brand name, should always have a space when referring to it by name (excluding NuGet package or namespace refs).
Fixes #1051
---
|:--|:--|
| [docs/caching/caching-components-deployment.md](https://github.com/dotnet/docs-aspire/blob/a2c1fa1e7c2a6fad33bbb1bff4c3903bcac03eb9/docs/caching/caching-components-deployment.md) | [Tutorial: Deploy a .NET Aspire app with a Redis Cache to Azure](https://review.learn.microsoft.com/en-us/dotnet/aspire/caching/caching-components-deployment?branch=pr-en-us-1064) |
| [docs/caching/caching-components.md](https://github.com/dotnet/docs-aspire/blob/a2c1fa1e7c2a6fad33bbb1bff4c3903bcac03eb9/docs/caching/caching-components.md) | [Implement …
> Add an overview of Stack Exchange Redis caching

- docs/get-started/build-your-first-aspire-app.md
- docs/troubleshooting/untrusted-localhost-certificate.md
Add details about trusting dev-cert.
Fixes #1068
---
|:--|:--|
| [docs/get-started/build-your-first-aspire-app.md](https://github.com/dotnet/docs-aspire/blob/df2a3155ddfb08a604ad6ff9665e9a46ef09a98d/docs/get-started/build-your-first-aspire-app.md) | [Quickstart: Build your first .NET Aspire app](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/build-your-first-aspire-app?branch=pr-en-us-1087) |
| [docs/troubleshooting/untrusted-localhost-certificate.md](https://github.com/dotnet/docs-aspire/blob/df2a3155ddfb08a604ad6ff9665e9a46ef09a98d/docs/troubleshooting/untrusted-localhost-certificate.md) | [Troubleshoot untrusted localhost certificate in .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/troubleshooting/untrusted-localhost- …
> Add details about trusting dev-cert

- docs/fundamentals/health-checks.md
Fix output caching typos in the docs.
---
|:--|:--|
| [docs/fundamentals/health-checks.md](https://github.com/dotnet/docs-aspire/blob/0efc352bf49c03866f7617fbcbc876f4101aa383/docs/fundamentals/health-checks.md) | [Health checks in .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/health-checks?branch=pr-en-us-1091) |
> Fix OutputCache typos

- docs/caching/stackexchange-redis-distributed-caching-component.md
The instructions as provided don't work, because the reference used in App host didn't match that of the consumer. So I made them both "cache" for consistency.
See above.  Just a very minor edit to the instructions for the Aspire Stack Exchange Redis distributed caching.
---
|:--|:--|
| [docs/caching/stackexchange-redis-distributed-caching-component.md](https://github.com/dotnet/docs-aspire/blob/c30a42ea8a36fa58d188953eda21e2ea382999ef/docs/caching/stackexchange-redis-distributed-caching-component.md) | [.NET Aspire Stack Exchange Redis distributed caching component](https://review.learn.microsoft.com/en-us/dotnet/aspire/caching/stackexchange-redis-distributed-caching-component?branch=pr-en-us-1148) |
> Matched the App host Redis reference to the consuming project

- .github/workflows/dispatch-merge-main-to-live.yml
Add a manual merge from main to live. If we need to merge from `main` to `live` outside of the scheduled time, then I can simply start this action to run.
> Add a manual merge from main to live.

- docs/database/azure-cosmos-db-component.md
- docs/database/mysql-entity-framework-component.md
- docs/database/oracle-entity-framework-component.md
- docs/database/postgresql-component.md
- docs/database/postgresql-entity-framework-component.md
- docs/database/sql-server-component.md
- docs/database/sql-server-entity-framework-component.md
Add missing connection string sections.
Fixes #1165
---
|:--|:--|
| [docs/database/azure-cosmos-db-component.md](https://github.com/dotnet/docs-aspire/blob/8a1dd13a849237072c8387cdab2d326e41ff3286/docs/database/azure-cosmos-db-component.md) | [.NET Aspire Azure Cosmos DB component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/azure-cosmos-db-component?branch=pr-en-us-1170) |
| [docs/database/mysql-entity-framework-component.md](https://github.com/dotnet/docs-aspire/blob/8a1dd13a849237072c8387cdab2d326e41ff3286/docs/database/mysql-entity-framework-component.md) | [MySQL Entity Framework Component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/mysql-entity-framework-component?branch=pr-en-us-1170) |
| …
> Add missing connection string sections.

- docs/index.yml
- docs/toc.yml
- docs/troubleshooting/connection-string-missing.md
- docs/troubleshooting/container-runtime-unhealthy.md
Going through the CSS troubleshooters, it will take time to migrate them into the docs. Starting with the two easiest.
---
|:--|:--|
| [docs/troubleshooting/connection-string-missing.md](https://github.com/dotnet/docs-aspire/blob/d2d94703062a08ff1aa32a0fd855370f48132255/docs/troubleshooting/connection-string-missing.md) | [Connection string is missing](https://review.learn.microsoft.com/en-us/dotnet/aspire/troubleshooting/connection-string-missing?branch=pr-en-us-1249) |
| [docs/troubleshooting/container-runtime-unhealthy.md](https://github.com/dotnet/docs-aspire/blob/d2d94703062a08ff1aa32a0fd855370f48132255/docs/troubleshooting/container-runtime-unhealthy.md) | [Container runtime appears to be unhealthy](https://review.learn.microsoft.com/en-us/dotnet/aspire/tr …
> Add two troubleshooters

- docs/fundamentals/dashboard/configuration.md
Fixes https://github.com/dotnet/aspire/issues/4173
---
|:--|:--|
| [docs/fundamentals/dashboard/configuration.md](https://github.com/dotnet/docs-aspire/blob/461211b503b101e72ebb8ca2b48c458484806a87/docs/fundamentals/dashboard/configuration.md) | [Dashboard configuration](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/configuration?branch=pr-en-us-1252) |
> Dashboard telemetry limit scopes

- docs/deployment/azure/aca-deployment-github-actions.md
Add missing details about provisioning and deployment in separate jobs.
Fixes #1117
Tagging @vishipayyallore for visibility, thoughts on this PR.
---
|:--|:--|
| [docs/deployment/azure/aca-deployment-github-actions.md](https://github.com/dotnet/docs-aspire/blob/1eb4118026a9dff46a82c1f398dc848a8c86455a/docs/deployment/azure/aca-deployment-github-actions.md) | [Tutorial: Deploy a .NET Aspire project using the Azure Developer CLI and GitHub Actions](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-github-actions?branch=pr-en-us-1255) |
> Add missing details about provision.

- .github/workflows/check-for-build-warnings.yml
Remove explicit checkout of SHA, as it's not needed.
Fixes:
- https://github.com/ossf/scorecard/blob/main/docs/checks.md#dangerous-workflow
Related to #1345
> Remove explicit checkout of SHA, as it's not needed

- docs/fundamentals/app-host-overview.md
Was using old name. See https://github.com/dotnet/aspire/pull/3950
---
|:--|:--|
| [docs/fundamentals/app-host-overview.md](https://github.com/dotnet/docs-aspire/blob/bbb7259d671c971bca397ae0bfde9f564104d3ce/docs/fundamentals/app-host-overview.md) | [docs/fundamentals/app-host-overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/app-host-overview?branch=pr-en-us-1356) |
> WithContainerRunArgs --> WithContainerRuntimeArgs

- docs/extensibility/custom-resources.md
---
|:--|:--|
| [docs/extensibility/custom-resources.md](https://github.com/dotnet/docs-aspire/blob/53cee653f6edd06c77f06f3e31262afd1c5fe542/docs/extensibility/custom-resources.md) | [docs/extensibility/custom-resources](https://review.learn.microsoft.com/en-us/dotnet/aspire/extensibility/custom-resources?branch=pr-en-us-1368) |
> Fix missing word + couple typos

- docs/database/seed-database-data.md
Adjusting the code snippets display in the section "Database seeding examples". Starting when `mysql`, `sqlserver` and `postgres` really start, and ending after the `AddDatabase()` command.
---
|:--|:--|
| [docs/database/seed-database-data.md](https://github.com/dotnet/docs-aspire/blob/0c9ff1333270454dd5052eddc79c8962aad45c6b/docs/database/seed-database-data.md) | [docs/database/seed-database-data](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/seed-database-data?branch=pr-en-us-1373) |
> Adjust code snippets

- docs/messaging/nats-component.md
Contributes to dotnet/docs#41277.
---
|:--|:--|
| [docs/messaging/nats-component.md](https://github.com/dotnet/docs-aspire/blob/6f2ddf9f96eedd4d02d936aafd5164ea466d2e2b/docs/messaging/nats-component.md) | [docs/messaging/nats-component](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/nats-component?branch=pr-en-us-1385) |
> Fix nats link

- docs/fundamentals/networking-overview.md
Add a few more bits about the callback overload.
Fixes #1382
---
|:--|:--|
| [docs/fundamentals/networking-overview.md](https://github.com/dotnet/docs-aspire/blob/4922e3df4c3c8c2a6547c5a16fbf8b25554ec393/docs/fundamentals/networking-overview.md) | [docs/fundamentals/networking-overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/networking-overview?branch=pr-en-us-1413) |
> Add a few more bits about the callback overload.

- docs/database/mongodb-component.md
Close code sections to prevent the sections mixing
---
|:--|:--|
| [docs/database/mongodb-component.md](https://github.com/dotnet/docs-aspire/blob/210a4c34009457730374f8d8cb59782be10a23e7/docs/database/mongodb-component.md) | [docs/database/mongodb-component](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/mongodb-component?branch=pr-en-us-1439) |
> Fix code section closing tag

- docs/fundamentals/launch-profiles.md
- docs/fundamentals/networking-overview.md
- docs/fundamentals/snippets/networking/Networking.AppHost/Program.EndpointFilter.cs
- docs/fundamentals/snippets/networking/Networking.AppHost/Program.KestrelConfiguration.cs
- docs/fundamentals/snippets/networking/Networking.AppHost/Program.cs
- docs/fundamentals/snippets/networking/Networking.AppHost/Properties/launchSettings.json
- docs/fundamentals/snippets/networking/Networking.Frontend/Networking.Frontend/Program.cs
- docs/fundamentals/snippets/networking/Networking.Frontend/Networking.Frontend/Properties/launchSettings.json
- docs/fundamentals/snippets/networking/Networking.Frontend/Networking.Frontend/appsettings.Development.json
- docs/toc.yml
Networking refinements.
Fixes #1112
---
|:--|:--|
| [docs/fundamentals/launch-profiles.md](https://github.com/dotnet/docs-aspire/blob/0f61cab14ad7ad1bf22ad2b1288a99c797e777f7/docs/fundamentals/launch-profiles.md) | [docs/fundamentals/launch-profiles](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/launch-profiles?branch=pr-en-us-1440) |
| [docs/fundamentals/networking-overview.md](https://github.com/dotnet/docs-aspire/blob/0f61cab14ad7ad1bf22ad2b1288a99c797e777f7/docs/fundamentals/networking-overview.md) | [docs/fundamentals/networking-overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/networking-overview?branch=pr-en-us-1440) |
> Networking refinements

- docs/database/seed-database-data.md
Current version says that code should be added to the AppHost project.
`builder` there is `IDistributedApplicationBuilder` and has no such extensions in `Aspire.Npgsql.EntityFrameworkCore.PostgreSQL` package. There is also `.MapDefaultEndpoints()` call which is from `Aspire.ServiceDefaults` projects which is referenced by all API Service projects.
Not sure about the best project name though.
https://learn.microsoft.com/en-us/dotnet/aspire/database/postgresql-entity-framework-component?tabs=dotnet-cli
EF Core component says `consuming client project` instead the `API service project` I have used
> Change target for code sample

- .github/policies/auto-merge.yml
PRs from dependabot aren't getting auto-approved.
> Switch order of approve and auto-merge

- docs/messaging/azure-event-hubs-integration.md
Add details for `EventHubBufferedProducerClient`.
Fixes #1558.
---
|:--|:--|
| [docs/messaging/azure-event-hubs-integration.md](https://github.com/dotnet/docs-aspire/blob/1f7106a083cee52c0a76db5a43de2fb9e223a555/docs/messaging/azure-event-hubs-integration.md) | [docs/messaging/azure-event-hubs-integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/azure-event-hubs-integration?branch=pr-en-us-1559) |
> Add details for `EventHubBufferedProducerClient`

- docs/fundamentals/dashboard/configuration.md
Added OTLP dashboard bits.
Fixes #1588
---
|:--|:--|
| [docs/fundamentals/dashboard/configuration.md](https://github.com/dotnet/docs-aspire/blob/0d019148721109df65811f9f48ed936de025de65/docs/fundamentals/dashboard/configuration.md) | [docs/fundamentals/dashboard/configuration](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/configuration?branch=pr-en-us-1616) |
> Added OTLP dashboard bits

- docs/get-started/build-aspire-apps-with-nodejs.md
- docs/toc.yml
- Added missing AppHost content.
- Add links to the Node.js sample and add some content around that for OTEL.
- Edit pass + Acrolinx
- Added parameter links and mention secrets/env vars.
Fixes #1585, /cc @indcoder.
---
|:--|:--|
| [docs/get-started/build-aspire-apps-with-nodejs.md](https://github.com/dotnet/docs-aspire/blob/469e33d3e538b5de097aaf96770ea4bdf622cce1/docs/get-started/build-aspire-apps-with-nodejs.md) | [docs/get-started/build-aspire-apps-with-nodejs](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/build-aspire-apps-with-nodejs?branch=pr-en-us-1646) |
> More JavaScript content

- .repoman.yml
**Can't merge until the old repoman webhook is turned off.**
This new config adds the following changes:
- Use regex to see if the details of the issue is still the default.
This config setting is good at detecting spam from the docs feedback site. If someone comes in and only fills out a subject with no extra text, it will get closed. Let me know if you want me to remove this setting.
This config takes the following actions when it detects the issue just has the default description text:
- Add `needs-more-info` label.
- Remove `not triaged` label.
- Close the issue
- Turns on a new feature which adds a link to the bottom of the issue that is a search for issues related to the article.
- Support for moving issues related to project items around, and not having to manually add a label to …
> Update repoman to latest config

- docs/fundamentals/app-host-overview.md
- Add links to tutorial on existing projects.
- Add details supporting existing resources.
Fixes #1577
/cc @HugoDurana
---
|:--|:--|
| [docs/fundamentals/app-host-overview.md](https://github.com/dotnet/docs-aspire/blob/342eec1fa2688a8af96a521d80eb0f8e3bbcdeb5/docs/fundamentals/app-host-overview.md) | [docs/fundamentals/app-host-overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/app-host-overview?branch=pr-en-us-1691) |
> Add details supporting existing resources

- docs/database/azure-cosmos-db-integration.md
- Update app host usage information
- Fix `CosmosClient` configuration
- Add information about logging and traces
---
|:--|:--|
| [docs/database/azure-cosmos-db-integration.md](https://github.com/dotnet/docs-aspire/blob/2e98109229cf1cfe4c6b0f8f1fe0a4e38ee57b29/docs/database/azure-cosmos-db-integration.md) | [docs/database/azure-cosmos-db-integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/azure-cosmos-db-integration?branch=pr-en-us-1698) |
> Update Azure Cosmos DB integration doc

- docs/messaging/azure-service-bus-integration.md
- docs/security/azure-security-key-vault-integration.md
- docs/storage/azure-storage-tables-integration.md
We need to use `Client` on these method calls.
---
|:--|:--|
| [docs/messaging/azure-service-bus-integration.md](https://github.com/dotnet/docs-aspire/blob/02a02ba421c92a62a48f286d9fa5749d84514fe8/docs/messaging/azure-service-bus-integration.md) | [docs/messaging/azure-service-bus-integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/azure-service-bus-integration?branch=pr-en-us-1757) |
| [docs/security/azure-security-key-vault-integration.md](https://github.com/dotnet/docs-aspire/blob/02a02ba421c92a62a48f286d9fa5749d84514fe8/docs/security/azure-security-key-vault-integration.md) | [docs/security/azure-security-key-vault-integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/security/azure-security-key-vault-integration?branc …
> Use correct method name in ServiceBus

- docs/deployment/azure/aca-deployment-azd-in-depth.md
Fixes #1769
---
|:--|:--|
| [docs/deployment/azure/aca-deployment-azd-in-depth.md](https://github.com/dotnet/docs-aspire/blob/f3e1c8ab050d956a816a597f365141cae28ee375/docs/deployment/azure/aca-deployment-azd-in-depth.md) | [docs/deployment/azure/aca-deployment-azd-in-depth](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-azd-in-depth?branch=pr-en-us-1804) |
> Fix typo in aca-deployment-azd-in-depth.md

- docs/messaging/kafka-integration.md
Fix doc.
1. Current Kafka integration does not support distributed traces yet (PR is here https://github.com/dotnet/aspire/pull/5765)
2. https://github.com/dotnet/aspire/pull/4327 added ability to pull IServiceProvider to configureBuilder of AddKafkaConsumer and AddKafkaProducer
---
|:--|:--|
| [docs/messaging/kafka-integration.md](https://github.com/dotnet/docs-aspire/blob/57f6bfcec971091b2b74441ec319573c11fb4f1e/docs/messaging/kafka-integration.md) | [.NET Aspire Apache Kafka integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/kafka-integration?branch=pr-en-us-1821) |
> Fix Kafka integration documentation

- docs/whats-new/dotnet-aspire-9-release-candidate-1.md
I **strongly** recommend that the Azure Function section ([Lines 624-883](https://github.com/dotnet/docs-aspire/pull/1840/files#diff-4e38be68119e5416371c193280dc1758cc94fb1ce629be5de4e2c87c1711642fR624-R883)) be ripped out. It's largely out of place and completely breaks up the list of related "what's new" items. It should be shortened to a few paragraphs.
---
|:--|:--|
| [docs/whats-new/dotnet-aspire-9-release-candidate-1.md](https://github.com/dotnet/docs-aspire/blob/9698aa50508e2a282a35abdc02cc5b15236cd3db/docs/whats-new/dotnet-aspire-9-release-candidate-1.md) | [docs/whats-new/dotnet-aspire-9-release-candidate-1](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9-release-candidate-1?branch=pr-en-us-1840) |
> Various fixes and tweaks to what's new

- .github/policies/auto-merge.yml
Restrict auto-merge to PRs with auto-merge labels that were added by the dotnet policy service bot.
---
|:--|:--|
| [.github/policies/auto-merge.yml](https://github.com/dotnet/docs-aspire/blob/b275faa4d6d9876f61abac7b3de4cd419748f588/.github/policies/auto-merge.yml) | [.github/policies/auto-merge](https://review.learn.microsoft.com/en-us/dotnet/aspire/.github/policies/auto-merge?branch=pr-en-us-1860) |
> Restrict auto-merge

- docs/fundamentals/dashboard/enable-browser-telemetry.md
---
|:--|:--|
| [docs/fundamentals/dashboard/enable-browser-telemetry.md](https://github.com/dotnet/docs-aspire/blob/6490678ae760f994d60d6a254ff8b407f2eeff25/docs/fundamentals/dashboard/enable-browser-telemetry.md) | [Enable browser telemetry](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/enable-browser-telemetry?branch=pr-en-us-1870) |
> minor text fixes

- docs/diagnostics/overview.md
Add diagnostic code in support of:
https://github.com/dotnet/aspire/pull/6275
---
|:--|:--|
| [docs/diagnostics/overview.md](https://github.com/dotnet/docs-aspire/blob/af9b3381cf7559cbfcc06638c90e784e0303b0d0/docs/diagnostics/overview.md) | [.NET Aspire diagnostics overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/diagnostics/overview?branch=pr-en-us-1876) |
> Add diag code for ConfigureCustomDomains.

- docs/get-started/build-aspire-apps-with-nodejs.md
Fix broken links.
Contributes to #1862
---
|:--|:--|
| [docs/get-started/build-aspire-apps-with-nodejs.md](https://github.com/dotnet/docs-aspire/blob/a21c023b6e8923f395830c8b6187e0e56377e8ae/docs/get-started/build-aspire-apps-with-nodejs.md) | [Orchestrate Node.js apps in .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/build-aspire-apps-with-nodejs?branch=pr-en-us-1863) |
> Fix broken links

- docs/diagnostics/overview.md
React to changes in Aspire.Hosting.Python which is experimental in 9.0.
---
|:--|:--|
| [docs/diagnostics/overview.md](https://github.com/dotnet/docs-aspire/blob/2e3d821bd5fd9a3f460e9e559d5b00aae1538e1c/docs/diagnostics/overview.md) | [.NET Aspire diagnostics overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/diagnostics/overview?branch=pr-en-us-1880) |
> Document experimental attributes for Aspire.Hosting.Python

- docs/diagnostics/overview.md
Current aka.ms links use #UPPERCASE but the ids are lower-case.
---
|:--|:--|
| [docs/diagnostics/overview.md](https://github.com/dotnet/docs-aspire/blob/4dfab3b81a469cd15a1c5006f052020a8728a33a/docs/diagnostics/overview.md) | [.NET Aspire diagnostics overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/diagnostics/overview?branch=pr-en-us-1894) |
> Add section handles in for Aspire diagnostics

- .github/ISSUE_TEMPLATE/05-community-toolkit-docs-request.yml
This pull request introduces a new issue template for requesting articles related to the Aspire Community Toolkit. The template is designed to streamline the process for community members to propose new documentation topics.
This issue template is not necessary but it's very helpful to track Community Toolkit docs issues.
* **Template Name and Description**: Added a new issue template named "Community Toolkit article request" with a description to guide users on requesting new articles. (`.github/ISSUE_TEMPLATE/05-community-toolkit-docs-request.yml`)
* **Template Structure**: 
* **Title and Labels**: Predefined title prefix and labels for the issue. (`.github/ISSUE_TEMPLATE/05-community-toolkit-docs-request.yml`)
* **Form Fields**: Various fields to capture the proposed topic, location in …
> Create community toolkit docs request issue template

- .github/ISSUE_TEMPLATE/05-community-toolkit-docs-request.yml
Remove the markdown section because there is no input associated with this description.
---
|:--|:--|
| [.github/ISSUE_TEMPLATE/05-community-toolkit-docs-request.yml](https://github.com/dotnet/docs-aspire/blob/e90b607ea9f8a7baa7d24ddd9b260954ccb493b2/.github/ISSUE_TEMPLATE/05-community-toolkit-docs-request.yml) | ["[Community Toolkit New article]: "](https://review.learn.microsoft.com/en-us/dotnet/aspire/.github/ISSUE_TEMPLATE/05-community-toolkit-docs-request?branch=pr-en-us-2039) |
> Remove extra markdown section from community-toolkit-docs-request issue template

- docs/app-host/eventing.md
- docs/fundamentals/app-host-overview.md
- docs/index.yml
- docs/serverless/functions.md
- docs/toc.yml
- docs/whats-new/dotnet-aspire-9.md
Add xref to a few places, now that they're indexed
Fixes #2083
---
|:--|:--|
| [docs/app-host/eventing.md](https://github.com/dotnet/docs-aspire/blob/2b490fea4168db9a1d7eee4af32ec5fe644fdee1/docs/app-host/eventing.md) | [Eventing in .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/app-host/eventing?branch=pr-en-us-2084) |
| [docs/fundamentals/app-host-overview.md](https://github.com/dotnet/docs-aspire/blob/2b490fea4168db9a1d7eee4af32ec5fe644fdee1/docs/fundamentals/app-host-overview.md) | [.NET Aspire orchestration overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/app-host-overview?branch=pr-en-us-2084) |
| [docs/index.yml](https://github.com/dotnet/docs-aspire/blob/2b490fea4168db9a1d7eee4af32ec5fe644fdee1/docs/index …
> Add xref to a few places, now that they're indexed

- docs/compatibility/9.0/azure-resource-name-scheme.md
- docs/whats-new/dotnet-aspire-9.md
The code snippets for maintaining compatibility with Aspire .NET 8 naming conventions is incorrect and does not compile. I've replaced it with the correct code, referenced from the unit tests:
https://github.com/dotnet/aspire/blob/9abbb30cabe217bd0d03ecd9793e7a7427a71675/tests/Aspire.Hosting.Azure.Tests/AzureResourceOptionsTests.cs#L29-L32
---
|:--|:--|
| [docs/compatibility/9.0/azure-resource-name-scheme.md](https://github.com/dotnet/docs-aspire/blob/8d412acabe20a951ba207a746e9d6a8399ae4661/docs/compatibility/9.0/azure-resource-name-scheme.md) | [Better Azure resource name scheme](https://review.learn.microsoft.com/en-us/dotnet/aspire/compatibility/9.0/azure-resource-name-scheme?branch=pr-en-us-2087) |
| …
> Correct Aspire V8 naming change code

- docs/messaging/rabbitmq-integration.md
---
|:--|:--|
| [docs/messaging/rabbitmq-integration.md](https://github.com/dotnet/docs-aspire/blob/aa5ab14a10138539f52489ff54488c8ed854d818/docs/messaging/rabbitmq-integration.md) | [.NET Aspire RabbitMQ integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/rabbitmq-integration?branch=pr-en-us-2097) |
> correct linking in RabbitMQ integration docs

- docs/messaging/kafka-integration.md
The docs incorrectly show the `WithHostPort(...)` extension method on the `IResourceBuilder<KafkaServerResource>`.
This is true for v8.2.2 and v9.0.0
The below screenshot is from a Visual Studio project using v9.0.0.
---
|:--|:--|
| [docs/messaging/kafka-integration.md](https://github.com/dotnet/docs-aspire/blob/9b57f4f5130f44c0c87a2586aec0b2c52de52e0a/docs/messaging/kafka-integration.md) | [.NET Aspire Apache Kafka integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/kafka-integration?branch=pr-en-us-2132) |
> Fix how to specify kafka ui host port

- docs/authentication/keycloak-integration.md
- docs/azureai/azureai-openai-integration.md
- docs/azureai/azureai-search-document-integration.md
- docs/breadcrumb/toc.yml
- docs/caching/includes/garnet-app-host.md
- docs/caching/includes/redis-app-host.md
- docs/caching/includes/valkey-app-host.md
- docs/community-toolkit/hosting-data-api-builder.md
- docs/database/azure-cosmos-db-entity-framework-integration.md
- docs/database/azure-cosmos-db-integration.md
- docs/database/includes/mysql-app-host.md
- docs/database/includes/postgresql-app-host.md
- docs/database/milvus-integration.md
- docs/database/mongodb-integration.md
- docs/database/oracle-entity-framework-integration.md
- docs/database/qdrant-integration.md
- docs/fundamentals/dashboard/security-considerations.md
- docs/get-started/build-aspire-apps-with-nodejs.md
- docs/logging/seq-integration.md
- docs/messaging/azure-event-hubs-integration.md
- docs/messaging/azure-service-bus-integration.md
- docs/messaging/azure-web-pubsub-integration.md
- docs/search/elasticsearch-integration.md
- docs/security/azure-security-key-vault-integration.md
- docs/storage/azure-storage-blobs-integration.md
- docs/storage/azure-storage-queues-integration.md
- docs/storage/azure-storage-tables-integration.md
- Fix what appears to be a bad merge conflict.
- Fix dup word.
- Fix breadcrumbs to the best of the platform supported capabilities.
Fixes #2133 and maybe #2099
---
|:--|:--|
| [docs/authentication/keycloak-integration.md](https://github.com/dotnet/docs-aspire/blob/8f24d6935b9790770be666ab5bcad19530b9d4e7/docs/authentication/keycloak-integration.md) | [.NET Aspire Keycloak integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/authentication/keycloak-integration?branch=pr-en-us-2140) |
| [docs/azureai/azureai-openai-integration.md](https://github.com/dotnet/docs-aspire/blob/8f24d6935b9790770be666ab5bcad19530b9d4e7/docs/azureai/azureai-openai-integration.md) | [.NET Aspire …
> Misc fixes

- docs/database/azure-cosmos-db-integration.md
Based on some internal feedback. Callout using WaitFor when the emulator is used.
---
|:--|:--|
| [docs/database/azure-cosmos-db-integration.md](https://github.com/dotnet/docs-aspire/blob/b66f8310fd39eaf095b766bb5646a092709080af/docs/database/azure-cosmos-db-integration.md) | [.NET Aspire Azure Cosmos DB integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/azure-cosmos-db-integration?branch=pr-en-us-2152) |
> Add note about WaitFor to Cosmos docs.

- docs/community-toolkit/hosting-eventstore.md
`WithLogVolume` and `WithLogBindMount` methods were removed from `EventStoreBuilderExtensions` class as other Hosting components usually don't provide such methods for log volume/mount.
However, I've update the docs to make use of the common Volume/Mount extension methods to show how users can persist the logs if desired.
EventStore integration PR is already merged: https://github.com/CommunityToolkit/Aspire/pull/277
---
|:--|:--|
| [docs/community-toolkit/hosting-eventstore.md](https://github.com/dotnet/docs-aspire/blob/ccf0d58026af31dc028cab9e727745dcca1461e3/docs/community-toolkit/hosting-eventstore.md) | [.NET Aspire Community Toolkit EventStore integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/community-toolkit/hosting-eventstore?branch=pr …
> Update EventStore docs

- docs/fundamentals/aspire-sdk-templates.md
Adds a specific callout about using `--framework` to specify the .NET  version to use when creating Aspire projects using the .NET CLI.
Fixes microsoft/vscode-dotnettools#1643
---
|:--|:--|
| [docs/fundamentals/aspire-sdk-templates.md](https://github.com/dotnet/docs-aspire/blob/3f67b48d938023d142821bcb83aaa02d2d152888/docs/fundamentals/aspire-sdk-templates.md) | [docs/fundamentals/aspire-sdk-templates](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/aspire-sdk-templates?branch=pr-en-us-2174) |
> Add tip about --framework option for creating Aspire projects with CLI

- docs/database/includes/postgresql-app-host.md
- docs/database/includes/sql-app-host.md
- docs/database/mongodb-integration.md
- docs/fundamentals/app-host-overview.md
Rewrite the MongoDB integration article. Fixes #2177
---
|:--|:--|
| [docs/database/mongodb-integration.md](https://github.com/dotnet/docs-aspire/blob/303574121e9346105602ab89797e6f973aae3171/docs/database/mongodb-integration.md) | [.NET Aspire MongoDB database integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/mongodb-integration?branch=pr-en-us-2178) |
> Rewrite the MongoDB integration article.

- quest-config.json
Some of the labels were targeting the wrong semester.
> Fix some config mistakes

- .github/workflows/create-monthly-issues.yml
Not sure when this happened, but the links were automatically removed.
---
|:--|:--|
| [.github/workflows/create-monthly-issues.yml](https://github.com/dotnet/docs-aspire/blob/8e5b1b5be859a0520cb9e2847ac3f266824841df/.github/workflows/create-monthly-issues.yml) | [.github/workflows/create-monthly-issues](https://review.learn.microsoft.com/en-us/dotnet/aspire/.github/workflows/create-monthly-issues?branch=pr-en-us-2294) |
> Re-add issue automation

- docs/logging/seq-integration.md
Restructures and updates the Seq integration article.
Fixes #2301
---
|:--|:--|
| [docs/logging/seq-integration.md](https://github.com/dotnet/docs-aspire/blob/0dcbce81942e43aa3227775c2f42b55110b494a2/docs/logging/seq-integration.md) | [.NET Aspire Seq integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/logging/seq-integration?branch=pr-en-us-2321) |
> Seq integration rewrite

- docs/fundamentals/dashboard/explore.md
Replace technical information with example of how exemplars are useful.
---
|:--|:--|
| [docs/fundamentals/dashboard/explore.md](https://github.com/dotnet/docs-aspire/blob/2df7229204d9af5ed5c0491e6dfd93ac2c34f1b7/docs/fundamentals/dashboard/explore.md) | [docs/fundamentals/dashboard/explore](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/explore?branch=pr-en-us-2353) |
> Improve exemplar description

- docs/frameworks/orleans.md
[This Reddit thread](https://www.reddit.com/r/dotnet/comments/1hzmc03/why_doesnt_this_aspire_project_work/) highlights that the current doc has a deficiency in that it misses these two packages
---
|:--|:--|
| [docs/frameworks/orleans.md](https://github.com/dotnet/docs-aspire/blob/eb7f2cd9afda265d436b92aa6b9d90157dccbbee/docs/frameworks/orleans.md) | [.NET Aspire Orleans integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/frameworks/orleans?branch=pr-en-us-2372) |
> Add Orleans Server & Client NuGet packages to guide

- docs/deployment/azure/aca-deployment-github-actions.md
Bump version of AZD. Fixes #2362
---
|:--|:--|
| [docs/deployment/azure/aca-deployment-github-actions.md](https://github.com/dotnet/docs-aspire/blob/d16116e18fe17a4d2f538d13a18c8305cf6f9000/docs/deployment/azure/aca-deployment-github-actions.md) | [Tutorial: Deploy a .NET Aspire project using the Azure Developer CLI and GitHub Actions](https://review.learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-github-actions?branch=pr-en-us-2364) |
> Bump version of AZD

- docs/index.yml
The platform extensions monikers don't exist anymore.
---
|:--|:--|
| [docs/index.yml](https://github.com/dotnet/docs-aspire/blob/63239aabb4b2416c0ecc5bb0a3fc55fa01562abf/docs/index.yml) | [Limit summary to 400 characters](https://review.learn.microsoft.com/en-us/dotnet/aspire/index?branch=pr-en-us-2480) |
> Remove platform extensions API ref link

- docs/database/oracle-entity-framework-integration.md
Expands and restructures the article.
Fixes #2306
---
|:--|:--|
| [docs/database/oracle-entity-framework-integration.md](https://github.com/dotnet/docs-aspire/blob/7d9f16b3f715ddb803d2f013edd73bf5b3217b4b/docs/database/oracle-entity-framework-integration.md) | [.NET Aspire Oracle Entity Framework Core integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/oracle-entity-framework-integration?branch=pr-en-us-2478) |
> Oracle EF Core integration rewrite

- docs/get-started/aspire-overview.md
No GPTs were harmed in the making of this PR
Fixes #2093
---
|:--|:--|
| [docs/get-started/aspire-overview.md](https://github.com/dotnet/docs-aspire/blob/c61c61001f164260da27fd91dd9a8a241083598a/docs/get-started/aspire-overview.md) | [docs/get-started/aspire-overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/aspire-overview?branch=pr-en-us-2377) |
> overview page update branding / cleanup

- docs/fundamentals/setup-tooling.md
Remove placeholder content.
Fixes #2374
---
|:--|:--|
| [docs/fundamentals/setup-tooling.md](https://github.com/dotnet/docs-aspire/blob/19d38fa5d3ee7d5a1971ccd2155eff71aada28e6/docs/fundamentals/setup-tooling.md) | [.NET Aspire setup and tooling](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/setup-tooling?branch=pr-en-us-2431) |
> Remove placeholder content

- docs/fundamentals/integrations-overview.md
Add a section describing how Aspire updates versions of dependencies.
---
|:--|:--|
| [docs/fundamentals/integrations-overview.md](https://github.com/dotnet/docs-aspire/blob/9d5831fc1cabcbb61f34bb1ec873a12bd1c2da5f/docs/fundamentals/integrations-overview.md) | [.NET Aspire integrations overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/integrations-overview?branch=pr-en-us-2425) |
> Add versioning considerations to integration overview

- docs/database/snippets/tutorial/aspiresqlefcore/AspireSQLEFCore/Components/Pages/Home.razor
The razor code in the [Tutorial: Connect an ASP.NET Core app to SQL Server using .NET Aspire and Entity Framework Core](https://learn.microsoft.com/dotnet/aspire/database/sql-server-integrations) currently causes an error. I've added the following line to the snippet to fix it:
``` razor
@using Microsoft.EntityFrameworkCore
```
Fixes #2102
> Fix the SQL Server with Entity Framework tutorial

- docs/serverless/functions.md
@IEvangelist CosmosDB triggers are going to be supported for Functions as of 9.1.
I dunno how we want to stylize this in the docs but I figured a note in the column is a good enough start.
---
|:--|:--|
| [docs/serverless/functions.md](https://github.com/dotnet/docs-aspire/blob/db7f697acc11e8307a55df5f2b4c432af2cfb595/docs/serverless/functions.md) | [.NET Aspire Azure Functions integration (Preview)](https://review.learn.microsoft.com/en-us/dotnet/aspire/serverless/functions?branch=pr-en-us-2550) |
> List CosmosDB triggers as supported

- docs/storage/azure-storage-blobs-integration.md
- docs/storage/includes/storage-app-host.md
Fixes #2553
Update Azurite container ports code example to use only one argument for `WithBlobPort`, `WithTablePort`, and `WithQueuePort`.
* Remove the string arguments representing the type configured from the code example in `docs/storage/azure-storage-blobs-integration.md`.
* Specify only the port numbers for `WithBlobPort`, `WithQueuePort`, and `WithTablePort` in the code example.
* Update the code example in `docs/storage/includes/storage-app-host.md` to reflect the changes.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/dotnet/docs-aspire/pull/2554?shareId=8acd9573-509b-4ad2-b4ff-e14f495c5f95).
---
|:--|:--|
| [docs/storage/azure-storage-blobs-integration.md](https://github.com/dotnet/docs-aspire/blob/5e …
> Fix Azurite container ports code example

- docs/messaging/azure-service-bus-integration.md
- docs/snippets/azure/AppHost/Program.ConfigureServiceBusInfra.cs
> [!CAUTION]
> Currently **blocked** by the release of .NET Aspire 9.1. Various APIs and `xref` links will not render correctly and are missing.
Rewrite Azure Service Bus integration article.
Fixes #2308
---
|:--|:--|
| [docs/messaging/azure-service-bus-integration.md](https://github.com/dotnet/docs-aspire/blob/617122a516b4439bda532d3bb64e78d46a1b089c/docs/messaging/azure-service-bus-integration.md) | [.NET Aspire Azure Service Bus integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/azure-service-bus-integration?branch=pr-en-us-2365) |
> Update Azure Service Bus integration doc

- docs/testing/accessing-resources.md
Resource notifications.
Supersedes and closes #2564, and fixes #2563.
---
|:--|:--|
| [docs/testing/accessing-resources.md](https://github.com/dotnet/docs-aspire/blob/106c89b4d6acafe4d820d9bde928bac8e0bf968e/docs/testing/accessing-resources.md) | [Access resources in .NET Aspire tests](https://review.learn.microsoft.com/en-us/dotnet/aspire/testing/accessing-resources?branch=pr-en-us-2568) |
> Resource notifications

- docs/fundamentals/app-host-overview.md
Document this new behavior in 9.1.
---
|:--|:--|
| [docs/fundamentals/app-host-overview.md](https://github.com/dotnet/docs-aspire/blob/58544058496d411b93c19bfaca14173fbb3a2ffb/docs/fundamentals/app-host-overview.md) | [docs/fundamentals/app-host-overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/app-host-overview?branch=pr-en-us-2629) |
> [9.1] Force waiting resource to start

- docs/database/mongodb-integration.md
- docs/messaging/rabbitmq-integration.md
Add details about the decision to provide version-suffixed client integrations when dependent packages introduce binary breaking changes.
Fixes #2360
---
|:--|:--|
| [docs/database/mongodb-integration.md](https://github.com/dotnet/docs-aspire/blob/6813e72f903df502900654fc7d0d4f3d9889bd05/docs/database/mongodb-integration.md) | [.NET Aspire MongoDB database integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/mongodb-integration?branch=pr-en-us-2643) |
| [docs/messaging/rabbitmq-integration.md](https://github.com/dotnet/docs-aspire/blob/6813e72f903df502900654fc7d0d4f3d9889bd05/docs/messaging/rabbitmq-integration.md) | [.NET Aspire RabbitMQ integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/rabbitmq-integration?br …
> Version-suffixed NuGet client integrations

- docs/database/includes/cosmos-app-host.md
- docs/diagnostics/overview.md
Fix #2376
---
|:--|:--|
| [docs/diagnostics/overview.md](https://github.com/dotnet/docs-aspire/blob/3ecc043a0f89678b103642bc0dd7b33f23d670da/docs/diagnostics/overview.md) | [.NET Aspire diagnostics overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/diagnostics/overview?branch=pr-en-us-2654) |
> Add docs for CosmosDB preview emulator

- docs/database/includes/cosmos-app-host.md
- docs/messaging/azure-event-hubs-integration.md
- docs/messaging/azure-service-bus-integration.md
- docs/snippets/azure/AppHost/Program.cs
- docs/snippets/azure/AppHost/aspire-manifest.json
- docs/snippets/azure/AppHost/event-hubs.module.bicep
These APIs changed late in 9.1. See https://github.com/dotnet/docs-aspire/issues/2327#issuecomment-2673088907
---
|:--|:--|
| [docs/messaging/azure-event-hubs-integration.md](https://github.com/dotnet/docs-aspire/blob/e92c85e90ce0308d37bee2657d2d26e13d3143c5/docs/messaging/azure-event-hubs-integration.md) | [.NET Aspire Azure Event Hubs integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/azure-event-hubs-integration?branch=pr-en-us-2656) |
| [docs/messaging/azure-service-bus-integration.md](https://github.com/dotnet/docs-aspire/blob/e92c85e90ce0308d37bee2657d2d26e13d3143c5/docs/messaging/azure-service-bus-integration.md) | [.NET Aspire Azure Service Bus integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/azure- …
> Update CosmosDB, EventHubs, and ServiceBus for latest APIs.

- docs/get-started/github-codespaces.md
Remove the Azure features out of the devcontainer sample.
---
|:--|:--|
| [docs/get-started/github-codespaces.md](https://github.com/dotnet/docs-aspire/blob/5da14ed6b64083beb08be99011bcfb553ecef64e/docs/get-started/github-codespaces.md) | [.NET Aspire and GitHub Codespaces](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/github-codespaces?branch=pr-en-us-2664) |
> Remove-azure-features-from-devcontainer

- docs/whats-new/dotnet-aspire-9.1.md
The "Upgrade to 9.1" should be first
---
|:--|:--|
| [docs/whats-new/dotnet-aspire-9.1.md](https://github.com/dotnet/docs-aspire/blob/79ee417c535a4d0c8d58d372c1ef3f6418038152/docs/whats-new/dotnet-aspire-9.1.md) | [What's new in .NET Aspire 9.1](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9.1?branch=pr-en-us-2668) |
> Move Upgrade to 9.1 to the top

- docs/azure/integrations-overview.md
Adding some additional clarification on the difference between the different strategies for referencing existing Azure resources in the `docs/azure/integrations-overview.md` file.
---
|:--|:--|
| [docs/azure/integrations-overview.md](https://github.com/dotnet/docs-aspire/blob/bbafa657fedf333dd6a758790051e4d9aead03bc/docs/azure/integrations-overview.md) | [.NET Aspire Azure integrations overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/azure/integrations-overview?branch=pr-en-us-2678) |
> Add snippet on difference between different existing resource strategies

- docs/community-toolkit/hosting-sql-database-projects.md
Document new feature in the SQL Database Projects hosting extension that adds support for using a connection string
---
|:--|:--|
| [docs/community-toolkit/hosting-sql-database-projects.md](https://github.com/dotnet/docs-aspire/blob/b44713f5be6593bc8c80bd9d8e7f44c5e900be08/docs/community-toolkit/hosting-sql-database-projects.md) | [.NET Aspire SQL Database Projects hosting integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/community-toolkit/hosting-sql-database-projects?branch=pr-en-us-2486) |
> Add docs for new SQL Project extension feature to use a connection string

- docs/database/azure-cosmos-db-entity-framework-integration.md
- docs/database/azure-cosmos-db-integration.md
Correctly state Cosmos DB client integration health checks coverage.
Fixes #2571
---
|:--|:--|
| [docs/database/azure-cosmos-db-entity-framework-integration.md](https://github.com/dotnet/docs-aspire/blob/f0b534387e7397687a40b25c695fd6740ee6f6f4/docs/database/azure-cosmos-db-entity-framework-integration.md) | [.NET Aspire Cosmos DB Entity Framework Core integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/azure-cosmos-db-entity-framework-integration?branch=pr-en-us-2698) |
| [docs/database/azure-cosmos-db-integration.md](https://github.com/dotnet/docs-aspire/blob/f0b534387e7397687a40b25c695fd6740ee6f6f4/docs/database/azure-cosmos-db-integration.md) | [.NET Aspire Azure Cosmos DB integration](https://review.learn.microsoft.com/en-us/dotnet/ …
> Correctly state Cosmos DB client integration health checks coverage

- docs/testing/snippets/testing/mstest/AspireApp.Tests/EnvVarTests.cs
- docs/testing/snippets/testing/mstest/AspireApp.Tests/IntegrationTest1.cs
- docs/testing/snippets/testing/nunit/AspireApp.Tests/EnvVarTests.cs
- docs/testing/snippets/testing/nunit/AspireApp.Tests/IntegrationTest1.cs
- docs/testing/snippets/testing/xunit/AspireApp.Tests/EnvVarTests.cs
- docs/testing/snippets/testing/xunit/AspireApp.Tests/IntegrationTest1.cs
- Rename appHost to builder
- Use CreateResourceBuilder instead of Resources.Single(...)
- Use ResourceNotifications and WaitForResourceHealthyAsync
> Update testing snippets to use v9.1 testing changes

- docs/get-started/build-aspire-apps-with-nodejs.md
Update the Angular get started article.
This PR adds the step to update the `angular.json` to include to proxy, which is created in step 1.
Fixes #2700 (if available)
---
|:--|:--|
| [docs/get-started/build-aspire-apps-with-nodejs.md](https://github.com/dotnet/docs-aspire/blob/6c983a0c14836a7769edebb9fb5eb229e80f584b/docs/get-started/build-aspire-apps-with-nodejs.md) | [Orchestrate Node.js apps in .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/build-aspire-apps-with-nodejs?branch=pr-en-us-2708) |
> javascript(angular): add proxy to the angular.json configuration

- docs/community-toolkit/hosting-mongodb-extensions.md
- docs/community-toolkit/hosting-postgresql-extensions.md
- docs/community-toolkit/hosting-redis-extensions.md
- docs/community-toolkit/hosting-sqlserver-extensions.md
- docs/community-toolkit/includes/sqlite-hosting.md
- docs/community-toolkit/overview.md
- docs/community-toolkit/sqlite-entity-framework-integration.md
- docs/community-toolkit/sqlite.md
- docs/toc.yml
This pull request adds comprehensive documentation for various .NET Aspire Community Toolkit hosting extensions, including MongoDB extensions, PostgreSQL extensions, Redis extensions, SQL Server extensions, and SQLite. It also introduces new client integration documentation for SQLite with Entity Framework. The most important changes include detailed instructions for using these extensions, examples of usage, and updates to the overview documentation to reflect these additions.
- Fixes #2435 
- Fixes #2665 
- Fixes #2632 
- Fixes #2560
- Fixes #2540
Hosting Extensions Documentation:
* [`docs/community-toolkit/hosting-mongodb-extensions.md`](diffhunk://#diff-dc7c1648b10ad493bf06d3c39455c6693c8ce20bc601f21e5b9c818dc32a62c5R1-R49): Added documentation for MongoDB hosting extensions, …
> Several new docs from the Community Toolkit

- docs/testing/manage-app-host.md
Fix code snippets for `DistributedApplicationFactory` usage to use primary constructors correctly.
---
|:--|:--|
| [docs/testing/manage-app-host.md](https://github.com/dotnet/docs-aspire/blob/517ee9eac224f9feb1c6cfcd922213b2cd7e7499/docs/testing/manage-app-host.md) | [Manage the app host in .NET Aspire tests](https://review.learn.microsoft.com/en-us/dotnet/aspire/testing/manage-app-host?branch=pr-en-us-2773) |
> Fix code snippets

- docs/azureai/azureai-openai-integration.md
- docs/caching/includes/redis-client-json-settings.md
- docs/caching/includes/redis-distributed-client-json-settings.md
- docs/caching/includes/redis-output-client-json-settings.md
- docs/database/azure-cosmos-db-entity-framework-integration.md
- docs/database/azure-cosmos-db-integration.md
- docs/database/includes/postgresql-client.md
- docs/database/includes/postgresql-ef-client.md
- docs/database/milvus-integration.md
- docs/database/qdrant-integration.md
- docs/logging/seq-integration.md
- docs/messaging/azure-service-bus-integration.md
- docs/messaging/kafka-integration.md
- docs/messaging/nats-integration.md
- docs/messaging/rabbitmq-integration.md
- docs/search/elasticsearch-integration.md
- docs/security/azure-security-key-vault-integration.md
- docs/snippets/azure/AppHost/Program.ConfigureOpenAIInfra.cs
- docs/snippets/azure/AppHost/Program.cs
- docs/snippets/azure/AppHost/aspire-manifest.json
- docs/snippets/azure/AppHost/cosmos.module.bicep
- docs/snippets/azure/AppHost/openai.module.bicep
- docs/storage/azure-storage-blobs-integration.md
- docs/storage/azure-storage-queues-integration.md
- docs/storage/azure-storage-tables-integration.md
- docs/toc.yml
In this PR — [.NET Aspire Azure OpenAI integration (Preview)](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-openai-integration?branch=pr-en-us-2722&tabs=dotnet-cli):
- Rewrite the .NET Aspire Azure OpenAI integration article
- Fixes TOC and bumps JSON link
Fixes #2314
---
|:--|:--|
| [docs/azureai/azureai-openai-integration.md](https://github.com/dotnet/docs-aspire/blob/ba5643e7ed6a4759c0f0b36c07608d523caf2842/docs/azureai/azureai-openai-integration.md) | [.NET Aspire Azure OpenAI integration (Preview)](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-openai-integration?branch=pr-en-us-2722) |
| …
> Rewrite the .NET Aspire Azure OpenAI integration article

- docs/azure/integrations-overview.md
Adds missing API details for `PublishAsAzureContainerApp`.
Fixes #1699
---
|:--|:--|
| [docs/azure/integrations-overview.md](https://github.com/dotnet/docs-aspire/blob/b14a961ede5fe1a31c74b1a83fb1211c4bd6bf40/docs/azure/integrations-overview.md) | [.NET Aspire Azure integrations overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/azure/integrations-overview?branch=pr-en-us-2777) |
> Adds missing API details for `PublishAsAzureContainerApp`

- docs/database/sql-server-entity-framework-integration.md
add a semicolon.
---
|:--|:--|
| [docs/database/sql-server-entity-framework-integration.md](https://github.com/dotnet/docs-aspire/blob/2866185d91c1cd7bfbc2e0623b3689709194e4e7/docs/database/sql-server-entity-framework-integration.md) | [.NET Aspire SQL Server Entity Framework Core integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/sql-server-entity-framework-integration?branch=pr-en-us-2841) |
> missing a semicolon  in sql-server-entity-framework-integration.md

- docs/messaging/azure-service-bus-integration.md
The Aspire emulator support doesn't generate this file by default. It uses the registered resources (queues, topics, ...). But it can be set manually.
---
|:--|:--|
| [docs/messaging/azure-service-bus-integration.md](https://github.com/dotnet/docs-aspire/blob/a7d582a15924d8cedfbb3fc79032e0616077f1eb/docs/messaging/azure-service-bus-integration.md) | [.NET Aspire Azure Service Bus integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/azure-service-bus-integration?branch=pr-en-us-2848) |
> Fix error in Aspire service bus configuration section

- docs/database/includes/postgresql-app-host.md
- docs/database/includes/sql-app-host.md
Adds the database details for SQL server.
Adds the database details for PostgreSQL server.
Fixes #2789
_**Previews**_
- [.NET Aspire SQL Server integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/sql-server-integration?branch=pr-en-us-2878&tabs=dotnet-cli%2Cssms)
- [.NET Aspire PostgreSQL integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/postgresql-integration?branch=pr-en-us-2878&tabs=dotnet-cli)
> Add clarifying details about updates to `AddDatabase` APIs

- docs/database/entity-framework-core-integration-overview.md
After copy-pasting a snippet, I noticed it didn't compile because of missing brackets.
This PR fixes some other smaller issues as well within the code samples.
---
|:--|:--|
| [docs/database/entity-framework-core-integration-overview.md](https://github.com/dotnet/docs-aspire/blob/94e50b3d183c0d1f9873a8f310931c8e16f4ab1f/docs/database/entity-framework-core-integration-overview.md) | [Entity Framework Core overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/entity-framework-core-integration-overview?branch=pr-en-us-2897) |
> fix typos entity-framework-core-integration-overview

- docs/messaging/kafka-integration.md
This change the docs to reflect changes of https://github.com/dotnet/aspire/pull/7830
---
|:--|:--|
| [docs/messaging/kafka-integration.md](https://github.com/dotnet/docs-aspire/blob/0dbb2050e00b6fad06d7e4cc18dc17d7e0b558f0/docs/messaging/kafka-integration.md) | [.NET Aspire Apache Kafka integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/kafka-integration?branch=pr-en-us-2712) |
> Update Links of kafkaui

- docs/azure/integrations-overview.md
- docs/azure/role-assignments.md
- docs/snippets/azure/AppHost/AppHost.csproj
- docs/toc.yml
Add role assignments with .NET Aspire
Fixes #2788
---
|:--|:--|
| [docs/azure/integrations-overview.md](https://github.com/dotnet/docs-aspire/blob/3813362569da04c66c010fde905457f575757e9e/docs/azure/integrations-overview.md) | [.NET Aspire Azure integrations overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/azure/integrations-overview?branch=pr-en-us-2891) |
| [docs/azure/role-assignments.md](https://github.com/dotnet/docs-aspire/blob/3813362569da04c66c010fde905457f575757e9e/docs/azure/role-assignments.md) | [Manage Azure role assignments](https://review.learn.microsoft.com/en-us/dotnet/aspire/azure/role-assignments?branch=pr-en-us-2891) |
| [docs/toc.yml](https://github.com/dotnet/docs-aspire/blob/3813362569da04c66c010fde905457f575757e9e/docs/toc …
> Add role assignments with .NET Aspire

- docs/compatibility/9.2/generated-bicep-updates.md
- docs/compatibility/9.2/index.md
- docs/compatibility/9.2/keyvault-role-assignment-changes.md
- docs/compatibility/9.2/managed-identity-per-app.md
- docs/compatibility/9.2/withauthentication-changes.md
- docs/compatibility/9.2/withcommand-obsolete.md
- docs/compatibility/api-removal.md
- docs/compatibility/breaking-changes.md
- docs/compatibility/categories.md
- docs/compatibility/toc.yml
Breaking changes for .NET Aspire 9.2.
- Fixes #2888
- Fixes #2889
- Fixes #2899 
- Fixes #2914
- Fixes #2911
---
|:--|:--|
| [docs/compatibility/9.2/generated-bicep-updates.md](https://github.com/dotnet/docs-aspire/blob/df8b7c5267995fbb58c419d2b3b2ec4bce939812/docs/compatibility/9.2/generated-bicep-updates.md) | [Role Assignments separated from Azure resource bicep](https://review.learn.microsoft.com/en-us/dotnet/aspire/compatibility/9.2/generated-bicep-updates?branch=pr-en-us-2892) |
| [docs/compatibility/9.2/index.md](https://github.com/dotnet/docs-aspire/blob/df8b7c5267995fbb58c419d2b3b2ec4bce939812/docs/compatibility/9.2/index.md) | [Breaking changes in .NET Aspire 9.2](https://review.learn.microsoft.com/en-us/dotnet/aspire/compatibility/9.2/index?branch=pr- …
> Breaking changes for .NET Aspire 9.2

- docs/database/azure-postgresql-entity-framework-integration.md
- docs/database/azure-postgresql-integration.md
- docs/database/includes/azure-postgresql-client.md
- docs/database/includes/azure-postgresql-ef-client.md
- docs/database/includes/postgresql-app-host.md
Add new Azure PostgreSQL client integrations.
Fixes #2883
---
|:--|:--|
| [docs/database/azure-postgresql-entity-framework-integration.md](https://github.com/dotnet/docs-aspire/blob/7c03316f4bc47398120864827f77dae12f2810b1/docs/database/azure-postgresql-entity-framework-integration.md) | [.NET Aspire Azure PostgreSQL Entity Framework Core integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/azure-postgresql-entity-framework-integration?branch=pr-en-us-2905) |
| [docs/database/azure-postgresql-integration.md](https://github.com/dotnet/docs-aspire/blob/7c03316f4bc47398120864827f77dae12f2810b1/docs/database/azure-postgresql-integration.md) | [.NET Aspire Azure PostgreSQL integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/dat …
> Add new Azure PostgreSQL client integrations.

- docs/whats-new/dotnet-aspire-9.2.md
BlueSky spelling and some repeated items 
---
|:--|:--|
| [docs/whats-new/dotnet-aspire-9.2.md](https://github.com/dotnet/docs-aspire/blob/a84608641d0aa6555aa4815ee0be829d31b47968/docs/whats-new/dotnet-aspire-9.2.md) | [What's new in .NET Aspire 9.2](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9.2?branch=pr-en-us-3064) |
> A couple things

- docs/whats-new/dotnet-aspire-9.2.md
---
|:--|:--|
| [docs/whats-new/dotnet-aspire-9.2.md](https://github.com/dotnet/docs-aspire/blob/3d3afbc97f3933e3d13bbd413b0ea8eaf91b3d3c/docs/whats-new/dotnet-aspire-9.2.md) | [What's new in .NET Aspire 9.2](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9.2?branch=pr-en-us-3066) |
> Feedback for What's New in 9.2

- docs/get-started/build-aspire-apps-with-python.md
- Add instructions to run the app as HTTP which is required for the OpenTelemetry package to work via Python on a local dev box.
- Adjust some of the code block identifiers.
- Improve acro score from 88 to 95.
- Add some extra code highlighters where appropriate.
Fixes #3076
---
|:--|:--|
| [docs/get-started/build-aspire-apps-with-python.md](https://github.com/dotnet/docs-aspire/blob/012d770ad7bf093168e8f4a43cd3551403ab9faf/docs/get-started/build-aspire-apps-with-python.md) | [docs/get-started/build-aspire-apps-with-python](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/build-aspire-apps-with-python?branch=pr-en-us-3117) |
> Fix the Python article

- docs/diagnostics/overview.md
Add missing diagnostics and an attempt to remove redundancies
Fixes #2882
Contributes to #3057
---
|:--|:--|
| [docs/diagnostics/overview.md](https://github.com/dotnet/docs-aspire/blob/e39695088be46244b85e0bca9decb3215944e4ab/docs/diagnostics/overview.md) | [.NET Aspire diagnostics overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/diagnostics/overview?branch=pr-en-us-3077) |
> Add missing diagnostics

- docs/azure/configure-aca-environments.md
Modified existing 'configure-aca-environments.md' to provide simple example of configuring the container apps environment in Program.cs of the Aspire AppHost, using 'ConfigureInfrastructure' and getting the provisionable resource of type 'ContainerAppManagedEnvironment'.
fixes #3085
---
|:--|:--|
| [docs/azure/configure-aca-environments.md](https://github.com/dotnet/docs-aspire/blob/8017de83958bfda19135ee2d2fed86c6d2ceb6cf/docs/azure/configure-aca-environments.md) | [Configure Azure Container Apps environments](https://review.learn.microsoft.com/en-us/dotnet/aspire/azure/configure-aca-environments?branch=pr-en-us-3119) |
> fixes #3085 Simple example for configuring the container apps environment

- .github/ISSUE_TEMPLATE/06-diagnostic-addition.yml
Discuss!
- Fun intro box
- Add field to indicate error or warning
- Add short title, hopefully engineer will paste in the actual error text a user sees.
- Keep Description
- Add possible fix
- Add version introduced
Preview: https://github.com/dotnet/docs-aspire/blob/adegeo/github/diagnostic/.github/ISSUE_TEMPLATE/06-diagnostic-addition.yml
---
|:--|:--|
| [.github/ISSUE_TEMPLATE/06-diagnostic-addition.yml](https://github.com/dotnet/docs-aspire/blob/998ccb06dd551ab115d2b593199d7a26a31d85d1/.github/ISSUE_TEMPLATE/06-diagnostic-addition.yml) | [.github/ISSUE_TEMPLATE/06-diagnostic-addition](https://review.learn.microsoft.com/en-us/dotnet/aspire/.github/ISSUE_TEMPLATE/06-diagnostic-addition?branch=pr-en-us-3127) |
> Redesign diagnostic template

- docs/frameworks/orleans.md
Add the missing contract/interface.
Fixes #3132
---
|:--|:--|
| [docs/frameworks/orleans.md](https://github.com/dotnet/docs-aspire/blob/fc0ee2ad6ba22886d0758cc54abbe1159a42e93b/docs/frameworks/orleans.md) | [.NET Aspire Orleans integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/frameworks/orleans?branch=pr-en-us-3134) |
> Add missing Orleans interface

- docs/fundamentals/aspire-sdk-templates.md
Add dev-cert details to templates content.
Fixes #3135
---
|:--|:--|
| [docs/fundamentals/aspire-sdk-templates.md](https://github.com/dotnet/docs-aspire/blob/cdffe26fc62acc264ff233a296c0616430d3a141/docs/fundamentals/aspire-sdk-templates.md) | [.NET Aspire templates](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/aspire-sdk-templates?branch=pr-en-us-3136) |
> Add dev-cert details to templates content

- docs/fundamentals/service-defaults.md
- docs/fundamentals/snippets/template/YourAppName/Extensions.cs
Update service defaults and add details about changes in 9.2 to filter request traces for the health endpoints.
Fixes #2939
---
|:--|:--|
| [docs/fundamentals/service-defaults.md](https://github.com/dotnet/docs-aspire/blob/693660fc0b9566a417f2c6b3a0cd3e71470bcbe5/docs/fundamentals/service-defaults.md) | [.NET Aspire service defaults](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/service-defaults?branch=pr-en-us-3138) |
> Update service defaults and add filtering details

- docs/snippets/azure/AppHost/Program.ConfigureServiceBusInfra.cs
The ConfigureServiceBusInfra snippet uses the Tier property to configure the Sku but this generates incorrect bicep when trying to deploy via azd and azure publisher. It should use the Name property instead.
Fixes https://github.com/dotnet/docs-aspire/issues/3158
> fix: update Service Bus SKU property from Tier to Name

- .github/workflows/snippets5001-release.yml
Added 5001
---
|:--|:--|
| [.github/workflows/snippets5001-release.yml](https://github.com/dotnet/docs-aspire/blob/b15d4685ec2bbf258165bd2ab644a359e49729f3/.github/workflows/snippets5001-release.yml) | [This is a basic workflow to help you get started with Actions](https://review.learn.microsoft.com/en-us/dotnet/aspire/.github/workflows/snippets5001-release?branch=pr-en-us-3369) |
> Added 5001

- docs/database/includes/azure-sql-hosting.md
The documentation listed azureSql as the SQLServer variable. But then when the database is referenced it uses postgres as the server that it's adding a database to. This change corrects the documentation so it references azureSql instead.
> Fixed documentation to use the correct variable name

- docs/azure/user-assigned-managed-identity.md
- docs/toc.yml
Add content for user-assigned managed ids.
Fixes #3325
---
|:--|:--|
| [docs/azure/user-assigned-managed-identity.md](https://github.com/dotnet/docs-aspire/blob/62bda17ebbae1853812b897d642200b3071f7734/docs/azure/user-assigned-managed-identity.md) | [User-assigned managed identities in .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/azure/user-assigned-managed-identity?branch=pr-en-us-3377) |
| [docs/toc.yml](https://github.com/dotnet/docs-aspire/blob/62bda17ebbae1853812b897d642200b3071f7734/docs/toc.yml) | [docs/toc](https://review.learn.microsoft.com/en-us/dotnet/aspire/toc?branch=pr-en-us-3377) |
> Add content for user-assigned managed ids

- docs/azure/container-registry-integration.md
- docs/azure/integrations-overview.md
- docs/azure/snippets/acr/AspireAcr.AppHost/AspireAcr.AppHost/AspireAcr.AppHost.csproj
- docs/azure/snippets/acr/AspireAcr.AppHost/AspireAcr.AppHost/Program.Existing.cs
- docs/azure/snippets/acr/AspireAcr.AppHost/AspireAcr.AppHost/Program.cs
- docs/azure/snippets/acr/AspireAcr.AppHost/AspireAcr.AppHost/Properties/launchSettings.json
- docs/azure/snippets/acr/AspireAcr.AppHost/AspireAcr.AppHost/api-identity.module.bicep
- docs/azure/snippets/acr/AspireAcr.AppHost/AspireAcr.AppHost/api-roles-my-acr.module.bicep
- docs/azure/snippets/acr/AspireAcr.AppHost/AspireAcr.AppHost/api.module.bicep
- docs/azure/snippets/acr/AspireAcr.AppHost/AspireAcr.AppHost/aspire-manifest.json
- docs/azure/snippets/acr/AspireAcr.AppHost/AspireAcr.AppHost/env.module.bicep
- docs/azure/snippets/acr/AspireAcr.AppHost/AspireAcr.AppHost/my-acr.module.bicep
- docs/toc.yml
Add ACR hosting integration content. Fixes #3222
---
|:--|:--|
| [docs/azure/container-registry-integration.md](https://github.com/dotnet/docs-aspire/blob/dfc236658b80090fb6937541b905911a305187e1/docs/azure/container-registry-integration.md) | [.NET Aspire Azure Container Registry integration (Preview)](https://review.learn.microsoft.com/en-us/dotnet/aspire/azure/container-registry-integration?branch=pr-en-us-3383) |
| [docs/azure/integrations-overview.md](https://github.com/dotnet/docs-aspire/blob/dfc236658b80090fb6937541b905911a305187e1/docs/azure/integrations-overview.md) | [Azure integrations overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/azure/integrations-overview?branch=pr-en-us-3383) |
| …
> Add ACR hosting integration content.

- docs/compatibility/9.3/azure-sql-server-default-uami-admin.md
- docs/compatibility/9.3/index.md
- docs/compatibility/toc.yml
Adds breaking changes content for Azure SQL Server admin user-assigned managed id.
Fixes #3386
---
|:--|:--|
| [docs/compatibility/9.3/azure-sql-server-default-uami-admin.md](https://github.com/dotnet/docs-aspire/blob/63b698beb4f538eafcbff2b3ae423b31d9dd82cd/docs/compatibility/9.3/azure-sql-server-default-uami-admin.md) | [AddAzureSqlServer assigns a dedicated user-assigned managed identity as the administrator](https://review.learn.microsoft.com/en-us/dotnet/aspire/compatibility/9.3/azure-sql-server-default-uami-admin?branch=pr-en-us-3391) |
| [docs/compatibility/9.3/index.md](https://github.com/dotnet/docs-aspire/blob/63b698beb4f538eafcbff2b3ae423b31d9dd82cd/docs/compatibility/9.3/index.md) | [Breaking changes in .NET Aspire …
> Adds breaking changes content for Azure SQL Server admin user-assigned managed id.

- docs/database/ef-core-migrations.md
I've added some explanatory notes to the article to explain:
- Why the migrations are called in a separate worker service (separation of concerns).
- That the `AddDatabase()` call in the App Host *project.cs* file doesn't create a database and you need to call `EnsureCreated()` in the API project, or take other similar actions.
- That data won't be persisted across restarts, unless you add a data volume to the container.
Fixes: #1846, #2336
---
|:--|:--|
| [docs/database/ef-core-migrations.md](https://github.com/dotnet/docs-aspire/blob/dd83f6d9face8b9661ae81a6cccd51afe41772e9/docs/database/ef-core-migrations.md) | [Apply Entity Framework Core migrations in .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/ef-core-migrations?branch=pr-e …
> Add explanatory notes to the EF Core Migrations tutorial.

- docs/azureai/azureai-inference-integration.md
- docs/includes/includes-client.md
- docs/includes/includes-hosting-and-client.md
- docs/includes/includes-hosting.md
- docs/toc.yml
Initial draft of Azure AI Inference content
Fixes #3394
---
|:--|:--|
| [docs/azureai/azureai-inference-integration.md](https://github.com/dotnet/docs-aspire/blob/e93fa7c127e11af13b6213787c0442d5572e0367/docs/azureai/azureai-inference-integration.md) | [.NET Aspire Azure AI Inference integration (Preview)](https://review.learn.microsoft.com/en-us/dotnet/aspire/azureai/azureai-inference-integration?branch=pr-en-us-3399) |
| [docs/toc.yml](https://github.com/dotnet/docs-aspire/blob/e93fa7c127e11af13b6213787c0442d5572e0367/docs/toc.yml) | [docs/toc](https://review.learn.microsoft.com/en-us/dotnet/aspire/toc?branch=pr-en-us-3399) |
> Initial draft of Azure AI Inference content

- docs/database/seed-database-data.md
Updates the [Seed data in database using .NET Aspire](https://learn.microsoft.com/dotnet/aspire/database/seed-database-data) article to .NET Aspire 9.2:
- Ensures container volumes and bind mounts are correctly described and differentiated.
- Describes the `WithCreationScript()` method for SQL Server and how to use it.
- Updates links to the code in the [DataContainers sample](https://github.com/dotnet/aspire-samples/blob/main/samples/DatabaseContainers/README.md)
Note: The `WithCreationScript()` method is not supported for PostgreSQL and MySQL in .NET Aspire 9.2 but will be in 9.3. This article should be updated after that release.
Fixes #3384
---
|:--|:--|
| [docs/database/seed-database-data.md](https://github.com/dotnet/docs-aspire/blob/004aa85ad1017463f28549 …
> Update Seed data in database article to 9.2

- docs/azure/azure-app-configuration-integration.md
- docs/database/azure-cosmos-db-integration.md
- docs/snippets/azure/AppHost/Program.ConfigureAppConfigInfra.cs
- docs/toc.yml
Adds Azure App Configuration.
- Fixes #3395
---
|:--|:--|
| [docs/azure/azure-app-configuration-integration.md](https://github.com/dotnet/docs-aspire/blob/ff7b734281f1f4655744602020f707f76d8d1613/docs/azure/azure-app-configuration-integration.md) | [.NET Aspire Azure App Configuration integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/azure/azure-app-configuration-integration?branch=pr-en-us-3500) |
| [docs/database/azure-cosmos-db-integration.md](https://github.com/dotnet/docs-aspire/blob/ff7b734281f1f4655744602020f707f76d8d1613/docs/database/azure-cosmos-db-integration.md) | [.NET Aspire Azure Cosmos DB integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/azure-cosmos-db-integration?branch=pr-en-us-3500) |
| …
> Adds Azure App Configuration integration

- docs/whats-new/dotnet-aspire-9.3.md
Tweaking some wording to make the doc more correct.
---
|:--|:--|
| [docs/whats-new/dotnet-aspire-9.3.md](https://github.com/dotnet/docs-aspire/blob/bf3124dc99db761e63cfd6e05a2f50cd18d025a0/docs/whats-new/dotnet-aspire-9.3.md) | [What's new in .NET Aspire 9.3](https://review.learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9.3?branch=pr-en-us-3504) |
> Aspire 9.3 What's New Feedback

- docs/database/seed-database-data.md
- docs/get-started/build-aspire-apps-with-nodejs.md
This fixes the build error introduced by the sample being updated.
@IEvangelist this is a good example as to why we stopped using sample references in the .NET docs. It's very fragile and can not only break the builds, but if someone changes some code, any highlights or ranges will be out of date and can break the article itself for a customer.
---
|:--|:--|
| [docs/database/seed-database-data.md](https://github.com/dotnet/docs-aspire/blob/a922bd5446e62a9eec4da9ff25e627ffd26951bf/docs/database/seed-database-data.md) | [Seed data in a database using .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/seed-database-data?branch=pr-en-us-3615) |
| [docs/get-started/build-aspire-apps-with-nodejs.md](https://github.com/dotnet/docs-aspire/blob/ …
> Fix errors in seed-database-data.md

- docs/azure/container-registry-integration.md
It referred to the Azure Functions integration instead of the Azure Container Registry integration. This PR corrects that.
Fixes #3708
---
|:--|:--|
| [docs/azure/container-registry-integration.md](https://github.com/dotnet/docs-aspire/blob/a463c25b5351da92c185ab2ed3cb44e23f0068ce/docs/azure/container-registry-integration.md) | [.NET Aspire Azure Container Registry integration (Preview)](https://review.learn.microsoft.com/en-us/dotnet/aspire/azure/container-registry-integration?branch=pr-en-us-3721) |
> Fixed typo in Azure Container Registry article

- docs/database/includes/mysql-app-host.md
- docs/database/includes/postgresql-app-host.md
- docs/database/mongodb-integration.md
- docs/database/snippets/postgres-data-volume-deploy/.aspire/settings.json
- docs/database/snippets/postgres-data-volume-deploy/AppHost.cs
- docs/database/snippets/postgres-data-volume-deploy/PostgresDataVolumeDeploy.csproj
- docs/database/snippets/postgres-data-volume-deploy/Properties/launchSettings.json
- docs/database/snippets/postgres-data-volume-deploy/appsettings.Development.json
- docs/database/snippets/postgres-data-volume-deploy/appsettings.json
- docs/database/snippets/postgres-data-volume-deploy/postgres-data-volume-deploy.sln
Added notes to the PostgreSQL, MySQL, and MongoDB articles explaining that data volumes are not compatible with deployment to ACA. For PostgreSQL, suggested using Azure Database for PostgreSQL. For the others, deploying to k8s because there's no equivalent integration.
Fixes #3387
---
|:--|:--|
| [docs/database/mongodb-integration.md](https://github.com/dotnet/docs-aspire/blob/1e6db04690e52e303e55d11e6820fa98f3792776/docs/database/mongodb-integration.md) | [.NET Aspire MongoDB database integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/mongodb-integration?branch=pr-en-us-3706) |
> Documents the issue with deploying data volumes to ACA.

- docs/get-started/upgrade-to-aspire-9.md
With 8.0 installed via a workload, using `dotnet new` to create an Aspire project creates an 8.0 version. This update fixes that problem and gets the 9.0 templates installed.
Fixes #3118 
---
|:--|:--|
| [docs/get-started/upgrade-to-aspire-9.md](https://github.com/dotnet/docs-aspire/blob/3cc374fbf198d40c1c8b5ac0bd160a9af2578542/docs/get-started/upgrade-to-aspire-9.md) | [docs/get-started/upgrade-to-aspire-9](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/upgrade-to-aspire-9?branch=pr-en-us-3722) |
> Add instructions to get rid of .NET Aspire 8 before upgrading to 9

- docs/community-toolkit/hosting-mysql-extensions.md
- docs/community-toolkit/overview.md
- docs/toc.yml
This pull request adds documentation for the new `.NET Aspire Community Toolkit MySql hosting extensions` package, which provides additional functionality for MySql hosting in .NET applications.
/cc @aaronpowell 
---
|:--|:--|
| [docs/community-toolkit/hosting-mysql-extensions.md](https://github.com/dotnet/docs-aspire/blob/6af1ef33dd29b3406f607cdd1da99fba6a96745d/docs/community-toolkit/hosting-mysql-extensions.md) | [.NET Aspire Community Toolkit MySql hosting extensions](https://review.learn.microsoft.com/en-us/dotnet/aspire/community-toolkit/hosting-mysql-extensions?branch=pr-en-us-3664) |
| [docs/community-toolkit/overview.md](https://github.com/dotnet/docs-aspire/blob/6af1ef33dd29b3406f607cdd1da99fba6a96745d/docs/community-toolkit/overview.md) | …
> Add article for CommunityToolkit.Aspire.Hosting.MySql.Extensions

- docs/community-toolkit/hosting-python-extensions.md
Added documentation for the uv aspire integration from the [community toolkit](https://github.com/CommunityToolkit/Aspire/tree/main/src/CommunityToolkit.Aspire.Hosting.Python.Extensions).
Documentation has been added to the already existing [Python Extension documentation](https://learn.microsoft.com/en-us/dotnet/aspire/community-toolkit/hosting-python-extensions?tabs=dotnet-cli).
Fixes #2426
---
|:--|:--|
| [docs/community-toolkit/hosting-python-extensions.md](https://github.com/dotnet/docs-aspire/blob/1edfbf8645b3cc571a00b9cb1766c844aad29742/docs/community-toolkit/hosting-python-extensions.md) | [Community Toolkit Python hosting extensions](https://review.learn.microsoft.com/en-us/dotnet/aspire/community-toolkit/hosting-python-extensions?branch=pr-en-us-4033) …
> Adds uv documentation in Python Extensions

- docs/fundamentals/setup-tooling.md
- docs/includes/aspire-prereqs.md
Add details about Aspire 9.4 support of .NET 10 Preview 5.
Fixes #3820
---
|:--|:--|
| [docs/fundamentals/setup-tooling.md](https://github.com/dotnet/docs-aspire/blob/db9b458e21c3218adeb4a177656e465e72c645f9/docs/fundamentals/setup-tooling.md) | [.NET Aspire setup and tooling](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/setup-tooling?branch=pr-en-us-4040) |
> Add details about Aspire 9.4 support of .NET 10 Preview 5.

- docs/fundamentals/aspire-sdk-templates.md
- docs/fundamentals/includes/install-templates.md
- docs/fundamentals/setup-tooling.md
Moved the template installation instructions into an include file, then linked to that include file from both:
- [.NET Aspire setup and tooling](https://learn.microsoft.com/dotnet/aspire/fundamentals/setup-tooling)
- [.NET Aspire templates](https://learn.microsoft.com/dotnet/aspire/fundamentals/aspire-sdk-templates)
Fixes #3864
---
|:--|:--|
| [docs/fundamentals/aspire-sdk-templates.md](https://github.com/dotnet/docs-aspire/blob/8b14a274334fb6051d86d67a46db7d333c9383bc/docs/fundamentals/aspire-sdk-templates.md) | [.NET Aspire templates](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/aspire-sdk-templates?branch=pr-en-us-4048) |
| [docs/fundamentals/setup-tooling.md](https://github.com/dotnet/docs-aspire/blob/8b14a274334fb6051d86d67a46db7d333c …
> Include template installation instructions in the ".NET Aspire templates" article.

- docs/fundamentals/setup-tooling.md
Fixed the name of the ASPIRE_CONTAINER_RUNTIME variable. DOTNET_ASPIRE_CONTAINER_RUNTIME was a old version.
Fixes #3863
---
|:--|:--|
| [docs/fundamentals/setup-tooling.md](https://github.com/dotnet/docs-aspire/blob/d43b5a0626075cec36325e884083ecb5ba60e8f2/docs/fundamentals/setup-tooling.md) | [.NET Aspire setup and tooling](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/setup-tooling?branch=pr-en-us-4097) |
> Fixed the name of the ASPIRE_CONTAINER_RUNTIME variable.

- docs/get-started/aspire-overview.md
Fixes #3860 
---
|:--|:--|
| [docs/get-started/aspire-overview.md](https://github.com/dotnet/docs-aspire/blob/0bf1e6d4a0441848bfca46ac3ad50ad4d93d5691/docs/get-started/aspire-overview.md) | [Aspire overview](https://review.learn.microsoft.com/en-us/dotnet/aspire/get-started/aspire-overview?branch=pr-en-us-3904) |
> Initial update to simplify overview

- docs/cli-reference/aspire-add.md
- docs/cli-reference/aspire-config-delete.md
- docs/cli-reference/aspire-config-get.md
- docs/cli-reference/aspire-config-list.md
- docs/cli-reference/aspire-config-set.md
- docs/cli-reference/aspire-config.md
- docs/cli-reference/aspire-deploy.md
- docs/cli-reference/aspire-exec.md
- docs/cli-reference/aspire-new.md
- docs/cli-reference/aspire-publish.md
- docs/cli-reference/aspire-run.md
- docs/cli-reference/aspire.md
- docs/cli-reference/includes/config-file-description.md
- docs/cli-reference/includes/config-settings-table.md
- docs/cli-reference/includes/mode-preview.md
- docs/cli-reference/includes/option-debug.md
- docs/cli-reference/includes/option-help.md
- docs/cli-reference/includes/option-project.md
- docs/cli-reference/includes/option-version.md
- docs/cli-reference/includes/option-wait.md
- docs/cli-reference/includes/project-search-logic-description.md
- docs/cli/install.md
- docs/cli/overview.md
- docs/fundamentals/setup-tooling.md
- docs/get-started/build-your-first-aspire-app.md
- docs/toc.yml
Fixes #4027
Fixes #4098
Fixes #4026 
Fixes #4028 
---
|:--|:--|
| [docs/cli-reference/aspire-add.md](https://github.com/dotnet/docs-aspire/blob/c643ab137a78549dcd699efa1c4a246ecf4c1291/docs/cli-reference/aspire-add.md) | [docs/cli-reference/aspire-add](https://review.learn.microsoft.com/en-us/dotnet/aspire/cli-reference/aspire-add?branch=pr-en-us-3905) |
| [docs/cli-reference/aspire-config-delete.md](https://github.com/dotnet/docs-aspire/blob/c643ab137a78549dcd699efa1c4a246ecf4c1291/docs/cli-reference/aspire-config-delete.md) | [docs/cli-reference/aspire-config-delete](https://review.learn.microsoft.com/en-us/dotnet/aspire/cli-reference/aspire-config-delete?branch=pr-en-us-3905) |
| …
> Initial drafts of .NET Aspire CLI docs

- docs/fundamentals/dashboard/standalone.md
- Replaced the alias `sls` with the PowerShell cmdlet "Select-String"
- Returned just the token instead of the whole line from the container log.
- Copied the token to the clipboard to save the users a step.
Fixes #4134
---
|:--|:--|
| [docs/fundamentals/dashboard/standalone.md](https://github.com/dotnet/docs-aspire/blob/8c73309760b724eb56252e21bc6f4ae2a69c4a95/docs/fundamentals/dashboard/standalone.md) | [Standalone .NET Aspire dashboard](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/standalone?branch=pr-en-us-4135) |
> Improved the scripts that retrieve the login token from the container logs

- docs/index.yml
- docs/toc.yml
- docs/whats-new/index.yml
- docs/whats-new/toc.yml
Update API reference links to version 9.4 and add release notes for .NET Aspire 9.4
Fixes #4177
---
|:--|:--|
| [docs/index.yml](https://github.com/dotnet/docs-aspire/blob/34df3411ad362297e5ce89e8c9f816fe2f30b98c/docs/index.yml) | [Limit summary to 400 characters](https://review.learn.microsoft.com/en-us/dotnet/aspire/index?branch=pr-en-us-4176) |
| [docs/toc.yml](https://github.com/dotnet/docs-aspire/blob/34df3411ad362297e5ce89e8c9f816fe2f30b98c/docs/toc.yml) | [docs/toc](https://review.learn.microsoft.com/en-us/dotnet/aspire/toc?branch=pr-en-us-4176) |
| [docs/whats-new/index.yml](https://github.com/dotnet/docs-aspire/blob/34df3411ad362297e5ce89e8c9f816fe2f30b98c/docs/whats-new/index.yml) | [.NET Aspire — what's …
> Correct links to point to 9.4 bits

- docs/messaging/kafka-integration.md
The same connection name should be used when you call `AddKafka` in the AppHost and both `AddKafkaProducer` and `AddKafkaConsumer` in consuming projects, otherwise the latter won't start. I've ensured the name `kafka` is used for connections throughout the article add added two tips.
Fixes #3824
---
|:--|:--|
| [docs/messaging/kafka-integration.md](https://github.com/dotnet/docs-aspire/blob/5c4008ddd0d346a0bde6d2f62c9fd9c44cc433ab/docs/messaging/kafka-integration.md) | [.NET Aspire Apache Kafka integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/kafka-integration?branch=pr-en-us-4197) |
> Fix Kafka article to use consistent connection names.

- docs/database/ef-core-migrations.md
Changes code to use new versions of Aspire and .NET. Also corrects some code highlighting.
Fixes #3714 
---
|:--|:--|
| [docs/database/ef-core-migrations.md](https://github.com/dotnet/docs-aspire/blob/3aa126ba5b243ad3b975bb75d84dce092e66d2e4/docs/database/ef-core-migrations.md) | [Apply Entity Framework Core migrations in .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/database/ef-core-migrations?branch=pr-en-us-4195) |
> Upgrade tutorial to .NET 9.0 and Aspire 9.4.0

- docs/azure/azure-app-configuration-integration.md
- docs/azure/container-registry-integration.md
- docs/azureai/azureai-foundry-integration.md
- docs/azureai/azureai-openai-integration.md
- docs/azureai/azureai-search-document-integration.md
- docs/caching/includes/azure-redis-app-host.md
- docs/database/includes/cosmos-app-host.md
- docs/database/includes/postgresql-flexible-server.md
- docs/messaging/azure-event-hubs-integration.md
- docs/messaging/azure-service-bus-integration.md
- docs/messaging/azure-web-pubsub-integration.md
- docs/real-time/azure-signalr-scenario.md
- docs/security/azure-security-key-vault-integration.md
- docs/storage/includes/storage-bicep.md
I've moved the **Provisioning-generated Bicep** and **Customize provisioning infrastructure** towards the end of the **Host integration** section in all Azure integration articles where it appears. Now students can read about all ways to add the relevant resources to the App Host and *then* read about Bicep and customizing provisioning. I've also made them consistently H3 and H4 level sections respectively. 
Fixes #4276
---
|:--|:--|
| [docs/azure/azure-app-configuration-integration.md](https://github.com/dotnet/docs-aspire/blob/5d4dd5db2740b57cbee0e52e745ab8ef744eccf4/docs/azure/azure-app-configuration-integration.md) | [.NET Aspire Azure App Configuration integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/azure/azure-app-configuration-integrat …
> Move Bicep content in Azure articles to improve flow

- docs/azure/customize-azure-resources.md
Added a tip explaining that InfrastructureResolver can customize many Azure resources simultaneously. This contrasts with the ConfigureInfrastructure method, which only applies to a single resource. This change helps developers choose the right customization method.
Fixes #4287
---
|:--|:--|
| [docs/azure/customize-azure-resources.md](https://github.com/dotnet/docs-aspire/blob/61c0a15b8cdbf832dc18903429d9da6db3188a19/docs/azure/customize-azure-resources.md) | [Customize Azure resources](https://review.learn.microsoft.com/en-us/dotnet/aspire/azure/customize-azure-resources?branch=pr-en-us-4288) |
> Clarify the difference between InfrastructureResolver and ConfigureInfrastructure to customize Azure resources

- docs/troubleshooting/allow-unsecure-transport.md
Make the note about this being a security feature stand out.
---
|:--|:--|
| [docs/troubleshooting/allow-unsecure-transport.md](https://github.com/dotnet/docs-aspire/blob/1ad85f1c6d40cb577fd537c150892ed53992e061/docs/troubleshooting/allow-unsecure-transport.md) | [Allow unsecure transport in .NET Aspire](https://review.learn.microsoft.com/en-us/dotnet/aspire/troubleshooting/allow-unsecure-transport?branch=pr-en-us-4350) |
> Add warning format to note about unsecured transport setting

- docs/testing/write-your-first-test.md
Make it clearer how to configure xUnit.net to output logs to test output.
Updated the description to specify 'xUnit.net' instead of 'xUnit'.
---
|:--|:--|
| [docs/testing/write-your-first-test.md](https://github.com/dotnet/docs-aspire/blob/838be9b01a362fd772101eb089a36b447c49938f/docs/testing/write-your-first-test.md) | [docs/testing/write-your-first-test](https://review.learn.microsoft.com/en-us/dotnet/aspire/testing/write-your-first-test?branch=pr-en-us-4356) |
> Correct description for xUnit.net in testing guide

- docs/messaging/azure-service-bus-integration.md
The correct `connectionName` to pass to `AddAzureServiceBusClient()` depends on whether you subscribed to a topic in the AppHost.
- If you did, it must match the name you passed to `AddServiceBusSubscription()`
- Otherwise, it must match the name you passed to `AddAzureServiceBus()`
Fixes #4718
---
|:--|:--|
| [docs/messaging/azure-service-bus-integration.md](https://github.com/dotnet/docs-aspire/blob/c88b550528ffff4ba80a80b19d94aeb32cb3ca18/docs/messaging/azure-service-bus-integration.md) | [.NET Aspire Azure Service Bus integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/azure-service-bus-integration?branch=pr-en-us-4720) |
> Correct the description of connection names in the Azure Service Bus client integration.

- docs/messaging/kafka-integration.md
Describes how to use a connection string to work with existing Kafka clusters. The integration uses the [confluentinc/confluent-local](https://hub.docker.com/r/confluentinc/confluent-local) image, which doesn't support anything complex, such as multiple brokers.
Fixes #3619
---
|:--|:--|
| [docs/messaging/kafka-integration.md](https://github.com/dotnet/docs-aspire/blob/1e96af9a9b9beec1022e7ff4c259a3cd5f0180f7/docs/messaging/kafka-integration.md) | [.NET Aspire Apache Kafka integration](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/kafka-integration?branch=pr-en-us-4516) |
> Add a new section on working with existing Kafka cluters.
